function t(key, ...args) {
    const lang = (typeof gameState !== 'undefined' && gameState.language) || 'zh';
    const str = translations[lang] && translations[lang][key];
    if (str === undefined) return key;
    if (args.length === 0) return str;
    return str.replace(/\{(\d+)\}/g, (match, index) => {
        const i = parseInt(index);
        return i < args.length ? args[i] : match;
    });
}

function getLocalizedGuideData() {
    const lang = (typeof gameState !== 'undefined' && gameState.language) || 'zh';
    return guideData[lang] || guideData.zh;
}

const translations = {
    zh: {
        'menu.startBoss': '开始 Boss 战',
        'menu.startBossDesc': '挑战强大的Boss敌人',
        'menu.startTraining': '进入训练场',
        'menu.startTrainingDesc': '在不会反击的假人上练习武器',
        'menu.customizeMech': '定制机甲',
        'menu.customizeDesc': '配置武器装备，自定义作战风格',
        'menu.guide': '游戏简介',
        'menu.settings': '设置',
        'menu.settingsDesc': '机甲命名等个人偏好',
        'settings.title': '设置',
        'settings.subtitle': 'PERSONAL PREFERENCES',
        'settings.mechNameLabel': '机甲命名',
        'settings.mechNameHint': '为你的座驾起一个专属代号 (1–24 字符)',
        'settings.save': '保存',
        'settings.saved': '已保存',
        'settings.reset': '恢复默认',
        'settings.back': '返回',
        'settings.contactHeader': '// CONTACT — 联络作者',
        'settings.contactGreeting': '欢迎联系我！',
        'settings.contactBili': 'B 站：ガンダムさん',
        'settings.contactBiliUid': 'UID：3493134971439675',
        'menu.selectLevel': '选择关卡',
        'menu.bossModeSub': 'Boss战模式 - 挑战强大的敌人',
        'menu.difficulty': '难度: ',
        'menu.locked': '🔒 未解锁',
        'menu.back': '返回',
        'menu.backArrow': '← 返回',
        'menu.mainMenu': '主菜单',
        'menu.backToMenu': '返回主菜单',
        'menu.backToCatalog': '返回目录',
        'menu.backTo': '返回{0}',

        'cfg.selected': '已选择：{0}',
        'cfg.leftHand': '左手武器',
        'cfg.rightHand': '右手武器',
        'cfg.leftShoulder': '左肩武器',
        'cfg.rightShoulder': '右肩武器',
        'cfg.hiddenAbility': '隐藏机能',
        'cfg.leftKey': '(左键)',
        'cfg.rightKey': '(右键)',
        'cfg.qKey': '(Q键)',
        'cfg.eKey': '(E键)',
        'cfg.shiftKey': '(Shift键)',
        'cfg.none': '无',
        'cfg.currentConfig': '当前配置：',
        'cfg.invincibleOn': '无敌模式：开启',
        'cfg.invincibleOff': '无敌模式：关闭',
        'cfg.startGame': '开始游戏',
        'cfg.configHint': '点击武器槽位选择武器，然后点击开始游戏',
        'cfg.customHint': '点击武器槽位选择武器，然后返回主菜单',

        'hud.mech': '机甲: {0}',
        'hud.health': '❤️ 生命值: ',
        'hud.invincible': '⭐ 无敌模式 ⭐',
        'hud.leftKey': '🖊️ 左键 - ',
        'hud.rightKey': '🖐️ 右键 - ',
        'hud.dodgeKey': '⚡ 空格 - ',
        'hud.dodge': '闪避: {0}',
        'hud.lockKey': '🎯 F键 - ',
        'hud.lockMode': '锁定模式: {0}',
        'hud.shiftKey': '🛡️ Shift键 - ',
        'hud.noWeapon': '无武器',
        'hud.noHidden': '无隐藏机能',
        'hud.dodgeLimit': '闪避限制',
        'hud.cKey': '🔄 C键 - ',
        'hud.switchTarget': '切换目标',
        'hud.qKey': '🚀 Q键 - ',
        'hud.eKey': '🚀 E键 - ',
        'hud.noLeftShoulder': '无左肩武器',
        'hud.noRightShoulder': '无右肩武器',
        'hud.ctrlKey': '🛠️ Ctrl键 - ',
        'hud.repairKit': '维修包: {0}/{1}',
        'hud.repairEmpty': '维修包: 已用完',
        'hud.mode': '模式: {0}',
        'hud.bossKills': 'Boss击杀数: {0}',

        'enemy.elite': '精英',

        'ui.paused': '游戏暂停',
        'ui.pauseHint': '按 P 继续游戏',
        'ui.pauseBtn': '暂停',
        'ui.gameOver': '游戏结束',
        'ui.totalDamage': '造成总伤害: {0}',
        'ui.spaceReturn': '按空格键返回主菜单',
        'ui.victory': '🎉 胜利！🎉',
        'ui.defeated': '击败了 {0}！',
        'ui.finalScore': '最终分数: {0}',
        'ui.blindStatus': '信号干扰',
        'ui.blindRemaining': '剩余时间: {0}秒',
        'ui.langToggle': 'EN',
        'ui.gameTitle': '机甲战斗游戏',

        'boss.CRIMSON_KING': '血红之王',
        'boss.SUBLIME_MOON': '冰之姬',
        'boss.STAR_DEVOURER': '噬星者',
        'boss.UGLY_EMPEROR': '丑皇',
        'boss.MAGNUS_EXEC': '机甲执政官 Magnus',
        'boss.HIVE_MIND': '蜂巢意识',
        'boss.YUKIKON': '剑舞者 雪魂',
        'boss.PROTEUS': '变形机甲 普罗忒斯',
        'boss.TRIUMVIRATE': '元素三主神',
        'boss.unknown': '未知Boss',
        'bossDesc.CRIMSON_KING': '深红色的恐怖统治者，掌控着黑暗的力量',
        'bossDesc.SUBLIME_MOON': '青蓝色的神秘支配者，散发着冰冷的月光之力',
        'bossDesc.STAR_DEVOURER': '黑白相间的虚无毁灭者，吞噬一切光明与黑暗',
        'bossDesc.UGLY_EMPEROR': '丑陋扭曲的混沌统治者，掌控着扭曲与混乱的力量',
        'bossDesc.MAGNUS_EXEC': '重装机甲执政官，肩载双炮塔、远程压制与轨道炮击',
        'bossDesc.HIVE_MIND': '由蜂群守护的女王意识体，本体脆弱却难以触及，死亡后分裂为四道残识',
        'bossDesc.YUKIKON': '高速近战决斗者，凭瞬移、突袭与影分身贴身压制，不闪避子弹只用距离换速度',
        'bossDesc.PROTEUS': '依玩家距离实时切换近战长戟、霰弹机动、远程炮塔三种结构，重组瞬间脆弱可乘',

        'boss.pierce': '扎穿!',
        'boss.blind': '失明',
        'boss.immune': '免疫',
        'boss.clone': '分身',
        'boss.burn': '燃烧',

        'boss.blindActive': '失明激活中 {0}s',
        'boss.blindUnlockNeed': '失明技能解锁: 还需 {0} 伤害',
        'boss.blindUnlocked': '失明技能已解锁',
        'boss.blindCooldown': '失明冷却中 {0}s {1}',
        'boss.blindReady': '失明技能准备就绪 {0}',
        'boss.phase1': '(一阶段)',
        'boss.phase2label': '(二阶段)',
        'boss.phase2Visible': '二阶段 - 距离 {0}/{1} - 可见可锁定',
        'boss.phase2Cloaked': '二阶段 - 距离 {0}/{1} - 隐身状态',
        'boss.phase2Trigger': '二阶段触发: 还需 {0} 伤害',

        'mode.BOSS_BATTLE': 'Boss战模式',
        'modeDesc.BOSS_BATTLE': '挑战强大的Boss敌人',
        'mode.TRAINING': '训练场',
        'modeDesc.TRAINING': '不会反击的假人靶 | 死后立即补充',
        'mech.HYBRID': '混合机甲',

        'weapon.gun': '自动步枪',
        'weapon.sword': '脉冲光束军刀',
        'weapon.laser_spear': '镭射长枪',
        'weapon.cluster_missile': '分裂飞弹',
        'weapon.laser_rifle': '镭射步枪',
        'weapon.laser_smg': '镭射机枪',
        'weapon.shotgun': '霰弹枪',
        'weapon.rocket_launcher': '火箭筒',
        'weapon.minigun': '加特林',
        'weapon.flamethrower': '火焰喷射器',
        'weapon.missile_launcher': '15连导弹发射器',
        'weapon.high_track_missile': '高诱导飞弹',
        'weapon.cluster_bomb_missile': '集束飞弹',
        'weapon.mine_layer_missile': '布雷飞弹',
        'weapon.det_cord_missile': '爆导索飞弹',
        'weapon.laser_turret': '镭射炮台',
        'weapon.ciws': '近防炮',
        'weapon.plasma_missile': '6连电浆飞弹',
        'weapon.super_weapon': '超级导弹',
        'weapon.moonlight_greatsword': '月光大剑',
        'weapon.pulse_shield': '脉冲护盾',
        'weapon.emp': 'EMP电磁脉冲',
        'weapon.counter_mech': '反制重击',
        'weapon.decoy_clone': '诱饵分身',
        'weapon.overdrive_burst': '超限爆发',
        'weapon.repair_protocol': '应急修复',
        'weapon.god_mode': '金手指',

        'weaponDesc.gun': '远程射击 | 高射速 | 预瞄功能',
        'weaponDesc.sword': '近战攻击 | 高伤害 | 刀推功能',
        'weaponDesc.laser_spear': '中距离突刺 | 蓄力攻击 | 推进功能',
        'weaponDesc.cluster_missile': '大弹近炸分裂8子弹 | 持续索敌 | 高追踪',
        'weaponDesc.laser_rifle': '长按蓄力 | 预瞄射线 | 过热系统',
        'weaponDesc.laser_smg': '速射镭射 | 出手快 | 单发低伤低热 | 持续输出会过热',
        'weaponDesc.shotgun': '近距锥形扩散 | 8颗弹丸 | 短射程高爆发',
        'weaponDesc.rocket_launcher': 'AOE火箭 | 中心强边缘弱 | 单发膛',
        'weaponDesc.minigun': '200发弹链 | 单发伤害2倍步枪(近距离) | 远距离衰减至30% | 装填45秒',
        'weaponDesc.flamethrower': '持续喷射 30° 火焰锥 | 射程 240 | 距离衰减 | 过热限制',
        'weaponDesc.missile_launcher': '强追踪1.1秒 | 范围爆炸 | 高伤害',
        'weaponDesc.high_track_missile': '单发 | 极高追踪 | 5倍伤害 | 慢速',
        'weaponDesc.cluster_bomb_missile': '空中投放10枚子弹 | L30°/R45°轮射 | 投放期间无敌',
        'weaponDesc.mine_layer_missile': '飞行中每0.7秒布置高爆机雷 | 可被拦截',
        'weaponDesc.det_cord_missile': '尾部拖出爆导索 | 引爆后沿索连环 AOE | 单点伤害2/3母弹',
        'weaponDesc.laser_turret': '在原地部署镭射炮台 | 12秒内自动射击600射程内敌人 | 弹仓2发',
        'weaponDesc.ciws': '自动拦截制导武器 | 30发弹仓 | 优先打导弹',
        'weaponDesc.plasma_missile': '近炸引信 | 电浆场持续伤害 | 可叠加',
        'weaponDesc.super_weapon': '100伤害 | 一次战斗只能用一次 | 占用双槽位',
        'weaponDesc.moonlight_greatsword': '200伤害 | 超大范围光刃 | 占用4槽位 | 一次性',
        'weaponDesc.pulse_shield': '完全免伤 | 14.4秒持续 | 40秒冷却',
        'weaponDesc.emp': '范围伤害+僵直 | 距离越远伤害越低 | 18秒冷却',
        'weaponDesc.counter_mech': '3秒减伤40% | 反射250%伤害 | 15秒冷却',
        'weaponDesc.decoy_clone': '释放3诱饵 | 4秒隐身 | 35秒冷却',
        'weaponDesc.overdrive_burst': '6秒爆发 | 伤害×3 移速×3 | 自损30%血 受伤×2 | 30秒冷却',
        'weaponDesc.repair_protocol': '5秒修复 | 移速×1.5 每秒回5血 | 期间无法攻击 | 满血溢出至+50护盾 | 35秒冷却',
        'weaponDesc.god_mode': '【调试用】释放即瞬杀场上一切 | 无冷却 无特效',

        'ws.attacking': '攻击中...',
        'ws.stagger': '僵直: {0}秒',
        'ws.dashPush': '刀推中...',
        'ws.cooldown': '冷却: {0}秒',
        'ws.cooldownS': '冷却: {0}s',
        'ws.ready': '准备就绪',
        'ws.readyShort': '就绪',
        'ws.reloading': '重装中 {0}s',
        'ws.ammoEmpty': '弹药耗尽！自动重装',
        'ws.ammo': '弹药: {0}/{1}',
        'ws.overheat': '过热! {0}s',
        'ws.charging': '蓄力中 {0}%',
        'ws.coolingDown': '冷却中...',
        'ws.heat': '热量: {0}/{1}',
        'ws.rushing': '冲锋中！',
        'ws.recovering': '恢复中',
        'ws.launching': '发射中... ({0}枚)',
        'ws.launchingSimple': '发射中...',
        'ws.shielding': '护盾中: {0}秒',
        'ws.countering': '反制中: {0}s',
        'ws.stealth': '隐身中: {0}s',
        'ws.overdriveActive': '超限爆发: {0}s',
        'ws.repairActive': '应急修复: {0}s',
        'ws.slashing': '斩击中...',
        'ws.used': '已使用',
        'ws.cooldownRemaining': '冷却中 {0}s',

        'player.dodging': '闪避中...',
        'player.dodgeCooldown': '闪避冷却: {0}秒',
        'player.dodgeReady': '闪避就绪',
        'player.softLock': '软锁',
        'player.hardLock': '硬锁',
        'player.manualLock': '手动锁',
    },

    en: {
        'menu.startBoss': 'Start Boss Battle',
        'menu.startBossDesc': 'Challenge powerful bosses',
        'menu.startTraining': 'Enter Training Ground',
        'menu.startTrainingDesc': 'Practice weapons on passive dummies',
        'menu.customizeMech': 'Customize Mech',
        'menu.customizeDesc': 'Configure weapons & combat style',
        'menu.guide': 'Game Guide',
        'menu.settings': 'Settings',
        'menu.settingsDesc': 'Mech callsign and other preferences',
        'settings.title': 'SETTINGS',
        'settings.subtitle': 'PERSONAL PREFERENCES',
        'settings.mechNameLabel': 'Mech Callsign',
        'settings.mechNameHint': 'Name your personal mech (1–24 chars)',
        'settings.save': 'Save',
        'settings.saved': 'Saved',
        'settings.reset': 'Reset',
        'settings.back': 'Back',
        'settings.contactHeader': '// CONTACT — REACH OUT',
        'settings.contactGreeting': 'Feel free to get in touch!',
        'settings.contactBili': 'Bilibili: ガンダムさん',
        'settings.contactBiliUid': 'UID: 3493134971439675',
        'menu.selectLevel': 'Select Level',
        'menu.bossModeSub': 'Boss Battle - Challenge powerful bosses',
        'menu.difficulty': 'Difficulty: ',
        'menu.locked': '🔒 Locked',
        'menu.back': 'Back',
        'menu.backArrow': '← Back',
        'menu.mainMenu': 'Main Menu',
        'menu.backToMenu': 'Return to Menu',
        'menu.backToCatalog': 'Back to Catalog',
        'menu.backTo': 'Back to {0}',

        'cfg.selected': 'Selected: {0}',
        'cfg.leftHand': 'Left Hand',
        'cfg.rightHand': 'Right Hand',
        'cfg.leftShoulder': 'Left Shoulder',
        'cfg.rightShoulder': 'Right Shoulder',
        'cfg.hiddenAbility': 'Hidden Ability',
        'cfg.leftKey': '(LMB)',
        'cfg.rightKey': '(RMB)',
        'cfg.qKey': '(Q)',
        'cfg.eKey': '(E)',
        'cfg.shiftKey': '(Shift)',
        'cfg.none': 'None',
        'cfg.currentConfig': 'Current Config:',
        'cfg.invincibleOn': 'Invincible: ON',
        'cfg.invincibleOff': 'Invincible: OFF',
        'cfg.startGame': 'Start Game',
        'cfg.configHint': 'Click weapon slots to configure, then Start Game',
        'cfg.customHint': 'Click weapon slots to configure, then return to menu',

        'hud.mech': 'Mech: {0}',
        'hud.health': '❤️ HP: ',
        'hud.invincible': '⭐ Invincible ⭐',
        'hud.leftKey': '🖊️ LMB - ',
        'hud.rightKey': '🖐️ RMB - ',
        'hud.dodgeKey': '⚡ Space - ',
        'hud.dodge': 'Dodge: {0}',
        'hud.lockKey': '🎯 F - ',
        'hud.lockMode': 'Lock: {0}',
        'hud.shiftKey': '🛡️ Shift - ',
        'hud.noWeapon': 'No Weapon',
        'hud.noHidden': 'No Ability',
        'hud.dodgeLimit': 'Dodge Lock',
        'hud.cKey': '🔄 C - ',
        'hud.switchTarget': 'Switch Target',
        'hud.qKey': '🚀 Q - ',
        'hud.eKey': '🚀 E - ',
        'hud.noLeftShoulder': 'No L-Shoulder',
        'hud.noRightShoulder': 'No R-Shoulder',
        'hud.ctrlKey': '🛠️ Ctrl - ',
        'hud.repairKit': 'Repair: {0}/{1}',
        'hud.repairEmpty': 'Repair: Empty',
        'hud.mode': 'Mode: {0}',
        'hud.bossKills': 'Boss Kills: {0}',

        'enemy.elite': 'Elite',

        'ui.paused': 'Game Paused',
        'ui.pauseHint': 'Press P to resume',
        'ui.pauseBtn': 'Pause',
        'ui.gameOver': 'Game Over',
        'ui.totalDamage': 'Total Damage: {0}',
        'ui.spaceReturn': 'Press SPACE to return to menu',
        'ui.victory': '🎉 Victory! 🎉',
        'ui.defeated': 'Defeated {0}!',
        'ui.finalScore': 'Final Score: {0}',
        'ui.blindStatus': 'SIGNAL JAMMED',
        'ui.blindRemaining': 'Time left: {0}s',
        'ui.langToggle': '中文',
        'ui.gameTitle': 'Mech Combat',

        'boss.CRIMSON_KING': 'Crimson King',
        'boss.SUBLIME_MOON': 'Sublime Moon',
        'boss.STAR_DEVOURER': 'Star Devourer',
        'boss.UGLY_EMPEROR': 'Ugly Emperor',
        'boss.MAGNUS_EXEC': 'Magnus, Mech Executive',
        'boss.HIVE_MIND': 'Hive Mind',
        'boss.YUKIKON': 'Yukikon, the Silent Edge',
        'boss.PROTEUS': 'Proteus, the Shapeshifter',
        'boss.TRIUMVIRATE': 'Elemental Triumvirate',
        'boss.unknown': 'Unknown Boss',
        'bossDesc.CRIMSON_KING': 'Crimson lord of terror, wielding the power of darkness',
        'bossDesc.SUBLIME_MOON': 'Cerulean mystic ruler, radiating icy moonlight power',
        'bossDesc.STAR_DEVOURER': 'Monochrome void destroyer, devouring all light and dark',
        'bossDesc.UGLY_EMPEROR': 'Twisted chaotic emperor, master of distortion and chaos',
        'bossDesc.MAGNUS_EXEC': 'Heavy mech executive — twin shoulder turrets, long-range suppression and orbital bombardment',
        'bossDesc.HIVE_MIND': 'Queen consciousness shielded by drone swarm — fragile core, hard to reach. Splits into four splinters on death',
        'bossDesc.YUKIKON': 'High-mobility melee duelist — blink, dash, sword rain and shadow clones to keep the pressure on. No bullet dodge.',
        'bossDesc.PROTEUS': 'Reconfigures between halberd melee, skirmish shotgun and stationary turret form based on player distance — vulnerable while reshaping.',

        'boss.pierce': 'Pierce!',
        'boss.blind': 'Blind',
        'boss.immune': 'Immune',
        'boss.clone': 'Clone',
        'boss.burn': 'Burning',

        'boss.blindActive': 'Blindness Active {0}s',
        'boss.blindUnlockNeed': 'Blind unlock: {0} DMG needed',
        'boss.blindUnlocked': 'Blind skill unlocked',
        'boss.blindCooldown': 'Blind CD {0}s {1}',
        'boss.blindReady': 'Blind skill ready {0}',
        'boss.phase1': '(Phase 1)',
        'boss.phase2label': '(Phase 2)',
        'boss.phase2Visible': 'Phase 2 - Range {0}/{1} - Visible',
        'boss.phase2Cloaked': 'Phase 2 - Range {0}/{1} - Cloaked',
        'boss.phase2Trigger': 'Phase 2 trigger: {0} DMG needed',

        'mode.BOSS_BATTLE': 'Boss Battle',
        'modeDesc.BOSS_BATTLE': 'Challenge powerful bosses',
        'mode.TRAINING': 'Training Ground',
        'modeDesc.TRAINING': 'Passive practice dummies | auto-respawn',
        'mech.HYBRID': 'Hybrid Mech',

        'weapon.gun': 'Auto Rifle',
        'weapon.sword': 'Beam Saber',
        'weapon.laser_spear': 'Laser Spear',
        'weapon.cluster_missile': 'Cluster Missile',
        'weapon.laser_rifle': 'Laser Rifle',
        'weapon.laser_smg': 'Laser SMG',
        'weapon.shotgun': 'Shotgun',
        'weapon.rocket_launcher': 'Rocket Launcher',
        'weapon.minigun': 'Minigun',
        'weapon.flamethrower': 'Flamethrower',
        'weapon.missile_launcher': 'Missile Launcher ×15',
        'weapon.high_track_missile': 'High-Track Missile',
        'weapon.cluster_bomb_missile': 'Cluster Bomblet Missile',
        'weapon.mine_layer_missile': 'Mine-Layer Missile',
        'weapon.det_cord_missile': 'Det-Cord Missile',
        'weapon.laser_turret': 'Laser Turret',
        'weapon.ciws': 'CIWS',
        'weapon.plasma_missile': 'Plasma Missile ×6',
        'weapon.super_weapon': 'Super Missile',
        'weapon.moonlight_greatsword': 'Moonlight Greatsword',
        'weapon.pulse_shield': 'Pulse Shield',
        'weapon.emp': 'EMP',
        'weapon.counter_mech': 'Counter Strike',
        'weapon.decoy_clone': 'Decoy Clone',
        'weapon.overdrive_burst': 'Overdrive Burst',
        'weapon.repair_protocol': 'Repair Protocol',
        'weapon.god_mode': 'God Mode',

        'weaponDesc.gun': 'Ranged | High ROF | Predictive Aim',
        'weaponDesc.sword': 'Melee | High DMG | Dash Attack',
        'weaponDesc.laser_spear': 'Mid-range Thrust | Charge | Rush',
        'weaponDesc.cluster_missile': 'Proximity Split ×8 | Tracking | Homing',
        'weaponDesc.laser_rifle': 'Hold to Charge | Aim Beam | Overheat',
        'weaponDesc.laser_smg': 'Rapid laser bursts | Snap-fire | Low DMG/heat per shot | Sustained fire overheats',
        'weaponDesc.shotgun': 'Cone Spread | 8 Pellets | Short-range Burst',
        'weaponDesc.rocket_launcher': 'AoE Rocket | Strong Center, Weak Rim | Single-shot',
        'weaponDesc.minigun': '200-round belt | 2× Rifle DMG up close | Falloff to 30% at max range | 45s reload',
        'weaponDesc.flamethrower': 'Sustained 30° flame cone | Range 240 | Damage falloff with distance | Heat-limited',
        'weaponDesc.missile_launcher': '1.1s Homing | AoE Blast | High DMG',
        'weaponDesc.high_track_missile': 'Single Shot | Hyper-Homing | 5x DMG | Slow',
        'weaponDesc.cluster_bomb_missile': 'Drops 10 bomblets midair | L30°/R45° fan | Invulnerable while dispersing',
        'weaponDesc.mine_layer_missile': 'Drops a HE mine every 0.7s along its path | Interceptable',
        'weaponDesc.det_cord_missile': 'Trails a det-cord | Detonation chains AoEs along path | 2/3 warhead DMG per node',
        'weaponDesc.laser_turret': 'Deploys a laser turret in place | Auto-fires within 600 range for 12s | 2-shot magazine',
        'weaponDesc.ciws': 'Auto-intercept | 30 Rounds | Missile Priority',
        'weaponDesc.plasma_missile': 'Proximity Fuse | Plasma DoT | Stackable',
        'weaponDesc.super_weapon': '100 DMG | Single Use | Dual Slot',
        'weaponDesc.moonlight_greatsword': '200 DMG | Massive Beam | 4 Slots | Single Use',
        'weaponDesc.pulse_shield': 'Full Immunity | 14.4s Duration | 40s CD',
        'weaponDesc.emp': 'AoE + Stun | Damage Falloff | 18s CD',
        'weaponDesc.counter_mech': '3s -40% DMG | 250% Reflect | 15s CD',
        'weaponDesc.decoy_clone': '3 Decoys | 4s Stealth | 35s CD',
        'weaponDesc.overdrive_burst': '6s Burst | DMG×3 SPD×3 | -30% HP, Incoming×2 | 30s CD',
        'weaponDesc.repair_protocol': '5s Repair | SPD×1.5, +5 HP/s | No attacking | Spill into +50 shield | 35s CD',
        'weaponDesc.god_mode': '[Debug] Insta-kills everything on activation | No CD, no VFX',

        'ws.attacking': 'Attacking...',
        'ws.stagger': 'Stagger: {0}s',
        'ws.dashPush': 'Dash Push...',
        'ws.cooldown': 'Cooldown: {0}s',
        'ws.cooldownS': 'CD: {0}s',
        'ws.ready': 'Ready',
        'ws.readyShort': 'Ready',
        'ws.reloading': 'Reload {0}s',
        'ws.ammoEmpty': 'Empty! Auto-reload',
        'ws.ammo': 'Ammo: {0}/{1}',
        'ws.overheat': 'Overheat! {0}s',
        'ws.charging': 'Charging {0}%',
        'ws.coolingDown': 'Cooling...',
        'ws.heat': 'Heat: {0}/{1}',
        'ws.rushing': 'Rushing!',
        'ws.recovering': 'Recovering',
        'ws.launching': 'Launching... ({0} left)',
        'ws.launchingSimple': 'Launching...',
        'ws.shielding': 'Shield: {0}s',
        'ws.countering': 'Counter: {0}s',
        'ws.stealth': 'Stealth: {0}s',
        'ws.overdriveActive': 'Overdrive: {0}s',
        'ws.repairActive': 'Repairing: {0}s',
        'ws.slashing': 'Slashing...',
        'ws.used': 'Used',
        'ws.cooldownRemaining': 'Cooldown {0}s',

        'player.dodging': 'Dodging...',
        'player.dodgeCooldown': 'Dodge CD: {0}s',
        'player.dodgeReady': 'Dodge Ready',
        'player.softLock': 'Soft Lock',
        'player.hardLock': 'Hard Lock',
        'player.manualLock': 'Manual',
    }
};

const guideData = {
    zh: [
        {
            id: 'controls', name: '操作说明', color: '#4488FF',
            content: [
                '【移动】 WASD / 方向键',
                '【左手武器】 鼠标左键',
                '【右手武器】 鼠标右键',
                '【左肩武器】 Q键',
                '【右肩武器】 E键',
                '【隐藏机能】 Shift键',
                '【闪避】 空格 + 方向键（0.15秒，冷却0.35秒）',
                '【切换锁定】 F键（软锁→硬锁→手动锁）',
                '【切换目标】 C键（硬锁模式下）',
                '【维修包】 Ctrl键（+60HP，共3个）',
                '【暂停】 P键',
                '【返回主菜单】 ESC键',
                '',
                '— 锁定系统 —',
                '软锁：自动瞄准最近敌人',
                '硬锁：锁定当前目标不放，C键切换',
                '手动锁：鼠标控制瞄准方向',
            ]
        },
        {
            id: 'hand_weapons', name: '手部武器', color: '#4169E1',
            items: [
                { name: '自动步枪', color: '#4169E1', lines: [
                    '伤害 6/发 | 射速 5发/秒',
                    '弹匣 30发 | 重装 2秒',
                    '自动预瞄：根据目标速度预判落点',
                ]},
                { name: '脉冲光束军刀', color: '#ff6b6b', lines: [
                    '伤害 50 | 120°扇形范围',
                    '冷却 4.8秒',
                    '刀推：距目标过远时自动冲刺接近',
                ]},
                { name: '镭射长枪', color: '#00FFFF', lines: [
                    '伤害 25 | 冲锋距离 400像素',
                    '冲锋速度 40 | 冷却 5秒',
                    '可扎穿敌人并带其一起移动',
                ]},
                { name: '镭射步枪', color: '#FF4444', lines: [
                    '伤害 18 | 蓄力 1秒后发射',
                    '射击间隔 0.7秒 | 射程无限',
                    '过热系统：每发+50热量，≥200过热',
                    '过热后强制散热7秒',
                ]},
                { name: '分裂飞弹', color: '#FFD700', lines: [
                    '发射1枚母弹，持续索敌（8秒无目标自爆）',
                    '接近敌人120px分裂为8枚子弹',
                    '子弹伤害 4 | 高追踪性 | 冷却 4秒',
                    '分裂后先扇形散开再制导',
                ]},
                { name: '霰弹枪', color: '#ff9040', lines: [
                    '伤害 8/弹 × 12颗弹丸 | 锥形扩散22°',
                    '伤害随距离线性衰减 | 满射程时降至20%',
                    '射程 700px | 射击间隔 0.7秒',
                    '弹匣 6发 | 重装 1.6秒',
                    '近距离贴脸输出爆炸',
                ]},
                { name: '火箭筒', color: '#ff7030', lines: [
                    '伤害 30 | 爆炸半径 180px | 中心强 边缘5%',
                    '伤害随距离平方衰减 | 射程 900px',
                    '射击间隔 1.1秒 | 单发膛 | 重装 2.6秒',
                    '高爆AOE，正中目标威力极高',
                ]},
            ]
        },
        {
            id: 'shoulder_weapons', name: '肩部武器', color: '#FF8800',
            items: [
                { name: '15连导弹发射器', color: '#FFD700', lines: [
                    '每次齐射 15枚 | 每枚 5伤害',
                    '前1.1秒强追踪 | 爆炸半径 80px',
                    '冷却 4秒',
                ]},
                { name: '近防炮 (CIWS)', color: '#00FF88', lines: [
                    '全自动射击 30发/秒 | 弹仓 30发',
                    '优先级：导弹 > 月牙弹 > 策反弹 > 机雷 > 敌人',
                    '对制导武器一发摧毁',
                    '对敌人本体 40%概率造成伤害',
                ]},
                { name: '6连电浆飞弹', color: '#00FFCC', lines: [
                    '6枚连射 | 近炸引信（55px引爆）',
                    '生成电浆场：持续1秒，每0.25秒造成3伤害',
                    '多个电浆场可叠加 | 冷却 5秒',
                ]},
                { name: '超级导弹', color: '#FF0000', lines: [
                    '伤害 100 | 占用左右肩双槽位',
                    '爆炸半径 400px | 超强追踪 4.1秒',
                    '每场战斗限用1次',
                ]},
                { name: '月光大剑', color: '#88CCFF', lines: [
                    '伤害 200 | 占用右手+双肩+隐藏机能共4槽位',
                    '光刃长度为光束军刀的7倍（1050px）',
                    '机体朝向±90°共180°范围 | 1秒完成扫击',
                    '无法秒杀Boss（最低保留1HP）',
                    '每场战斗限用1次',
                ]},
            ]
        },
        {
            id: 'hidden', name: '隐藏机能', color: '#00FFFF',
            items: [
                { name: '脉冲护盾', color: '#00FFFF', lines: [
                    '70%伤害减免 | 持续 18秒',
                    '冷却 40秒',
                ]},
                { name: 'EMP电磁脉冲', color: '#66CCFF', lines: [
                    '范围 490px | 最大伤害 100',
                    '距离越远伤害越低 | 附加2秒僵直',
                    '冷却 18秒',
                ]},
                { name: '反制重击', color: '#FF8C00', lines: [
                    '持续 3秒 | 受伤减少 40%',
                    '将受到伤害的250%反射给最近敌人',
                    '冷却 15秒',
                ]},
                { name: '诱饵分身', color: '#4488FF', lines: [
                    '释放 3 个全息诱饵（等边三角形散开）',
                    '诱饵 40HP | 最多存活 7秒',
                    '玩家进入 4秒不可锁定状态',
                    '敌方AI/导弹/子弹转向攻击诱饵',
                    '冷却 35秒',
                ]},
                { name: '超限爆发', color: '#FF2030', lines: [
                    '激活时立即损失30%当前血量',
                    '持续 6秒：伤害 ×3 | 移速 ×3',
                    '机身变红 | 冲刺时留下残影',
                    '代价：受到的伤害放大至 ×2',
                    '冷却 30秒',
                ]},
                { name: '应急修复', color: '#60FF90', lines: [
                    '激活时清空旧的溢出护盾',
                    '持续 5秒：移速 ×1.5 | 每秒恢复 5HP',
                    '期间无法使用任何武器和闪避',
                    '满血后溢出 HP 转为护盾，最多 +50',
                    '冷却 35秒',
                ]},
            ]
        },
        {
            id: 'bosses', name: 'Boss图鉴', color: '#FF4444',
            items: [
                { name: '血红之王', color: '#8B0000', lines: [
                    'HP 300 | 导弹洗地型',
                    '',
                    '— 攻击方式 —',
                    '齐射(salvo)：60枚普通导弹四方向轮流，每枚6伤害',
                    '追踪(homing)：6枚琥珀色强追踪导弹，每枚12伤害（1600px制导）',
                    '电浆方阵(square)：4边各3枚大型电浆球追踪玩家，命中后留电浆场',
                    '网格光束：4纵+3横激光网，强制走位至空格',
                    '',
                    '— 特殊机制 —',
                    '累积减伤：1秒内受伤越多减伤越高（不归零）',
                    '导弹闪避：被追踪时80%闪避',
                    '回血：每3秒 45%概率恢复6-20HP',
                    '',
                    '— 建议 —',
                    '近防炮拦截导弹，配合近战输出',
                    '避免短时间集中火力触发高减伤',
                ]},
                { name: '冰之姬', color: '#4682B4', lines: [
                    'HP 200 | 高机动刺客型',
                    '',
                    '— 攻击方式 —',
                    '月牙追踪弹：多种发射模式（齐射/扇形/螺旋）',
                    '回旋斩：玩家靠近时主动释放，附带减速debuff',
                    '导弹拦截：导弹接近时用回旋斩打爆来袭导弹',
                    '冰冻分身：召唤分身，间歇性发射追踪寒冰弹',
                    '',
                    '— 特殊机制 —',
                    '高频瞬移：偏好瞬移而非走位，瞬移到玩家背后',
                    '镭射步枪抗性：受到镭射步枪伤害降低 80%',
                    '极高导弹闪避：90%概率闪避制导武器',
                    '',
                    '— 建议 —',
                    '近防炮拦截月牙弹与寒冰弹',
                    '勿过度依赖镭射步枪 / 制导武器',
                    '保持中近距离，利用霰弹/火箭筒爆发',
                ]},
                { name: '噬星者', color: '#333333', lines: [
                    'HP 300 | 战术压制型',
                    '',
                    '— 攻击方式 —',
                    '光束步枪：25伤害+0.7秒僵直',
                    '自动步枪：近距离6伤害/发，30发/秒',
                    '浮游炮×3：各70HP，镭射15伤害+僵直',
                    '',
                    '— 特殊机制 —',
                    '信号干扰：屏幕被强烈雪花噪点覆盖，无法切换锁定',
                    '二阶段(≤80HP)：隐身(200px内可见)',
                    '导弹反转：75%玩家导弹被策反攻击玩家',
                    '',
                    '— 建议 —',
                    '优先摧毁浮游炮，近防炮拦截策反导弹',
                    '信号干扰期间凭手感持续移动，二阶段需近距离作战',
                ]},
                { name: '丑皇', color: '#8B4513', lines: [
                    'HP 250 | 区域控制型',
                    '',
                    '— 攻击方式 —',
                    '混沌弹幕：8发/波，4伤害/发',
                    '扭曲光环：半径80px持续伤害场',
                    '机雷(一阶段)：引爆15伤害',
                    '燃烧瓶(二阶段)：产生燃烧区域',
                    '',
                    '— 特殊机制 —',
                    '一阶段：免疫导弹伤害',
                    '二阶段(≤100HP)：仅受导弹伤害，伤害×2',
                    '混沌传送：每8秒传送到玩家附近',
                    '',
                    '— 建议 —',
                    '一阶段用步枪/激光/近战，近防炮清机雷',
                    '二阶段全力导弹输出（伤害翻倍）',
                    '两阶段需完全不同的武器策略',
                ]},
                { name: '机甲执政官 Magnus', color: '#C68C2A', lines: [
                    'HP 600 | 重装压制型',
                    '',
                    '— 攻击方式 —',
                    '主炮齐射：高速实弹弹幕',
                    '轨道炮击：圈内画地为牢，AOE覆盖打击',
                    '肩载炮塔×2：80HP，独立索敌火力',
                    '蜉蝣炮台：脱离的肩载炮塔会发射追踪火箭弹（仅它们能发射火箭，本体不会）',
                    '',
                    '— 阈值护盾 —',
                    '盾值上限 50% 总血量',
                    '≤40 单体伤害：完全免伤（被盾全额吸收）',
                    '40~200 单体伤害：随伤害递增的非线性减伤',
                    '>200 单体伤害：100%打入本体，盾值损失×2',
                    '破盾后冷却 70秒重新生成（25%概率提前 1.2秒重启）',
                    '',
                    '— 建议 —',
                    '高单发武器（月光大剑/超级导弹）一击破盾',
                    '小数值连射会被护盾吃光，先破盾再输出',
                    '优先摧毁肩部炮塔，再压制本体',
                    '近防炮专门对付脱离的炮台火箭弹',
                ]},
                { name: '蜂巢意识', color: '#9C27B0', lines: [
                    'HP 320 (本体) | 多体协同型',
                    '',
                    '— 攻击方式 —',
                    '紫色等离子弹幕：高频齐射',
                    '无人机蜂群：上限50只，每0.5秒补充至4只',
                    '  · 防御型：拦截玩家攻击与制导武器',
                    '  · 攻击型：环绕女王突袭并射击玩家',
                    '无人机 10HP，被击落后立即触发补充',
                    '蜂群残识(二阶段)：4只 80HP 残识，紫色等离子狙击',
                    '残识各自可召唤上限12的小型蜂群（速度1/4）',
                    '',
                    '— 特殊机制 —',
                    '无人机不可被锁定，但会主动拦截一切攻击',
                    '本体长期不可触及，只在蜂群被压制时短暂暴露',
                    '残识形态：女王进入幽灵状态不可见也不可锁定',
                    '残识互相排斥，远离玩家，难以一波集中清除',
                    '',
                    '— 建议 —',
                    '霰弹/火箭/EMP 等 AOE 清扫无人机',
                    '抓住女王暴露窗口集中爆发',
                    '残识阶段优先处理对玩家威胁最大的那只',
                ]},
                { name: '剑舞者 雪魂 (Yukikon)', color: '#7fc8ff', lines: [
                    'HP 150 | 高速近战决斗者',
                    '',
                    '— 攻击方式 —',
                    '闪斩(flashStrike)：极短抬手的瞬移突进劈砍',
                    'SMG 突射(smgBurst)：中距离机枪扫射',
                    '剑雨(swordRain)：召唤多把剑插入地面后激发',
                    '影分身(shadowStep)：留下分身互相替换位置干扰锁定',
                    '居合冲锋(iaiCharge)：拉开 200~520px 距离的弧线居合',
                    '游走时持续 SMG 短点射，从不"安静"',
                    '',
                    '— 特殊机制 —',
                    '近战护盾：挥剑期间远程伤害减至 15%（剑/光刃/月牙不受影响）',
                    '自带近防炮拦截：高速拦截制导武器，无视距离',
                    '偏好瞬移而非走位，频繁变换战场距离',
                    '',
                    '— 建议 —',
                    '尽量用近战武器贴身换血，远程会被严重削弱',
                    '注意她抬手挥剑的瞬间，那几帧远程基本无效',
                    '影分身阶段不要乱锁，等真身露脸',
                ]},
                { name: '变形机甲 普罗忒斯 (Proteus)', color: '#a0ffc0', lines: [
                    'HP 360 | 形态切换型',
                    '',
                    '— 三种形态（按距离切换）—',
                    '长戟形态(近战 < 350px)：突刺 / 横扫 / 长程波动 (伤害已削减50%)',
                    '游骑形态(中距 350~600px)：霰弹爆破、闪现、自愈、EMP、偶发激光炮',
                    '炮台形态(远程 > 600px)：部署静态炮塔弧线射击 + 近防炮拦截制导武器',
                    '',
                    '— 重组(重要弱点)—',
                    '形态切换约 0.6秒，期间无法攻击且 +25% 受伤',
                    '强制让他换形态可以撕开伤害窗口',
                    '每 20秒会主动循环切换一次',
                    '',
                    '— 阈值护盾(炮台形态)—',
                    '盾值上限 32% 总血量，伤害 -80%',
                    '回复极慢(满盾约 333秒)，破盾后冷却 8秒重生',
                    '破盾时有 35% 概率仅 1.2秒后重新激活',
                    '若在护盾激活时被强制切换形态 → 原地释放大范围 AOE 冲击波',
                    '',
                    '— 建议 —',
                    '不停拉近 / 推远迫使他切换，重组瞬间集火',
                    '炮台形态破盾用大单发武器，低伤连射会被护盾吃光',
                    '别在护盾激活时贴脸逼他切换，会被反震',
                ]},
                { name: '元素三主神 + 虚空', color: '#c87cff', lines: [
                    '三本体各 HP 240 | 杀两个后第三个变身为虚空 HP 200',
                    '',
                    '— 火神 Pyron（中近距压制）—',
                    '热熔柱(Heat Lance)：原地长出柱形烈焰，多层粒子',
                    '火焰喷射(Flamethrower Sweep)：长程跟踪锥火（射程 630px）',
                    '',
                    '— 雷神 Volthar（远程吊放）—',
                    '磁吸闪电(Magnet Strike)：从本体身上发出，蜿蜒延伸寻找玩家',
                    '铁桩仪式(Iron Spike)：全图一次部署多根机甲铁桩，引来 AOE 落雷+长僵直',
                    '',
                    '— 冰神 Glacius（远程减速控制）—',
                    '寒冰导弹(Frost Bolt)：三连发追踪弹，0伤害但叠加重度减速',
                    '寒冰冲击(Frost Nova)：以自身为中心 AOE，命中即 1秒僵直，原地留减速冰场',
                    '',
                    '— 三本体共通 —',
                    '同时出场，独立血条，互相会自动错开避免扎堆',
                    '受击时会侧身闪避(reactive sidestep)',
                    '',
                    '— 虚空 Voidborn（杀两个后登场）—',
                    'HP 200 | 缓慢飘移不主动追玩家',
                    '虚空吞噬：吸收所有非近战攻击（半径 240px 内的远程弹药直接消失）',
                    '虚空传送：玩家在 160px 内停留 0.35秒立刻被传送到远角',
                    '黑洞炮：一次发射 3 颗黑洞弹，引爆后形成强力吸力场，可无限叠加',
                    '近战减伤 50%（剑/光刃/月光对它效果减半）',
                    '',
                    '— 建议 —',
                    '优先击杀冰神切断减速，再处理雷神规避地刺AOE',
                    '虚空阶段近战才是有效输出，但要小心被传送',
                    '黑洞炮多发叠加时几乎跑不掉，提前预走位',
                ]},
            ]
        },
        {
            id: 'status', name: '状态效果', color: '#AAAAAA',
            content: [
                '【僵直】 短暂无法移动和行动',
                '【燃烧】 持续5秒，每0.1秒受2伤害，移速-20%',
                '【减速】 冰之姬回旋斩附加，短时间大幅降低移速',
                '【信号干扰】 噬星者专属，屏幕雪花噪点覆盖，无法切换锁定',
                '',
                '— 玩家属性 —',
                '生命值：150',
                '移动速度：20',
                '维修包：3个，每个恢复60HP',
                '闪避：0.15秒，冷却0.35秒',
            ]
        },
    ],

    en: [
        {
            id: 'controls', name: 'Controls', color: '#4488FF',
            content: [
                '[Move] WASD / Arrow Keys',
                '[Left Hand] Left Mouse Button',
                '[Right Hand] Right Mouse Button',
                '[Left Shoulder] Q Key',
                '[Right Shoulder] E Key',
                '[Hidden Ability] Shift Key',
                '[Dodge] Space + Direction (0.15s, 0.35s CD)',
                '[Toggle Lock] F Key (Soft → Hard → Manual)',
                '[Switch Target] C Key (Hard Lock mode)',
                '[Repair Kit] Ctrl Key (+60HP, 3 total)',
                '[Pause] P Key',
                '[Return to Menu] ESC Key',
                '',
                '— Lock System —',
                'Soft Lock: Auto-aim nearest enemy',
                'Hard Lock: Stay locked on target, C to switch',
                'Manual Lock: Mouse controls aim direction',
            ]
        },
        {
            id: 'hand_weapons', name: 'Hand Weapons', color: '#4169E1',
            items: [
                { name: 'Auto Rifle', color: '#4169E1', lines: [
                    'Damage 6/shot | Fire Rate 5/sec',
                    'Magazine 30 | Reload 2s',
                    'Predictive Aim: leads target based on velocity',
                ]},
                { name: 'Beam Saber', color: '#ff6b6b', lines: [
                    'Damage 50 | 120° arc range',
                    'Cooldown 4.8s',
                    'Dash Push: auto-dash to distant targets',
                ]},
                { name: 'Laser Spear', color: '#00FFFF', lines: [
                    'Damage 25 | Charge distance 400px',
                    'Charge speed 40 | Cooldown 5s',
                    'Can impale enemies and carry them along',
                ]},
                { name: 'Laser Rifle', color: '#FF4444', lines: [
                    'Damage 18 | 1s charge before firing',
                    'Fire interval 0.7s | Infinite range',
                    'Overheat system: +50 heat/shot, ≥200 overheat',
                    'Forced 7s cooldown when overheated',
                ]},
                { name: 'Cluster Missile', color: '#FFD700', lines: [
                    'Fires 1 mother missile, continuous tracking (8s self-destruct)',
                    'Splits into 8 sub-missiles at 120px proximity',
                    'Sub-missile DMG 4 | High tracking | 4s CD',
                    'Fan spread after split, then guided',
                ]},
                { name: 'Shotgun', color: '#ff9040', lines: [
                    'DMG 8 × 12 pellets | 22° cone spread',
                    'Damage falls off with distance | 20% at max range',
                    'Range 700px | Fire interval 0.7s',
                    'Magazine 6 | Reload 1.6s',
                    'Devastating at point blank',
                ]},
                { name: 'Rocket Launcher', color: '#ff7030', lines: [
                    'DMG 30 | Blast radius 180px | Strong center, 5% edge',
                    'Quadratic falloff | Range 900px',
                    'Fire interval 1.1s | Single-shot tube | Reload 2.6s',
                    'Heavy AoE, devastating on direct hits',
                ]},
            ]
        },
        {
            id: 'shoulder_weapons', name: 'Shoulder Weapons', color: '#FF8800',
            items: [
                { name: 'Missile Launcher ×15', color: '#FFD700', lines: [
                    '15 missiles per salvo | 5 DMG each',
                    '1.1s strong homing | 80px blast radius',
                    'Cooldown 4s',
                ]},
                { name: 'CIWS', color: '#00FF88', lines: [
                    'Full-auto 30 rounds/sec | 30 round mag',
                    'Priority: Missiles > Crescents > Reversed > Mines > Enemies',
                    'One-shot kill on guided weapons',
                    '40% chance to hit enemy body',
                ]},
                { name: 'Plasma Missile ×6', color: '#00FFCC', lines: [
                    '6 rapid-fire | Proximity fuse (55px trigger)',
                    'Creates plasma field: 1s duration, 3 DMG per 0.25s',
                    'Multiple fields stack | Cooldown 5s',
                ]},
                { name: 'Super Missile', color: '#FF0000', lines: [
                    'Damage 100 | Occupies both shoulder slots',
                    '400px blast radius | 4.1s super homing',
                    'Single use per battle',
                ]},
                { name: 'Moonlight Greatsword', color: '#88CCFF', lines: [
                    'Damage 200 | Occupies R-Hand + Both Shoulders + Ability (4 slots)',
                    'Blade length 7× Beam Saber (1050px)',
                    '±90° sweep (180° total) | 1s sweep time',
                    'Cannot one-shot bosses (min 1 HP)',
                    'Single use per battle',
                ]},
            ]
        },
        {
            id: 'hidden', name: 'Hidden Abilities', color: '#00FFFF',
            items: [
                { name: 'Pulse Shield', color: '#00FFFF', lines: [
                    '70% damage reduction | 18s duration',
                    'Cooldown 40s',
                ]},
                { name: 'EMP', color: '#66CCFF', lines: [
                    'Range 490px | Max damage 100',
                    'Damage falls off with distance | 2s stagger',
                    'Cooldown 18s',
                ]},
                { name: 'Counter Strike', color: '#FF8C00', lines: [
                    '3s duration | 40% damage reduction',
                    'Reflects 250% of damage taken to nearest enemy',
                    'Cooldown 15s',
                ]},
                { name: 'Decoy Clone', color: '#4488FF', lines: [
                    'Deploys 3 holographic decoys (triangle formation)',
                    'Decoy 40HP | Max 7s lifetime',
                    'Player becomes untargetable for 4s',
                    'Enemy AI/missiles/bullets redirect to decoys',
                    'Cooldown 35s',
                ]},
                { name: 'Overdrive Burst', color: '#FF2030', lines: [
                    'On activation: lose 30% of current HP',
                    'For 6s: outgoing damage x3 | move speed x3',
                    'Mech turns crimson | leaves afterimage trail',
                    'Drawback: incoming damage amplified to x2',
                    'Cooldown 30s',
                ]},
                { name: 'Repair Protocol', color: '#60FF90', lines: [
                    'Resets banked overflow shield on activation',
                    'For 5s: move speed x1.5 | regen 5 HP/s',
                    'Cannot fire weapons or dodge while active',
                    'Surplus regen converts to overflow shield, up to +50',
                    'Cooldown 35s',
                ]},
            ]
        },
        {
            id: 'bosses', name: 'Boss Guide', color: '#FF4444',
            items: [
                { name: 'Crimson King', color: '#8B0000', lines: [
                    'HP 300 | Missile Barrage Type',
                    '',
                    '— Attacks —',
                    'Salvo: 60 standard missiles, 4-direction rotation, 6 DMG each',
                    'Homing: 6 amber-colored seekers, 12 DMG each (1600px guidance)',
                    'Plasma Square: 3 large plasma orbs from each of 4 sides — leave hostile plasma fields on hit',
                    'Grid Barrage: 4 vertical + 3 horizontal beams, weave through gaps',
                    '',
                    '— Special Mechanics —',
                    'Cumulative DR: more hits in 1s = higher reduction',
                    'Missile dodge: 80% evasion when tracked',
                    'Regen: 45% chance to heal 6-20 HP every 3s',
                    '',
                    '— Tips —',
                    'CIWS to intercept missiles, combine with melee',
                    'Avoid burst damage to prevent high DR',
                ]},
                { name: 'Sublime Moon', color: '#4682B4', lines: [
                    'HP 200 | High-Mobility Assassin Type',
                    '',
                    '— Attacks —',
                    'Crescent tracking shots: multiple firing patterns (volley/fan/spiral)',
                    'Spin slash: triggered when player gets close, applies a slow debuff',
                    'Missile guard: detonates incoming missiles with spin slash',
                    'Frost clones: summons clones that periodically fire homing ice shots',
                    '',
                    '— Special Mechanics —',
                    'Frequent teleport: prefers blinks over walking, often appears behind you',
                    'Laser Rifle resistance: takes 80% reduced damage from Laser Rifle',
                    'Extreme missile evasion: 90% dodge chance vs guided weapons',
                    '',
                    '— Tips —',
                    'CIWS to intercept crescents and ice shots',
                    'Avoid relying on Laser Rifle / homing missiles',
                    'Stay mid-close range, burst with Shotgun / Rocket Launcher',
                ]},
                { name: 'Star Devourer', color: '#333333', lines: [
                    'HP 300 | Tactical Suppression Type',
                    '',
                    '— Attacks —',
                    'Beam rifle: 25 DMG + 0.7s stagger',
                    'Auto rifle: close range 6 DMG/shot, 30 rps',
                    'Floating guns ×3: 70 HP each, 15 DMG laser + stagger',
                    '',
                    '— Special Mechanics —',
                    'Signal jamming: heavy static noise overlays the screen, cannot switch lock',
                    'Phase 2 (≤80 HP): cloaked (visible within 200px)',
                    'Missile reversal: 75% of player missiles turned against you',
                    '',
                    '— Tips —',
                    'Destroy floating guns first; CIWS intercepts reversed missiles',
                    'Keep moving while jammed; Phase 2 requires close combat',
                ]},
                { name: 'Ugly Emperor', color: '#8B4513', lines: [
                    'HP 250 | Area Control Type',
                    '',
                    '— Attacks —',
                    'Chaos barrage: 8/wave, 4 DMG each',
                    'Distortion aura: 80px radius persistent damage field',
                    'Mines (Phase 1): 15 DMG on detonation',
                    'Molotov (Phase 2): creates burning area',
                    '',
                    '— Special Mechanics —',
                    'Phase 1: Immune to missile damage',
                    'Phase 2 (≤100 HP): Only takes missile DMG, ×2 multiplier',
                    'Chaos teleport: teleports near player every 8s',
                    '',
                    '— Tips —',
                    'Phase 1: use rifle/laser/melee; CIWS clears mines',
                    'Phase 2: full missile assault (double damage)',
                    'Two phases require completely different weapon strategies',
                ]},
                { name: 'Magnus, Mech Executive', color: '#C68C2A', lines: [
                    'HP 600 | Heavy Suppression Type',
                    '',
                    '— Attacks —',
                    'Main cannon barrage: high-velocity solid shells',
                    'Orbital bombardment: telegraphed AoE strikes that lock down zones',
                    'Shoulder turrets ×2: 80 HP each, independent targeting',
                    'Detached pods fire homing rockets — only the pods, not the body',
                    '',
                    '— Threshold Shield —',
                    'Shield pool: 50% of total HP',
                    '≤40 single hit: fully absorbed, 0 hull damage',
                    '40~200 single hit: nonlinear partial reduction (more = less reduction)',
                    '>200 single hit: 100% hull damage, shield loses 2× the hit',
                    'After break: 70s respawn cooldown (25% chance to early-rebuild in 1.2s)',
                    '',
                    '— Tips —',
                    'High-burst weapons (Moonlight Greatsword / Super Missile) crack the shield',
                    'Small chip damage is eaten by the shield — break it before pouring DPS',
                    'Take down shoulder turrets first, then push the body',
                    'Use CIWS to pop the rockets fired by detached pods',
                ]},
                { name: 'Hive Mind', color: '#9C27B0', lines: [
                    'HP 320 (Queen) | Multi-body Coordination Type',
                    '',
                    '— Attacks —',
                    'Purple plasma barrage: high-frequency volleys',
                    'Drone swarm: up to 50 units, +4 every 0.5s',
                    '  · Defenders: intercept player attacks and guided weapons',
                    '  · Attackers: orbit & strafe the player with plasma fire',
                    'Drones have 10 HP and are replaced almost immediately',
                    'Splinters (Phase 2): 4× 80 HP shards, plasma sniper shots',
                    'Each splinter spawns its own mini-swarm (cap 12, 1/4 rate)',
                    '',
                    '— Special Mechanics —',
                    'Drones cannot be hard-locked but actively block all incoming attacks',
                    'Queen is mostly untouchable; only briefly exposed when swarm is suppressed',
                    'Splinter phase: queen enters ghost mode (invisible & untargetable)',
                    'Splinters repel each other and flee from the player — hard to clean up at once',
                    '',
                    '— Tips —',
                    'AoE weapons (Shotgun / Rocket / EMP) thin the swarm fast',
                    'Burst the queen during her exposed window',
                    'In splinter phase, focus the splinter that pressures you the most',
                ]},
                { name: 'Yukikon, the Silent Edge', color: '#7fc8ff', lines: [
                    'HP 150 | High-Mobility Melee Duelist',
                    '',
                    '— Attacks —',
                    'Flash Strike: blink-in slash with minimal wind-up',
                    'SMG Burst: mid-range autofire',
                    'Sword Rain: plants several swords that detonate as projectiles',
                    'Shadow Step: leaves shadow clones, swaps places with them',
                    'Iai Charge: curving long-range dash slash (200~520px)',
                    'Always taps SMG rounds while orbiting — never silent',
                    '',
                    '— Special Mechanics —',
                    'Melee Shield: ranged damage reduced to 15% while she\'s mid-swing',
                    '  (Sword / Moonlight / Crescent / Spear bypass it)',
                    'Built-in CIWS: shreds incoming missiles at any range',
                    'Prefers blinks to walking; constantly resets engagement distance',
                    '',
                    '— Tips —',
                    'Trade up close — ranged weapons get gutted by the melee shield',
                    'Watch for her swing windows; that\'s when ranged fizzles',
                    'During shadow phase, wait for the real one to reveal before locking',
                ]},
                { name: 'Proteus, the Shapeshifter', color: '#a0ffc0', lines: [
                    'HP 360 | Adaptive Shapeshifter',
                    '',
                    '— Three Forms (distance-based) —',
                    'Halberd (close < 350px): thrusts / sweeps / long wave (damage halved)',
                    'Skirmish (mid 350~600px): shotgun blasts, blink, self-heal, EMP, occasional cannon',
                    'Turret (far > 600px): static cannons, arc-fire, CIWS-style point defense',
                    '',
                    '— Reconfigure Window (KEY WEAKNESS) —',
                    'Form swap takes ~0.6s — cannot attack and takes +25% damage',
                    'Force form swaps with positioning to open damage windows',
                    'Auto-cycles forms every 20s anyway',
                    '',
                    '— Threshold Shield (Turret form) —',
                    'Shield pool: 32% of total HP, -80% damage absorbed',
                    'Regen extremely slow (~333s for full), 8s respawn cooldown after break',
                    '35% chance the shield rebuilds 1.2s after being broken',
                    'Forcing a form swap WHILE shield is up triggers a huge AoE shockwave',
                    '',
                    '— Tips —',
                    'Push or kite to force form swaps — burst him during reconfigure',
                    'Crack the turret-form shield with high single-hit weapons',
                    'Don\'t poke into melee while his shield is up — you\'ll eat the shockwave',
                ]},
                { name: 'Elemental Triumvirate + Voidborn', color: '#c87cff', lines: [
                    'Three bodies × HP 240 | Kill any 2 → the last becomes Voidborn (HP 200)',
                    '',
                    '— Pyron, the Fire God (close-mid pressure) —',
                    'Heat Lance: stationary multi-layer pillar of flame',
                    'Flamethrower Sweep: long-range tracking cone (range 630px)',
                    '',
                    '— Volthar, the Lightning God (long-range zoner) —',
                    'Magnet Strike: lightning crawls out of his body, snakes toward player',
                    'Iron Spike Ritual: drops multiple mecha-tech pylons across the arena',
                    '  → AoE chained lightning strikes + long stun',
                    '',
                    '— Glacius, the Ice God (long-range slow control) —',
                    'Frost Bolt: triple-shot homing missile, 0 damage but heavy slow',
                    'Frost Nova: self-centered AoE, 1s stagger on hit, leaves slow ice field',
                    '',
                    '— All three —',
                    'Spawn together with independent HP bars',
                    'Auto-spread so they don\'t pile up; reactive sidestep on hit',
                    '',
                    '— Voidborn (after any 2 die) —',
                    'HP 200 | Drifts slowly, doesn\'t actively chase',
                    'Void Devour: ALL ranged projectiles within 240px just disappear',
                    'Void Teleport: stay within 160px for 0.35s and you get yeeted to a far corner',
                    'Blackhole Cannon: salvo of 3 blackhole shots, pulls stack — escape gets harder fast',
                    'Melee resistance: takes 50% reduced damage from Sword / Moonlight',
                    '',
                    '— Tips —',
                    'Kill Glacius first to drop the slows, then Volthar for the spike AoE',
                    'In Voidborn phase melee is the only effective DPS — but don\'t linger',
                    'When multiple blackholes overlap, escape is nearly impossible — pre-empt them',
                ]},
            ]
        },
        {
            id: 'status', name: 'Status Effects', color: '#AAAAAA',
            content: [
                '[Stagger] Briefly unable to move or act',
                '[Burning] 5s duration, 2 DMG per 0.1s, -20% move speed',
                '[Slow] Applied by Sublime Moon spin slash, briefly halves move speed',
                '[Signal Jammed] Star Devourer exclusive: heavy static overlay, cannot switch lock',
                '',
                '— Player Stats —',
                'Health: 150',
                'Move Speed: 20',
                'Repair Kits: 3, each restores 60 HP',
                'Dodge: 0.15s, cooldown 0.35s',
            ]
        },
    ]
};
