function t(key, ...args) {
    const lang = (typeof gameState !== 'undefined' && gameState.language) || 'zh';
    const str = translations[lang] && translations[lang][key];
    if (str === undefined) return key;
    if (args.length === 0) return str;
    return str.replace(/\{(\d+)\}/g, (match, index) => {
        const i = parseInt(index);
        return i < args.length ? args[i] : match;
    });
}

function getLocalizedGuideData() {
    const lang = (typeof gameState !== 'undefined' && gameState.language) || 'zh';
    return guideData[lang] || guideData.zh;
}

const translations = {
    zh: {
        'menu.startBoss': '开始 Boss 战',
        'menu.startBossDesc': '挑战强大的Boss敌人',
        'menu.startTutorial': '新手教程',
        'menu.startTutorialDesc': '快速掌握行动、火力与锁定系统',
        'menu.startTraining': '进入训练场',
        'menu.startTrainingDesc': '在不会反击的假人上练习武器',
        'menu.customizeMech': '定制机甲',
        'menu.customizeDesc': '配置武器装备，自定义作战风格',
        'menu.guide': '游戏简介',
        'menu.settings': '设置',
        'menu.settingsDesc': '机甲命名等个人偏好',
        'settings.title': '设置',
        'settings.subtitle': 'PERSONAL PREFERENCES',
        'settings.mechNameLabel': '机甲命名',
        'settings.mechNameHint': '为你的座驾起一个专属代号 (1–24 字符)',
        'settings.save': '保存',
        'settings.saved': '已保存',
        'settings.reset': '恢复默认',
        'settings.back': '返回',
        'settings.contactHeader': '// CONTACT — 联络作者',
        'settings.contactGreeting': '欢迎联系我！',
        'settings.contactBili': 'B 站：ガンダムさん',
        'settings.contactBiliUid': 'UID：3493134971439675',
        'menu.selectLevel': '选择关卡',
        'menu.bossModeSub': 'Boss战模式 - 挑战强大的敌人',
        'menu.difficulty': '难度: ',
        'menu.locked': '🔒 未解锁',
        'menu.back': '返回',
        'menu.backArrow': '← 返回',
        'menu.mainMenu': '主菜单',
        'menu.backToMenu': '返回主菜单',
        'menu.backToCatalog': '返回目录',
        'menu.backTo': '返回{0}',

        'cfg.selected': '已选择：{0}',
        'cfg.leftHand': '左手武器',
        'cfg.rightHand': '右手武器',
        'cfg.leftShoulder': '左肩武器',
        'cfg.rightShoulder': '右肩武器',
        'cfg.hiddenAbility': '隐藏机能',
        'cfg.leftKey': '(左键)',
        'cfg.rightKey': '(右键)',
        'cfg.qKey': '(Q键)',
        'cfg.eKey': '(E键)',
        'cfg.shiftKey': '(Shift键)',
        'cfg.none': '无',
        'cfg.currentConfig': '当前配置：',
        'cfg.invincibleOn': '无敌模式：开启',
        'cfg.invincibleOff': '无敌模式：关闭',
        'cfg.startGame': '开始游戏',
        'cfg.configHint': '点击武器槽位选择武器，然后点击开始游戏',
        'cfg.customHint': '点击武器槽位选择武器，然后返回主菜单',

        'hud.mech': '机甲: {0}',
        'hud.health': '❤️ 生命值: ',
        'hud.invincible': '⭐ 无敌模式 ⭐',
        'hud.leftKey': '🖊️ 左键 - ',
        'hud.rightKey': '🖐️ 右键 - ',
        'hud.dodgeKey': '⚡ 空格 - ',
        'hud.dodge': '闪避: {0}',
        'hud.lockKey': '🎯 F键 - ',
        'hud.lockMode': '锁定模式: {0}',
        'hud.shiftKey': '🛡️ Shift键 - ',
        'hud.noWeapon': '无武器',
        'hud.noHidden': '无隐藏机能',
        'hud.dodgeLimit': '闪避限制',
        'hud.cKey': '🔄 C键 - ',
        'hud.switchTarget': '切换目标',
        'hud.qKey': '🚀 Q键 - ',
        'hud.eKey': '🚀 E键 - ',
        'hud.noLeftShoulder': '无左肩武器',
        'hud.noRightShoulder': '无右肩武器',
        'hud.ctrlKey': '🛠️ Ctrl键 - ',
        'hud.repairKit': '维修包: {0}/{1}',
        'hud.repairEmpty': '维修包: 已用完',
        'hud.mode': '模式: {0}',
        'hud.bossKills': 'Boss击杀数: {0}',

        'enemy.elite': '精英',

        'ui.paused': '游戏暂停',
        'ui.pauseHint': '按 P 继续游戏',
        'ui.pauseBtn': '暂停',
        'ui.gameOver': '游戏结束',
        'ui.totalDamage': '造成总伤害: {0}',
        'ui.spaceReturn': '按空格键返回主菜单',
        'ui.victory': '🎉 胜利！🎉',
        'ui.defeated': '击败了 {0}！',
        'ui.finalScore': '最终分数: {0}',
        'ui.blindStatus': '信号干扰',
        'ui.blindRemaining': '剩余时间: {0}秒',
        'ui.langToggle': '日本語',
        'ui.gameTitle': '机甲战斗游戏',

        'boss.CRIMSON_KING': '血红之王',
        'boss.SUBLIME_MOON': '冰之姬',
        'boss.STAR_DEVOURER': '噬星者',
        'boss.UGLY_EMPEROR': '丑皇',
        'boss.MAGNUS_EXEC': '机甲执政官 Magnus',
        'boss.HIVE_MIND': '蜂巢意识',
        'boss.YUKIKON': '剑舞者 雪魂',
        'boss.PROTEUS': '变形机甲 普罗忒斯',
        'boss.TRIUMVIRATE': '元素三主神',
        'boss.unknown': '未知Boss',
        'bossDesc.CRIMSON_KING': '深红色的恐怖统治者，掌控着黑暗的力量',
        'bossDesc.SUBLIME_MOON': '青蓝色的神秘支配者，散发着冰冷的月光之力',
        'bossDesc.STAR_DEVOURER': '黑白相间的虚无毁灭者，吞噬一切光明与黑暗',
        'bossDesc.UGLY_EMPEROR': '丑陋扭曲的混沌统治者，掌控着扭曲与混乱的力量',
        'bossDesc.MAGNUS_EXEC': '重装机甲执政官，肩载双炮塔、远程压制与轨道炮击',
        'bossDesc.HIVE_MIND': '由蜂群守护的女王意识体，本体脆弱却难以触及，死亡后分裂为四道残识',
        'bossDesc.YUKIKON': '高速近战决斗者，凭瞬移、突袭与影分身贴身压制，不闪避子弹只用距离换速度',
        'bossDesc.PROTEUS': '依玩家距离实时切换近战长戟、霰弹机动、远程炮塔三种结构，重组瞬间脆弱可乘',

        'boss.pierce': '扎穿!',
        'boss.blind': '失明',
        'boss.immune': '免疫',
        'boss.clone': '分身',
        'boss.burn': '燃烧',

        'boss.blindActive': '失明激活中 {0}s',
        'boss.blindUnlockNeed': '失明技能解锁: 还需 {0} 伤害',
        'boss.blindUnlocked': '失明技能已解锁',
        'boss.blindCooldown': '失明冷却中 {0}s {1}',
        'boss.blindReady': '失明技能准备就绪 {0}',
        'boss.phase1': '(一阶段)',
        'boss.phase2label': '(二阶段)',
        'boss.phase2Visible': '二阶段 - 距离 {0}/{1} - 可见可锁定',
        'boss.phase2Cloaked': '二阶段 - 距离 {0}/{1} - 隐身状态',
        'boss.phase2Trigger': '二阶段触发: 还需 {0} 伤害',

        'mode.BOSS_BATTLE': 'Boss战模式',
        'modeDesc.BOSS_BATTLE': '挑战强大的Boss敌人',
        'mode.TRAINING': '训练场',
        'modeDesc.TRAINING': '不会反击的假人靶 | 死后立即补充',
        'mode.TUTORIAL': '新手教程',
        'modeDesc.TUTORIAL': '飞行员入门训练',
        'mech.HYBRID': '混合机甲',

        'weapon.gun': '自动步枪',
        'weapon.sword': '脉冲光束军刀',
        'weapon.laser_spear': '镭射长枪',
        'weapon.cluster_missile': '分裂飞弹',
        'weapon.laser_rifle': '镭射步枪',
        'weapon.laser_smg': '镭射机枪',
        'weapon.shotgun': '霰弹枪',
        'weapon.rocket_launcher': '火箭筒',
        'weapon.minigun': '加特林',
        'weapon.flamethrower': '火焰喷射器',
        'weapon.missile_launcher': '15连导弹发射器',
        'weapon.high_track_missile': '高诱导飞弹',
        'weapon.cluster_bomb_missile': '集束飞弹',
        'weapon.mine_layer_missile': '布雷飞弹',
        'weapon.det_cord_missile': '爆导索飞弹',
        'weapon.laser_turret': '镭射炮台',
        'weapon.ciws': '近防炮',
        'weapon.plasma_missile': '6连电浆飞弹',
        'weapon.super_weapon': '超级导弹',
        'weapon.moonlight_greatsword': '月光大剑',
        'weapon.pulse_shield': '脉冲振刀',
        'weapon.emp': 'EMP电磁脉冲',
        'weapon.counter_mech': '反制重击',
        'weapon.decoy_clone': '诱饵分身',
        'weapon.overdrive_burst': '超限爆发',
        'weapon.repair_protocol': '应急修复',
        'weapon.god_mode': '金手指',

        'weaponDesc.gun': '远程射击 | 高射速 | 预瞄功能',
        'weaponDesc.sword': '近战攻击 | 高伤害 | 刀推功能',
        'weaponDesc.laser_spear': '中距离突刺 | 蓄力攻击 | 推进功能',
        'weaponDesc.cluster_missile': '大弹近炸分裂8子弹 | 持续索敌 | 高追踪',
        'weaponDesc.laser_rifle': '长按蓄力 | 预瞄射线 | 过热系统',
        'weaponDesc.laser_smg': '速射镭射 | 出手快 | 单发低伤低热 | 持续输出会过热',
        'weaponDesc.shotgun': '近距锥形扩散 | 8颗弹丸 | 短射程高爆发',
        'weaponDesc.rocket_launcher': 'AOE火箭 | 中心强边缘弱 | 单发膛',
        'weaponDesc.minigun': '200发弹链 | 单发伤害2倍步枪(近距离) | 远距离衰减至30% | 装填45秒',
        'weaponDesc.flamethrower': '持续喷射 30° 火焰锥 | 射程 240 | 距离衰减 | 过热限制',
        'weaponDesc.missile_launcher': '强追踪1.1秒 | 范围爆炸 | 高伤害',
        'weaponDesc.high_track_missile': '单发 | 极高追踪 | 5倍伤害 | 慢速',
        'weaponDesc.cluster_bomb_missile': '空中投放10枚子弹 | L30°/R45°轮射 | 投放期间无敌',
        'weaponDesc.mine_layer_missile': '飞行中每0.7秒布置高爆机雷 | 可被拦截',
        'weaponDesc.det_cord_missile': '尾部拖出爆导索 | 引爆后沿索连环 AOE | 单点伤害2/3母弹',
        'weaponDesc.laser_turret': '在原地部署镭射炮台 | 12秒内自动射击600射程内敌人 | 弹仓2发',
        'weaponDesc.ciws': '自动拦截制导武器 | 30发弹仓 | 优先打导弹',
        'weaponDesc.plasma_missile': '近炸引信 | 电浆场持续伤害 | 可叠加',
        'weaponDesc.super_weapon': '100伤害 | 一次战斗只能用一次 | 占用双槽位',
        'weaponDesc.moonlight_greatsword': '200伤害 | 超大范围光刃 | 占用4槽位 | 一次性',
        'weaponDesc.pulse_shield': '0.2秒振刀窗口 | 全伤害类型反弹 | 1秒冷却',
        'weaponDesc.emp': '范围伤害+僵直 | 距离越远伤害越低 | 18秒冷却',
        'weaponDesc.counter_mech': '3秒减伤40% | 反射250%伤害 | 15秒冷却',
        'weaponDesc.decoy_clone': '释放3诱饵 | 4秒隐身 | 35秒冷却',
        'weaponDesc.overdrive_burst': '6秒爆发 | 伤害×3 移速×3 | 自损30%血 受伤×2 | 30秒冷却',
        'weaponDesc.repair_protocol': '5秒修复 | 移速×1.5 每秒回5血 | 期间无法攻击 | 满血溢出至+50护盾 | 35秒冷却',
        'weaponDesc.god_mode': '【调试用】释放即瞬杀场上一切 | 无冷却 无特效',

        'ws.attacking': '攻击中...',
        'ws.stagger': '僵直: {0}秒',
        'ws.dashPush': '刀推中...',
        'ws.cooldown': '冷却: {0}秒',
        'ws.cooldownS': '冷却: {0}s',
        'ws.ready': '准备就绪',
        'ws.readyShort': '就绪',
        'ws.reloading': '重装中 {0}s',
        'ws.ammoEmpty': '弹药耗尽！自动重装',
        'ws.ammo': '弹药: {0}/{1}',
        'ws.overheat': '过热! {0}s',
        'ws.charging': '蓄力中 {0}%',
        'ws.coolingDown': '冷却中...',
        'ws.heat': '热量: {0}/{1}',
        'ws.rushing': '冲锋中！',
        'ws.recovering': '恢复中',
        'ws.launching': '发射中... ({0}枚)',
        'ws.launchingSimple': '发射中...',
        'ws.shielding': '护盾中: {0}秒',
        'ws.parryReady': '振刀就绪',
        'ws.parryActive': '振刀!',
        'ws.countering': '反制中: {0}s',
        'ws.stealth': '隐身中: {0}s',
        'ws.overdriveActive': '超限爆发: {0}s',
        'ws.repairActive': '应急修复: {0}s',
        'ws.slashing': '斩击中...',
        'ws.used': '已使用',
        'ws.cooldownRemaining': '冷却中 {0}s',

        'player.dodging': '闪避中...',
        'player.dodgeCooldown': '闪避冷却: {0}秒',
        'player.dodgeReady': '闪避就绪',
        'player.softLock': '软锁',
        'player.hardLock': '硬锁',
        'player.manualLock': '手动锁',

        // ===== Tutorial =====
        'tut.ui.objective': '当前目标',
        'tut.ui.tutorialLabel': '新手教程',
        'tut.ui.continueBriefing': '按 [空格] 继续',
        'tut.ui.continueDebrief': '按 [空格] 继续',
        'tut.ui.skipTitle': '跳过新手教程？',
        'tut.ui.skipBody': '已学过的内容随时可以在游戏简介里复习。',
        'tut.ui.skipPrompt': '[Y/Enter] 跳过　　[N/ESC] 返回',
        'tut.intro.title': '欢迎，{0}',
        'tut.intro.body': '这是一段简短的实弹训练。\n训练期间你将处于无敌状态，可放心熟悉操作。\n按 [空格] 开始。\n（任何时候可按 ESC 跳过教程。）',
        'tut.step.move': 'W/A/S/D 移动，按 [空格] 朝移动方向闪避冲刺。\n依次走入三个光环（ALPHA / BRAVO / CHARLIE）。',
        'tut.step.leftHand': '只装备左手自动步枪——按下鼠标左键持续开火。\n清除场上所有训练假人。',
        'tut.step.rightHand': '只装备右手近战武器——按下鼠标右键挥砍。\n靠近并击破全部假人。',
        'tut.step.shoulder': '只装备左肩 15 连导弹发射器——按下 Q 齐射。\n用肩部武器清除全部 3 个目标。',
        'tut.step.emp': '隐藏机能：EMP 电磁脉冲（按下 Shift 触发）。\n靶子在范围内——释放 EMP 击中它们即可（不会一击秒杀，看清效果）。',
        'tut.step.dodge': '前方部署了一台镭射炮台，被命中会被电磁僵直。\n按下 [空格] 闪避 5 次，每次闪避前后 1 秒内不可被命中。',
        'tut.step.dodgeProgress': '成功闪避 {0} / {1}',
        'tut.step.lock': 'C 键循环锁定模式：软锁 / 硬锁 / 手动锁。\n在每种锁定模式下各击杀至少 1 个目标。',
        'tut.lock.soft':   '软锁',
        'tut.lock.hard':   '硬锁',
        'tut.lock.manual': '手动锁',
        'tut.boss.title': '实战模拟',
        'tut.boss.body': '最终考核——一台名为「SPARRING DRONE」的训练型对手。\n本关取消无敌；它的伤害很低，且你的血量不会低于 1 点。\n善用所学击败它。',
        'tut.step.boss': '击败 SPARRING DRONE（生命下限 1 点）。',
        'tut.outro.title': '训练完成',
        'tut.outro.body': '欢迎加入战场，{0}。\n更详细的资料可在游戏简介中查阅。\n按 [空格] 返回主菜单。',
    },

    en: {
        'menu.startBoss': 'Start Boss Battle',
        'menu.startBossDesc': 'Challenge powerful bosses',
        'menu.startTutorial': 'New Pilot Training',
        'menu.startTutorialDesc': 'Quick course on movement, fire & locking',
        'menu.startTraining': 'Enter Training Ground',
        'menu.startTrainingDesc': 'Practice weapons on passive dummies',
        'menu.customizeMech': 'Customize Mech',
        'menu.customizeDesc': 'Configure weapons & combat style',
        'menu.guide': 'Game Guide',
        'menu.settings': 'Settings',
        'menu.settingsDesc': 'Mech callsign and other preferences',
        'settings.title': 'SETTINGS',
        'settings.subtitle': 'PERSONAL PREFERENCES',
        'settings.mechNameLabel': 'Mech Callsign',
        'settings.mechNameHint': 'Name your personal mech (1–24 chars)',
        'settings.save': 'Save',
        'settings.saved': 'Saved',
        'settings.reset': 'Reset',
        'settings.back': 'Back',
        'settings.contactHeader': '// CONTACT — REACH OUT',
        'settings.contactGreeting': 'Feel free to get in touch!',
        'settings.contactBili': 'Bilibili: ガンダムさん',
        'settings.contactBiliUid': 'UID: 3493134971439675',
        'menu.selectLevel': 'Select Level',
        'menu.bossModeSub': 'Boss Battle - Challenge powerful bosses',
        'menu.difficulty': 'Difficulty: ',
        'menu.locked': '🔒 Locked',
        'menu.back': 'Back',
        'menu.backArrow': '← Back',
        'menu.mainMenu': 'Main Menu',
        'menu.backToMenu': 'Return to Menu',
        'menu.backToCatalog': 'Back to Catalog',
        'menu.backTo': 'Back to {0}',

        'cfg.selected': 'Selected: {0}',
        'cfg.leftHand': 'Left Hand',
        'cfg.rightHand': 'Right Hand',
        'cfg.leftShoulder': 'Left Shoulder',
        'cfg.rightShoulder': 'Right Shoulder',
        'cfg.hiddenAbility': 'Hidden Ability',
        'cfg.leftKey': '(LMB)',
        'cfg.rightKey': '(RMB)',
        'cfg.qKey': '(Q)',
        'cfg.eKey': '(E)',
        'cfg.shiftKey': '(Shift)',
        'cfg.none': 'None',
        'cfg.currentConfig': 'Current Config:',
        'cfg.invincibleOn': 'Invincible: ON',
        'cfg.invincibleOff': 'Invincible: OFF',
        'cfg.startGame': 'Start Game',
        'cfg.configHint': 'Click weapon slots to configure, then Start Game',
        'cfg.customHint': 'Click weapon slots to configure, then return to menu',

        'hud.mech': 'Mech: {0}',
        'hud.health': '❤️ HP: ',
        'hud.invincible': '⭐ Invincible ⭐',
        'hud.leftKey': '🖊️ LMB - ',
        'hud.rightKey': '🖐️ RMB - ',
        'hud.dodgeKey': '⚡ Space - ',
        'hud.dodge': 'Dodge: {0}',
        'hud.lockKey': '🎯 F - ',
        'hud.lockMode': 'Lock: {0}',
        'hud.shiftKey': '🛡️ Shift - ',
        'hud.noWeapon': 'No Weapon',
        'hud.noHidden': 'No Ability',
        'hud.dodgeLimit': 'Dodge Lock',
        'hud.cKey': '🔄 C - ',
        'hud.switchTarget': 'Switch Target',
        'hud.qKey': '🚀 Q - ',
        'hud.eKey': '🚀 E - ',
        'hud.noLeftShoulder': 'No L-Shoulder',
        'hud.noRightShoulder': 'No R-Shoulder',
        'hud.ctrlKey': '🛠️ Ctrl - ',
        'hud.repairKit': 'Repair: {0}/{1}',
        'hud.repairEmpty': 'Repair: Empty',
        'hud.mode': 'Mode: {0}',
        'hud.bossKills': 'Boss Kills: {0}',

        'enemy.elite': 'Elite',

        'ui.paused': 'Game Paused',
        'ui.pauseHint': 'Press P to resume',
        'ui.pauseBtn': 'Pause',
        'ui.gameOver': 'Game Over',
        'ui.totalDamage': 'Total Damage: {0}',
        'ui.spaceReturn': 'Press SPACE to return to menu',
        'ui.victory': '🎉 Victory! 🎉',
        'ui.defeated': 'Defeated {0}!',
        'ui.finalScore': 'Final Score: {0}',
        'ui.blindStatus': 'SIGNAL JAMMED',
        'ui.blindRemaining': 'Time left: {0}s',
        'ui.langToggle': '中文',
        'ui.gameTitle': 'Mech Combat',

        'boss.CRIMSON_KING': 'Crimson King',
        'boss.SUBLIME_MOON': 'Sublime Moon',
        'boss.STAR_DEVOURER': 'Star Devourer',
        'boss.UGLY_EMPEROR': 'Ugly Emperor',
        'boss.MAGNUS_EXEC': 'Magnus, Mech Executive',
        'boss.HIVE_MIND': 'Hive Mind',
        'boss.YUKIKON': 'Yukikon, the Silent Edge',
        'boss.PROTEUS': 'Proteus, the Shapeshifter',
        'boss.TRIUMVIRATE': 'Elemental Triumvirate',
        'boss.unknown': 'Unknown Boss',
        'bossDesc.CRIMSON_KING': 'Crimson lord of terror, wielding the power of darkness',
        'bossDesc.SUBLIME_MOON': 'Cerulean mystic ruler, radiating icy moonlight power',
        'bossDesc.STAR_DEVOURER': 'Monochrome void destroyer, devouring all light and dark',
        'bossDesc.UGLY_EMPEROR': 'Twisted chaotic emperor, master of distortion and chaos',
        'bossDesc.MAGNUS_EXEC': 'Heavy mech executive — twin shoulder turrets, long-range suppression and orbital bombardment',
        'bossDesc.HIVE_MIND': 'Queen consciousness shielded by drone swarm — fragile core, hard to reach. Splits into four splinters on death',
        'bossDesc.YUKIKON': 'High-mobility melee duelist — blink, dash, sword rain and shadow clones to keep the pressure on. No bullet dodge.',
        'bossDesc.PROTEUS': 'Reconfigures between halberd melee, skirmish shotgun and stationary turret form based on player distance — vulnerable while reshaping.',

        'boss.pierce': 'Pierce!',
        'boss.blind': 'Blind',
        'boss.immune': 'Immune',
        'boss.clone': 'Clone',
        'boss.burn': 'Burning',

        'boss.blindActive': 'Blindness Active {0}s',
        'boss.blindUnlockNeed': 'Blind unlock: {0} DMG needed',
        'boss.blindUnlocked': 'Blind skill unlocked',
        'boss.blindCooldown': 'Blind CD {0}s {1}',
        'boss.blindReady': 'Blind skill ready {0}',
        'boss.phase1': '(Phase 1)',
        'boss.phase2label': '(Phase 2)',
        'boss.phase2Visible': 'Phase 2 - Range {0}/{1} - Visible',
        'boss.phase2Cloaked': 'Phase 2 - Range {0}/{1} - Cloaked',
        'boss.phase2Trigger': 'Phase 2 trigger: {0} DMG needed',

        'mode.BOSS_BATTLE': 'Boss Battle',
        'modeDesc.BOSS_BATTLE': 'Challenge powerful bosses',
        'mode.TRAINING': 'Training Ground',
        'modeDesc.TRAINING': 'Passive practice dummies | auto-respawn',
        'mode.TUTORIAL': 'Tutorial',
        'modeDesc.TUTORIAL': 'New-pilot training',
        'mech.HYBRID': 'Hybrid Mech',

        'weapon.gun': 'Auto Rifle',
        'weapon.sword': 'Beam Saber',
        'weapon.laser_spear': 'Laser Spear',
        'weapon.cluster_missile': 'Cluster Missile',
        'weapon.laser_rifle': 'Laser Rifle',
        'weapon.laser_smg': 'Laser SMG',
        'weapon.shotgun': 'Shotgun',
        'weapon.rocket_launcher': 'Rocket Launcher',
        'weapon.minigun': 'Minigun',
        'weapon.flamethrower': 'Flamethrower',
        'weapon.missile_launcher': 'Missile Launcher ×15',
        'weapon.high_track_missile': 'High-Track Missile',
        'weapon.cluster_bomb_missile': 'Cluster Bomblet Missile',
        'weapon.mine_layer_missile': 'Mine-Layer Missile',
        'weapon.det_cord_missile': 'Det-Cord Missile',
        'weapon.laser_turret': 'Laser Turret',
        'weapon.ciws': 'CIWS',
        'weapon.plasma_missile': 'Plasma Missile ×6',
        'weapon.super_weapon': 'Super Missile',
        'weapon.moonlight_greatsword': 'Moonlight Greatsword',
        'weapon.pulse_shield': 'Pulse Parry',
        'weapon.emp': 'EMP',
        'weapon.counter_mech': 'Counter Strike',
        'weapon.decoy_clone': 'Decoy Clone',
        'weapon.overdrive_burst': 'Overdrive Burst',
        'weapon.repair_protocol': 'Repair Protocol',
        'weapon.god_mode': 'God Mode',

        'weaponDesc.gun': 'Ranged | High ROF | Predictive Aim',
        'weaponDesc.sword': 'Melee | High DMG | Dash Attack',
        'weaponDesc.laser_spear': 'Mid-range Thrust | Charge | Rush',
        'weaponDesc.cluster_missile': 'Proximity Split ×8 | Tracking | Homing',
        'weaponDesc.laser_rifle': 'Hold to Charge | Aim Beam | Overheat',
        'weaponDesc.laser_smg': 'Rapid laser bursts | Snap-fire | Low DMG/heat per shot | Sustained fire overheats',
        'weaponDesc.shotgun': 'Cone Spread | 8 Pellets | Short-range Burst',
        'weaponDesc.rocket_launcher': 'AoE Rocket | Strong Center, Weak Rim | Single-shot',
        'weaponDesc.minigun': '200-round belt | 2× Rifle DMG up close | Falloff to 30% at max range | 45s reload',
        'weaponDesc.flamethrower': 'Sustained 30° flame cone | Range 240 | Damage falloff with distance | Heat-limited',
        'weaponDesc.missile_launcher': '1.1s Homing | AoE Blast | High DMG',
        'weaponDesc.high_track_missile': 'Single Shot | Hyper-Homing | 5x DMG | Slow',
        'weaponDesc.cluster_bomb_missile': 'Drops 10 bomblets midair | L30°/R45° fan | Invulnerable while dispersing',
        'weaponDesc.mine_layer_missile': 'Drops a HE mine every 0.7s along its path | Interceptable',
        'weaponDesc.det_cord_missile': 'Trails a det-cord | Detonation chains AoEs along path | 2/3 warhead DMG per node',
        'weaponDesc.laser_turret': 'Deploys a laser turret in place | Auto-fires within 600 range for 12s | 2-shot magazine',
        'weaponDesc.ciws': 'Auto-intercept | 30 Rounds | Missile Priority',
        'weaponDesc.plasma_missile': 'Proximity Fuse | Plasma DoT | Stackable',
        'weaponDesc.super_weapon': '100 DMG | Single Use | Dual Slot',
        'weaponDesc.moonlight_greatsword': '200 DMG | Massive Beam | 4 Slots | Single Use',
        'weaponDesc.pulse_shield': '0.2s parry window | Reflects all damage | 1s CD',
        'weaponDesc.emp': 'AoE + Stun | Damage Falloff | 18s CD',
        'weaponDesc.counter_mech': '3s -40% DMG | 250% Reflect | 15s CD',
        'weaponDesc.decoy_clone': '3 Decoys | 4s Stealth | 35s CD',
        'weaponDesc.overdrive_burst': '6s Burst | DMG×3 SPD×3 | -30% HP, Incoming×2 | 30s CD',
        'weaponDesc.repair_protocol': '5s Repair | SPD×1.5, +5 HP/s | No attacking | Spill into +50 shield | 35s CD',
        'weaponDesc.god_mode': '[Debug] Insta-kills everything on activation | No CD, no VFX',

        'ws.attacking': 'Attacking...',
        'ws.stagger': 'Stagger: {0}s',
        'ws.dashPush': 'Dash Push...',
        'ws.cooldown': 'Cooldown: {0}s',
        'ws.cooldownS': 'CD: {0}s',
        'ws.ready': 'Ready',
        'ws.readyShort': 'Ready',
        'ws.reloading': 'Reload {0}s',
        'ws.ammoEmpty': 'Empty! Auto-reload',
        'ws.ammo': 'Ammo: {0}/{1}',
        'ws.overheat': 'Overheat! {0}s',
        'ws.charging': 'Charging {0}%',
        'ws.coolingDown': 'Cooling...',
        'ws.heat': 'Heat: {0}/{1}',
        'ws.rushing': 'Rushing!',
        'ws.recovering': 'Recovering',
        'ws.launching': 'Launching... ({0} left)',
        'ws.launchingSimple': 'Launching...',
        'ws.shielding': 'Shield: {0}s',
        'ws.parryReady': 'Parry Ready',
        'ws.parryActive': 'PARRY!',
        'ws.countering': 'Counter: {0}s',
        'ws.stealth': 'Stealth: {0}s',
        'ws.overdriveActive': 'Overdrive: {0}s',
        'ws.repairActive': 'Repairing: {0}s',
        'ws.slashing': 'Slashing...',
        'ws.used': 'Used',
        'ws.cooldownRemaining': 'Cooldown {0}s',

        'player.dodging': 'Dodging...',
        'player.dodgeCooldown': 'Dodge CD: {0}s',
        'player.dodgeReady': 'Dodge Ready',
        'player.softLock': 'Soft Lock',
        'player.hardLock': 'Hard Lock',
        'player.manualLock': 'Manual',

        // ===== Tutorial =====
        'tut.ui.objective': 'OBJECTIVE',
        'tut.ui.tutorialLabel': 'TUTORIAL',
        'tut.ui.continueBriefing': 'Press [SPACE] to continue',
        'tut.ui.continueDebrief': 'Press [SPACE] to continue',
        'tut.ui.skipTitle': 'Skip the tutorial?',
        'tut.ui.skipBody': 'You can review every topic later in the in-game guide.',
        'tut.ui.skipPrompt': '[Y/Enter] skip   [N/ESC] back',
        'tut.intro.title': 'Welcome, {0}',
        'tut.intro.body': "A short live-fire warm-up.\nYou are invincible for the entire tutorial — relax and learn the controls.\nPress [SPACE] to begin.\n(Press ESC at any time to skip.)",
        'tut.step.move': 'W/A/S/D to move, tap [SPACE] to dash in the move direction.\nStep into all three rings (ALPHA / BRAVO / CHARLIE).',
        'tut.step.leftHand': 'Only the left-hand auto rifle is loaded — hold left mouse to fire.\nClear every training dummy on the field.',
        'tut.step.rightHand': 'Only the right-hand melee weapon is loaded — hold right mouse to swing.\nClose in and break every dummy.',
        'tut.step.shoulder': 'Only the left-shoulder 15-shot missile launcher is loaded — press Q to volley.\nDestroy all 3 hardened targets.',
        'tut.step.emp': 'Hidden ability: EMP pulse (press Shift to fire).\nThe dummies are in range — fire EMP and let it land (no instant kills, watch the FX).',
        'tut.step.dodge': 'A stunner laser turret network is active — hits will lock you down.\nPress [SPACE] to dodge 5 times without being hit within 1s before/after each press.',
        'tut.step.dodgeProgress': 'Clean dodges {0} / {1}',
        'tut.step.lock': 'Press C to cycle lock modes: soft / hard / manual.\nKill at least one dummy in EACH of the three modes.',
        'tut.lock.soft':   'SOFT',
        'tut.lock.hard':   'HARD',
        'tut.lock.manual': 'MANUAL',
        'tut.boss.title': 'Combat Simulation',
        'tut.boss.body': "Final exam — a training partner called the SPARRING DRONE.\nInvincibility is OFF, but its damage is very low and your HP is floored at 1.\nUse what you have learned and bring it down.",
        'tut.step.boss': 'Defeat the SPARRING DRONE (HP floored at 1).',
        'tut.outro.title': 'Training Complete',
        'tut.outro.body': 'Welcome to the field, {0}.\nDeeper reference is available in the in-game guide.\nPress [SPACE] to return to the main menu.',
    },

    ja: {
        'menu.startBoss': 'ボス戦開始',
        'menu.startBossDesc': '強力なボスに挑戦',
        'menu.startTutorial': '新人パイロット訓練',
        'menu.startTutorialDesc': '操作・射撃・ロックを短時間で習得',
        'menu.startTraining': '訓練場へ',
        'menu.startTrainingDesc': '反撃しないダミーで武装を試す',
        'menu.customizeMech': 'メカカスタム',
        'menu.customizeDesc': '武装を構成し戦闘スタイルを設定',
        'menu.guide': 'ゲームガイド',
        'menu.settings': '設定',
        'menu.settingsDesc': 'メカ命名などの個人設定',
        'settings.title': '設定',
        'settings.subtitle': 'PERSONAL PREFERENCES',
        'settings.mechNameLabel': 'メカ名',
        'settings.mechNameHint': '愛機の専用コードネームを設定 (1〜24 文字)',
        'settings.save': '保存',
        'settings.saved': '保存しました',
        'settings.reset': 'デフォルトに戻す',
        'settings.back': '戻る',
        'settings.contactHeader': '// CONTACT — 作者へ連絡',
        'settings.contactGreeting': 'お気軽にご連絡ください！',
        'settings.contactBili': 'Bilibili: ガンダムさん',
        'settings.contactBiliUid': 'UID: 3493134971439675',
        'menu.selectLevel': 'ステージ選択',
        'menu.bossModeSub': 'ボス戦モード - 強敵に挑戦',
        'menu.difficulty': '難易度: ',
        'menu.locked': '🔒 未開放',
        'menu.back': '戻る',
        'menu.backArrow': '← 戻る',
        'menu.mainMenu': 'メインメニュー',
        'menu.backToMenu': 'メニューに戻る',
        'menu.backToCatalog': '一覧に戻る',
        'menu.backTo': '{0}に戻る',

        'cfg.selected': '選択中: {0}',
        'cfg.leftHand': '左手武器',
        'cfg.rightHand': '右手武器',
        'cfg.leftShoulder': '左肩武器',
        'cfg.rightShoulder': '右肩武器',
        'cfg.hiddenAbility': '隠しアビリティ',
        'cfg.leftKey': '(左クリック)',
        'cfg.rightKey': '(右クリック)',
        'cfg.qKey': '(Qキー)',
        'cfg.eKey': '(Eキー)',
        'cfg.shiftKey': '(Shiftキー)',
        'cfg.none': 'なし',
        'cfg.currentConfig': '現在の構成:',
        'cfg.invincibleOn': '無敵モード: ON',
        'cfg.invincibleOff': '無敵モード: OFF',
        'cfg.startGame': 'ゲーム開始',
        'cfg.configHint': 'スロットをクリックして武装を選び、ゲーム開始へ',
        'cfg.customHint': 'スロットをクリックして武装を選び、メニューに戻る',

        'hud.mech': 'メカ: {0}',
        'hud.health': '❤️ HP: ',
        'hud.invincible': '⭐ 無敵モード ⭐',
        'hud.leftKey': '🖊️ 左クリック - ',
        'hud.rightKey': '🖐️ 右クリック - ',
        'hud.dodgeKey': '⚡ スペース - ',
        'hud.dodge': '回避: {0}',
        'hud.lockKey': '🎯 F - ',
        'hud.lockMode': 'ロック: {0}',
        'hud.shiftKey': '🛡️ Shift - ',
        'hud.noWeapon': '武器なし',
        'hud.noHidden': 'アビリティなし',
        'hud.dodgeLimit': '回避ロック',
        'hud.cKey': '🔄 C - ',
        'hud.switchTarget': 'ターゲット切替',
        'hud.qKey': '🚀 Q - ',
        'hud.eKey': '🚀 E - ',
        'hud.noLeftShoulder': '左肩なし',
        'hud.noRightShoulder': '右肩なし',
        'hud.ctrlKey': '🛠️ Ctrl - ',
        'hud.repairKit': '修理キット: {0}/{1}',
        'hud.repairEmpty': '修理キット: 残量なし',
        'hud.mode': 'モード: {0}',
        'hud.bossKills': 'ボス撃破数: {0}',

        'enemy.elite': 'エリート',

        'ui.paused': '一時停止',
        'ui.pauseHint': 'P で再開',
        'ui.pauseBtn': '一時停止',
        'ui.gameOver': 'ゲームオーバー',
        'ui.totalDamage': '総ダメージ: {0}',
        'ui.spaceReturn': 'スペースキーでメニューへ',
        'ui.victory': '🎉 勝利！🎉',
        'ui.defeated': '{0} を撃破！',
        'ui.finalScore': '最終スコア: {0}',
        'ui.blindStatus': 'シグナル妨害',
        'ui.blindRemaining': '残り時間: {0}秒',
        'ui.langToggle': 'EN',
        'ui.gameTitle': 'メカ戦闘ゲーム',

        'boss.CRIMSON_KING': '深紅の王',
        'boss.SUBLIME_MOON': '氷姫',
        'boss.STAR_DEVOURER': '星喰らい',
        'boss.UGLY_EMPEROR': '醜皇',
        'boss.MAGNUS_EXEC': 'メカ執政官 マグナス',
        'boss.HIVE_MIND': 'ハイブマインド',
        'boss.YUKIKON': '剣舞 雪魂',
        'boss.PROTEUS': '可変メカ プロテウス',
        'boss.TRIUMVIRATE': '元素三主神',
        'boss.unknown': '不明なボス',
        'bossDesc.CRIMSON_KING': '深紅の恐怖の支配者、闇の力を操る',
        'bossDesc.SUBLIME_MOON': '青藍の神秘なる支配者、氷の月光を放つ',
        'bossDesc.STAR_DEVOURER': '白黒の虚無の破壊者、光と闇すべてを喰らう',
        'bossDesc.UGLY_EMPEROR': '歪んだ混沌の支配者、歪曲と混乱の力を操る',
        'bossDesc.MAGNUS_EXEC': '重装メカ執政官 — 双肩砲塔、長距離制圧と軌道砲撃',
        'bossDesc.HIVE_MIND': '群れに守られた女王意識体。本体は脆いが届かない、撃破時に四つの残識へ分裂',
        'bossDesc.YUKIKON': '高機動近接決闘者 — 瞬移、突進、剣の雨、影分身で常に圧をかける。弾は避けず距離で逃げる',
        'bossDesc.PROTEUS': '距離に応じて長戟近接 / 散弾遊撃 / 据置砲台へ実時間で再構成。再構成中が脆い',

        'boss.pierce': '貫通!',
        'boss.blind': '失明',
        'boss.immune': '無敵',
        'boss.clone': '分身',
        'boss.burn': '燃焼',

        'boss.blindActive': '失明発動中 {0}s',
        'boss.blindUnlockNeed': '失明解放まで残り {0} ダメージ',
        'boss.blindUnlocked': '失明スキル解放',
        'boss.blindCooldown': '失明CD {0}s {1}',
        'boss.blindReady': '失明スキル準備完了 {0}',
        'boss.phase1': '(第1段階)',
        'boss.phase2label': '(第2段階)',
        'boss.phase2Visible': '第2段階 - 距離 {0}/{1} - 可視',
        'boss.phase2Cloaked': '第2段階 - 距離 {0}/{1} - 不可視',
        'boss.phase2Trigger': '第2段階発動まで残り {0} ダメージ',

        'mode.BOSS_BATTLE': 'ボス戦モード',
        'modeDesc.BOSS_BATTLE': '強力なボスに挑戦',
        'mode.TRAINING': '訓練場',
        'modeDesc.TRAINING': '反撃しない練習用ダミー | 即時リスポーン',
        'mode.TUTORIAL': 'チュートリアル',
        'modeDesc.TUTORIAL': '新人パイロット訓練',
        'mech.HYBRID': 'ハイブリッドメカ',

        'weapon.gun': 'オートライフル',
        'weapon.sword': 'ビームサーベル',
        'weapon.laser_spear': 'レーザーランス',
        'weapon.cluster_missile': '分裂ミサイル',
        'weapon.laser_rifle': 'レーザーライフル',
        'weapon.laser_smg': 'レーザーSMG',
        'weapon.shotgun': 'ショットガン',
        'weapon.rocket_launcher': 'ロケットランチャー',
        'weapon.minigun': 'ミニガン',
        'weapon.flamethrower': '火炎放射器',
        'weapon.missile_launcher': '15連ミサイル発射機',
        'weapon.high_track_missile': '高誘導ミサイル',
        'weapon.cluster_bomb_missile': 'クラスターミサイル',
        'weapon.mine_layer_missile': '機雷敷設ミサイル',
        'weapon.det_cord_missile': '導爆索ミサイル',
        'weapon.laser_turret': 'レーザータレット',
        'weapon.ciws': 'CIWS',
        'weapon.plasma_missile': '6連プラズマミサイル',
        'weapon.super_weapon': 'スーパーミサイル',
        'weapon.moonlight_greatsword': '月光の大剣',
        'weapon.pulse_shield': 'パルス弾き',
        'weapon.emp': 'EMP',
        'weapon.counter_mech': 'カウンター',
        'weapon.decoy_clone': 'デコイクローン',
        'weapon.overdrive_burst': 'オーバードライブ',
        'weapon.repair_protocol': 'リペアプロトコル',
        'weapon.god_mode': 'ゴッドモード',

        'weaponDesc.gun': '遠距離射撃 | 高連射 | 予測射撃',
        'weaponDesc.sword': '近接 | 高ダメージ | ダッシュ突撃',
        'weaponDesc.laser_spear': '中距離突き | チャージ | 突進',
        'weaponDesc.cluster_missile': 'ロックオン対象付近で8発分裂 | 持続追尾',
        'weaponDesc.laser_rifle': 'チャージ式 | 予測ビーム | オーバーヒート',
        'weaponDesc.laser_smg': '速射レーザー | 即発射 | 単発威力低・熱量低 | 持続射撃でオーバーヒート',
        'weaponDesc.shotgun': '円錐拡散 | 8 ペレット | 近距離爆発力',
        'weaponDesc.rocket_launcher': '範囲ロケット | 中心強・周縁弱 | 単発装填',
        'weaponDesc.minigun': '200発リンク | 近距離でライフルの2倍 | 最大射程で30%まで減衰 | 装填45秒',
        'weaponDesc.flamethrower': '30°炎の円錐を持続噴射 | 射程240 | 距離減衰 | 過熱制限',
        'weaponDesc.missile_launcher': '1.1秒強誘導 | 範囲爆発 | 高ダメージ',
        'weaponDesc.high_track_missile': '単発 | 超強誘導 | 5倍ダメージ | 速度高め',
        'weaponDesc.cluster_bomb_missile': '空中で10発のサブ弾を散布 | L30°/R45°交互 | 散布中は無敵',
        'weaponDesc.mine_layer_missile': '飛行中0.7秒毎に高威力機雷を敷設 | 迎撃可能',
        'weaponDesc.det_cord_missile': '尾部に導爆索を曳く | 起爆で経路に沿って連鎖AOE | 各節2/3ダメージ',
        'weaponDesc.laser_turret': '機体位置にレーザータレットを設置 | 射程600以内へ12秒間自動射撃 | 弾倉2発',
        'weaponDesc.ciws': '誘導兵器を自動迎撃 | 30発弾倉 | ミサイル優先',
        'weaponDesc.plasma_missile': '近接信管 | プラズマ持続ダメージ | 重ねがけ可',
        'weaponDesc.super_weapon': '100ダメージ | 1戦1回限り | 両肩スロット占有',
        'weaponDesc.moonlight_greatsword': '200ダメージ | 巨大ビーム | 4スロット占有 | 1戦1回限り',
        'weaponDesc.pulse_shield': '0.2秒弾き窓 | 全ダメージ反射 | 1秒CD',
        'weaponDesc.emp': '範囲ダメージ + スタン | 距離で減衰 | 18秒CD',
        'weaponDesc.counter_mech': '3秒-40%被ダメ | 250%反射 | 15秒CD',
        'weaponDesc.decoy_clone': '3体のデコイ | 4秒間ステルス | 35秒CD',
        'weaponDesc.overdrive_burst': '6秒バースト | 攻撃×3 移動×3 | -30%HP 被ダメ×2 | 30秒CD',
        'weaponDesc.repair_protocol': '5秒修理 | 移動×1.5 5HP/秒 | 攻撃不可 | 余剰は+50シールド | 35秒CD',
        'weaponDesc.god_mode': '【デバッグ】発動で場の全ユニット即死 | CD/エフェクトなし',

        'ws.attacking': '攻撃中...',
        'ws.stagger': 'スタン: {0}秒',
        'ws.dashPush': 'ダッシュ突進中...',
        'ws.cooldown': 'CD: {0}秒',
        'ws.cooldownS': 'CD: {0}s',
        'ws.ready': '使用可能',
        'ws.readyShort': '可',
        'ws.reloading': 'リロード {0}s',
        'ws.ammoEmpty': '弾切れ！自動リロード',
        'ws.ammo': '弾薬: {0}/{1}',
        'ws.overheat': 'オーバーヒート! {0}s',
        'ws.charging': 'チャージ {0}%',
        'ws.coolingDown': '冷却中...',
        'ws.heat': '熱量: {0}/{1}',
        'ws.rushing': '突進中！',
        'ws.recovering': '回復中',
        'ws.launching': '発射中... (残り{0})',
        'ws.launchingSimple': '発射中...',
        'ws.shielding': 'シールド: {0}秒',
        'ws.parryReady': '弾き 待機',
        'ws.parryActive': '弾き!',
        'ws.countering': 'カウンター: {0}s',
        'ws.stealth': 'ステルス: {0}s',
        'ws.overdriveActive': 'OD: {0}s',
        'ws.repairActive': 'リペア: {0}s',
        'ws.slashing': '斬撃中...',
        'ws.used': '使用済み',
        'ws.cooldownRemaining': 'CD {0}s',

        'player.dodging': '回避中...',
        'player.dodgeCooldown': '回避CD: {0}秒',
        'player.dodgeReady': '回避可能',
        'player.softLock': 'ソフトロック',
        'player.hardLock': 'ハードロック',
        'player.manualLock': 'マニュアル',

        // ===== Tutorial =====
        'tut.ui.objective': '現在の目標',
        'tut.ui.tutorialLabel': 'チュートリアル',
        'tut.ui.continueBriefing': '[スペース] で次へ',
        'tut.ui.continueDebrief': '[スペース] で次へ',
        'tut.ui.skipTitle': 'チュートリアルをスキップしますか？',
        'tut.ui.skipBody': '後でゲーム内のガイドからいつでも復習できます。',
        'tut.ui.skipPrompt': '[Y/Enter] スキップ　[N/ESC] 戻る',
        'tut.intro.title': 'ようこそ、{0}',
        'tut.intro.body': '短い実弾訓練だ。\n訓練中はずっと無敵なので、安心して操作を覚えてくれ。\n[スペース] で開始。\n（いつでも ESC でスキップ可能。）',
        'tut.step.move': 'W/A/S/D で移動、[スペース] で移動方向にダッシュ回避。\n3 つの光輪 (ALPHA / BRAVO / CHARLIE) に順番に入れ。',
        'tut.step.leftHand': '左手の自動小銃のみ装備中——左クリックで連射。\nダミーを全て撃破せよ。',
        'tut.step.rightHand': '右手の近接武器のみ装備中——右クリックで斬撃。\n接近して全てのダミーを破壊せよ。',
        'tut.step.shoulder': '左肩 15 連ミサイル発射器のみ装備中——Q で一斉発射。\n3 体の重装標的を全て撃破せよ。',
        'tut.step.emp': '隠し機能：EMP 電磁パルス（Shift で発動）。\nダミーは有効範囲内に配置済み——一撃で殲滅せよ。',
        'tut.step.dodge': 'レーザー砲台が起動中——被弾するとスタンする。\n[スペース] でダッシュ回避を 5 回成功させよ（前後 1 秒以内に被弾しないこと）。',
        'tut.step.dodgeProgress': 'クリア回避 {0} / {1}',
        'tut.step.lock': 'C キーでロックモードを循環：ソフト / ハード / マニュアル。\n3 種それぞれで最低 1 体ずつ撃破せよ。',
        'tut.lock.soft':   'ソフト',
        'tut.lock.hard':   'ハード',
        'tut.lock.manual': 'マニュアル',
        'tut.boss.title': '実戦シミュレーション',
        'tut.boss.body': '最終試験——「SPARRING DRONE」と呼ばれる訓練機が相手だ。\nこのステージは無敵を解除する。ただしダメージは極小で、HP は 1 で下限固定だ。\n習得した技術で撃破せよ。',
        'tut.step.boss': 'SPARRING DRONE を撃破せよ（HP 下限 1）。',
        'tut.outro.title': '訓練完了',
        'tut.outro.body': '戦場へようこそ、{0}。\n詳しい資料はゲーム内ガイドで確認できる。\n[スペース] でメインメニューへ戻る。',
    }
};

const guideData = {
    zh: [
        {
            id: 'controls', name: '操作说明', color: '#4488FF',
            content: [
                '【移动】 WASD / 方向键',
                '【左手武器】 鼠标左键',
                '【右手武器】 鼠标右键',
                '【左肩武器】 Q键',
                '【右肩武器】 E键',
                '【隐藏机能】 Shift键',
                '【闪避】 空格 + 方向键（0.15秒，冷却0.35秒）',
                '【切换锁定】 F键（软锁→硬锁→手动锁）',
                '【切换目标】 C键（硬锁模式下）',
                '【维修包】 Ctrl键（+60HP，共3个）',
                '【暂停】 P键',
                '【返回主菜单】 ESC键',
                '',
                '— 锁定系统 —',
                '软锁：自动瞄准最近敌人',
                '硬锁：锁定当前目标不放，C键切换',
                '手动锁：鼠标控制瞄准方向',
            ]
        },
        {
            id: 'hand_weapons', name: '手部武器', color: '#4169E1',
            items: [
                { name: '自动步枪', demoId: 'weapons:gun', color: '#4169E1', lines: [
                    '伤害 8/发 | 射速 5发/秒',
                    '弹匣 30发 | 重装 2秒',
                    '自动预瞄：根据目标速度预判落点',
                ]},
                { name: '脉冲光束军刀', demoId: 'weapons:sword', color: '#ff6b6b', lines: [
                    '伤害 50 | 120°扇形范围',
                    '冷却 4.8秒',
                    '刀推：距目标过远时自动冲刺接近',
                ]},
                { name: '镭射长枪', demoId: 'weapons:laser_spear', color: '#00FFFF', lines: [
                    '伤害 25 | 冲锋距离 400像素',
                    '冲锋速度 40 | 冷却 5秒',
                    '可扎穿敌人并带其一起移动',
                ]},
                { name: '镭射步枪', demoId: 'weapons:laser_rifle', color: '#FF4444', lines: [
                    '伤害 18 | 蓄力 1秒后发射',
                    '射击间隔 0.7秒 | 射程无限',
                    '过热系统：每发+50热量，≥200过热',
                    '过热后强制散热7秒',
                ]},
                { name: '镭射机枪', demoId: 'weapons:laser_smg', color: '#FF8866', lines: [
                    '伤害 6/发 | 蓄力极短(0.12秒) | 射击间隔 0.18秒',
                    '单发热量低(+14)，可连续点射约 14 发再过热',
                    '过热后强制散热7秒',
                    '速射型镭射，适合追打高机动目标',
                ]},
                { name: '分裂飞弹', demoId: 'weapons:cluster_missile', color: '#FFD700', lines: [
                    '发射1枚母弹，持续索敌（8秒无目标自爆）',
                    '锁定的目标接近时分裂为8枚子弹',
                    '子弹伤害 4 | 高追踪性 | 冷却 4秒',
                    '分裂后先扇形散开再制导',
                ]},
                { name: '霰弹枪', demoId: 'weapons:shotgun', color: '#ff9040', lines: [
                    '伤害 8/弹 × 12颗弹丸 | 锥形扩散22°',
                    '伤害随距离线性衰减 | 满射程时降至20%',
                    '射程 700px | 射击间隔 0.7秒',
                    '弹匣 6发 | 重装 1.6秒',
                    '近距离贴脸输出爆炸',
                ]},
                { name: '火箭筒', demoId: 'weapons:rocket', color: '#ff7030', lines: [
                    '伤害 30 | 爆炸半径 180px | 中心强 边缘5%',
                    '伤害随距离平方衰减 | 射程 900px',
                    '射击间隔 1.1秒 | 单发膛 | 重装 2.6秒',
                    '高爆AOE，正中目标威力极高',
                ]},
                { name: '加特林', demoId: 'weapons:minigun', color: '#d4a040', lines: [
                    '200发弹链 | 单发伤害约 2 倍步枪(近距离)',
                    '远距离衰减至 30% | 装填 45 秒',
                    '需要短暂转管启动 | 持续输出极强',
                ]},
                { name: '火焰喷射器', demoId: 'weapons:flamethrower', color: '#FF6020', lines: [
                    '持续按住喷出 30° 火焰锥 | 射程 240',
                    'Tick 伤害 4，每 110ms 命中一次（约 36 DPS）',
                    '距离衰减：枪口 100% → 锥尖 50%',
                    '过热限制：连续喷约 1.4 秒达上限，需冷却',
                ]},
            ]
        },
        {
            id: 'shoulder_weapons', name: '肩部武器', color: '#FF8800',
            items: [
                { name: '15连导弹发射器', demoId: 'shoulder:missile', color: '#FFD700', lines: [
                    '每次齐射 15枚 | 每枚 5伤害',
                    '前1.1秒强追踪 | 爆炸半径 80px',
                    '冷却 4秒',
                ]},
                { name: '高诱导飞弹', demoId: 'shoulder:high_track', color: '#FF8030', lines: [
                    '单发齐射 | 爆炸半径 80px',
                    '伤害 25（约 5 倍普通飞弹）',
                    '诱导半径 800px，强诱导持续 2.8 秒',
                    '弹速比普通飞弹快 30%',
                    '冷却 4 秒',
                ]},
                { name: '集束飞弹', demoId: 'shoulder:cluster_bomb', color: '#FFA040', lines: [
                    '本体伤害 1，飞行 1 秒后开始投放子弹',
                    '4 秒内向前方 L30°/R45° 轮流投放共 10 枚子弹',
                    '子弹伤害 8（高诱导力）',
                    '投放期间本体无敌，无法被吞噬/拦截',
                    '冷却 4 秒',
                ]},
                { name: '布雷飞弹', demoId: 'shoulder:mine_layer', color: '#FF6040', lines: [
                    '本体伤害 1，飞行中每 0.7 秒在身下布置一枚高爆机雷',
                    '机雷伤害 30（仅伤害敌人，不伤己）',
                    '机雷外观与丑皇不同，玩家始终可见',
                    '本体在投放第一枚雷之前不可被摧毁',
                    '冷却 4 秒',
                ]},
                { name: '爆导索飞弹', demoId: 'shoulder:det_cord', color: '#FFB060', lines: [
                    '本体伤害 12，命中或自爆后激发爆导索',
                    '从发射点起沿飞行轨迹依次连环爆炸（AOE）',
                    '每节爆炸伤害 17（母弹 2/3）',
                    '连锁爆炸速度比初版快 4 倍',
                    '冷却 12 秒（重装较慢）',
                ]},
                { name: '镭射炮台', demoId: 'shoulder:laser_turret', color: '#88E0FF', lines: [
                    '在玩家位置部署一座静止镭射炮台',
                    '存在 12 秒，自动锁定 600 范围内最近敌人',
                    '每 1 秒发射 0.4 秒短脉冲镭射，单次伤害 8',
                    '弹仓 2 发，打完后整体重装 8 秒',
                    '炮台不可被锁定/吞噬，临死前会闪烁示警',
                ]},
                { name: '近防炮 (CIWS)', demoId: 'shoulder:ciws', color: '#00FF88', lines: [
                    '全自动射击 30发/秒 | 弹仓 30发',
                    '优先级：导弹 > 月牙弹 > 策反弹 > 机雷 > 敌人',
                    '对制导武器一发摧毁',
                    '对敌人本体 40%概率造成伤害',
                ]},
                { name: '6连电浆飞弹', demoId: 'shoulder:plasma', color: '#00FFCC', lines: [
                    '6枚连射 | 近炸引信（55px引爆）',
                    '生成电浆场：持续1秒，每0.25秒造成3伤害',
                    '多个电浆场可叠加 | 冷却 5秒',
                ]},
                { name: '超级导弹', demoId: 'shoulder:super', color: '#FF0000', lines: [
                    '伤害 100 | 占用左右肩双槽位',
                    '爆炸半径 400px | 超强追踪 4.1秒',
                    '每场战斗限用1次',
                ]},
                { name: '月光大剑', demoId: 'shoulder:moonlight', color: '#88CCFF', lines: [
                    '伤害 200 | 占用右手+双肩+隐藏机能共4槽位',
                    '光刃长度为光束军刀的7倍（1050px）',
                    '机体朝向±90°共180°范围 | 1秒完成扫击',
                    '无法秒杀Boss（最低保留1HP）',
                    '每场战斗限用1次',
                ]},
            ]
        },
        {
            id: 'hidden', name: '隐藏机能', color: '#00FFFF',
            items: [
                { name: '脉冲振刀', demoId: 'hidden:pulse_shield', color: '#00FFFF', lines: [
                    '振刀窗口 0.2秒 | 反弹所有伤害类型',
                    '冷却 1秒',
                ]},
                { name: 'EMP电磁脉冲', demoId: 'hidden:emp', color: '#66CCFF', lines: [
                    '范围 490px | 最大伤害 100',
                    '距离越远伤害越低 | 附加2秒僵直',
                    '冷却 18秒',
                ]},
                { name: '反制重击', demoId: 'hidden:counter', color: '#FF8C00', lines: [
                    '持续 3秒 | 受伤减少 40%',
                    '将受到伤害的250%反射给最近敌人',
                    '冷却 15秒',
                ]},
                { name: '诱饵分身', demoId: 'hidden:decoy', color: '#4488FF', lines: [
                    '释放 3 个全息诱饵（等边三角形散开）',
                    '诱饵 40HP | 最多存活 7秒',
                    '玩家进入 4秒不可锁定状态',
                    '敌方AI/导弹/子弹转向攻击诱饵',
                    '冷却 35秒',
                ]},
                { name: '超限爆发', demoId: 'hidden:overdrive', color: '#FF2030', lines: [
                    '激活时立即损失30%当前血量',
                    '持续 6秒：伤害 ×3 | 移速 ×3',
                    '机身变红 | 冲刺时留下残影',
                    '代价：受到的伤害放大至 ×2',
                    '冷却 30秒',
                ]},
                { name: '应急修复', demoId: 'hidden:repair', color: '#60FF90', lines: [
                    '激活时清空旧的溢出护盾',
                    '持续 5秒：移速 ×1.5 | 每秒恢复 5HP',
                    '期间无法使用任何武器和闪避',
                    '满血后溢出 HP 转为护盾，最多 +50',
                    '冷却 35秒',
                ]},
                { name: '金手指（调试）', demoId: 'hidden:godmode', color: '#FFD700', lines: [
                    '【调试用，无特效】',
                    '释放即瞬杀场上一切单位',
                    '无冷却时间，可随意使用',
                ]},
            ]
        },
        {
            id: 'bosses', name: 'Boss图鉴', color: '#FF4444',
            items: [
                { name: '血红之王', demoId: 'boss:CRIMSON_KING', color: '#8B0000', lines: [
                    'HP 300 | 导弹洗地型',
                    '',
                    '— 攻击方式 —',
                    '齐射(salvo)：60枚普通导弹四方向轮流，每枚6伤害',
                    '追踪(homing)：6枚琥珀色强追踪导弹，每枚12伤害（1600px制导）',
                    '电浆方阵(square)：4边各3枚大型电浆球追踪玩家，命中后留电浆场',
                    '网格光束：4纵+3横激光网，强制走位至空格',
                    '',
                    '— 特殊机制 —',
                    '累积减伤：1秒内受伤越多减伤越高（不归零）',
                    '导弹闪避：被追踪时80%闪避',
                    '回血：每3秒 45%概率恢复6-20HP',
                    '',
                    '— 建议 —',
                    '近防炮拦截导弹，配合近战输出',
                    '避免短时间集中火力触发高减伤',
                ]},
                { name: '冰之姬', demoId: 'boss:SUBLIME_MOON', color: '#4682B4', lines: [
                    'HP 200 | 高机动刺客型',
                    '',
                    '— 攻击方式 —',
                    '月牙追踪弹：多种发射模式（齐射/扇形/螺旋）',
                    '回旋斩：玩家靠近时主动释放，附带减速debuff',
                    '导弹拦截：导弹接近时用回旋斩打爆来袭导弹',
                    '冰冻分身：召唤分身，间歇性发射追踪寒冰弹',
                    '',
                    '— 特殊机制 —',
                    '高频瞬移：偏好瞬移而非走位，瞬移到玩家背后',
                    '镭射步枪抗性：受到镭射步枪伤害降低 80%',
                    '极高导弹闪避：90%概率闪避制导武器',
                    '',
                    '— 建议 —',
                    '近防炮拦截月牙弹与寒冰弹',
                    '勿过度依赖镭射步枪 / 制导武器',
                    '保持中近距离，利用霰弹/火箭筒爆发',
                ]},
                { name: '噬星者', demoId: 'boss:STAR_DEVOURER', color: '#333333', lines: [
                    'HP 300 | 战术压制型',
                    '',
                    '— 攻击方式 —',
                    '光束步枪：25伤害+0.7秒僵直',
                    '自动步枪：近距离6伤害/发，30发/秒',
                    '浮游炮×3：各70HP，镭射15伤害+僵直',
                    '',
                    '— 特殊机制 —',
                    '信号干扰：屏幕被强烈雪花噪点覆盖，无法切换锁定',
                    '二阶段(≤80HP)：隐身(200px内可见)',
                    '导弹反转：75%玩家导弹被策反攻击玩家',
                    '',
                    '— 建议 —',
                    '优先摧毁浮游炮，近防炮拦截策反导弹',
                    '信号干扰期间凭手感持续移动，二阶段需近距离作战',
                ]},
                { name: '丑皇', demoId: 'boss:UGLY_EMPEROR', color: '#8B4513', lines: [
                    'HP 250 | 区域控制型',
                    '',
                    '— 攻击方式 —',
                    '混沌弹幕：8发/波，4伤害/发',
                    '扭曲光环：半径80px持续伤害场',
                    '机雷(一阶段)：引爆15伤害',
                    '燃烧瓶(二阶段)：产生燃烧区域',
                    '',
                    '— 特殊机制 —',
                    '一阶段：免疫导弹伤害',
                    '二阶段(≤100HP)：仅受导弹伤害，伤害×2',
                    '混沌传送：每8秒传送到玩家附近',
                    '',
                    '— 建议 —',
                    '一阶段用步枪/激光/近战，近防炮清机雷',
                    '二阶段全力导弹输出（伤害翻倍）',
                    '两阶段需完全不同的武器策略',
                ]},
                { name: '机甲执政官 Magnus', demoId: 'boss:MAGNUS_EXEC', color: '#C68C2A', lines: [
                    'HP 600 | 重装压制型',
                    '',
                    '— 攻击方式 —',
                    '主炮齐射：高速实弹弹幕',
                    '轨道炮击：圈内画地为牢，AOE覆盖打击',
                    '肩载炮塔×2：80HP，独立索敌火力',
                    '蜉蝣炮台：脱离的肩载炮塔会发射追踪火箭弹（仅它们能发射火箭，本体不会）',
                    '',
                    '— 阈值护盾 —',
                    '盾值上限 50% 总血量',
                    '≤40 单体伤害：完全免伤（被盾全额吸收）',
                    '40~200 单体伤害：随伤害递增的非线性减伤',
                    '>200 单体伤害：100%打入本体，盾值损失×2',
                    '破盾后冷却 70秒重新生成（25%概率提前 1.2秒重启）',
                    '',
                    '— 建议 —',
                    '高单发武器（月光大剑/超级导弹）一击破盾',
                    '小数值连射会被护盾吃光，先破盾再输出',
                    '优先摧毁肩部炮塔，再压制本体',
                    '近防炮专门对付脱离的炮台火箭弹',
                ]},
                { name: '蜂巢意识', demoId: 'boss:HIVE_MIND', color: '#9C27B0', lines: [
                    'HP 320 (本体) | 多体协同型',
                    '',
                    '— 攻击方式 —',
                    '紫色等离子弹幕：高频齐射',
                    '无人机蜂群：上限50只，每0.5秒补充至4只',
                    '  · 防御型：拦截玩家攻击与制导武器',
                    '  · 攻击型：环绕女王突袭并射击玩家',
                    '无人机 10HP，被击落后立即触发补充',
                    '蜂群残识(二阶段)：4只 80HP 残识，紫色等离子狙击',
                    '残识各自可召唤上限12的小型蜂群（速度1/4）',
                    '',
                    '— 特殊机制 —',
                    '无人机不可被锁定，但会主动拦截一切攻击',
                    '本体长期不可触及，只在蜂群被压制时短暂暴露',
                    '残识形态：女王进入幽灵状态不可见也不可锁定',
                    '残识互相排斥，远离玩家，难以一波集中清除',
                    '',
                    '— 建议 —',
                    '霰弹/火箭/EMP 等 AOE 清扫无人机',
                    '抓住女王暴露窗口集中爆发',
                    '残识阶段优先处理对玩家威胁最大的那只',
                ]},
                { name: '剑舞者 雪魂 (Yukikon)', demoId: 'boss:YUKIKON', color: '#7fc8ff', lines: [
                    'HP 150 | 高速近战决斗者',
                    '',
                    '— 攻击方式 —',
                    '闪斩(flashStrike)：极短抬手的瞬移突进劈砍',
                    'SMG 突射(smgBurst)：中距离机枪扫射',
                    '剑雨(swordRain)：召唤多把剑插入地面后激发',
                    '影分身(shadowStep)：留下分身互相替换位置干扰锁定',
                    '居合冲锋(iaiCharge)：拉开 200~520px 距离的弧线居合',
                    '游走时持续 SMG 短点射，从不"安静"',
                    '',
                    '— 特殊机制 —',
                    '近战护盾：挥剑期间远程伤害减至 15%（剑/光刃/月牙不受影响）',
                    '自带近防炮拦截：高速拦截制导武器，无视距离',
                    '偏好瞬移而非走位，频繁变换战场距离',
                    '',
                    '— 建议 —',
                    '尽量用近战武器贴身换血，远程会被严重削弱',
                    '注意她抬手挥剑的瞬间，那几帧远程基本无效',
                    '影分身阶段不要乱锁，等真身露脸',
                ]},
                { name: '变形机甲 普罗忒斯 (Proteus)', demoId: 'boss:PROTEUS', color: '#a0ffc0', lines: [
                    'HP 360 | 形态切换型',
                    '',
                    '— 三种形态（按距离切换）—',
                    '长戟形态(近战 < 350px)：突刺 / 横扫 / 长程波动 (伤害已削减50%)',
                    '游骑形态(中距 350~600px)：霰弹爆破、闪现、自愈、EMP、偶发激光炮',
                    '炮台形态(远程 > 600px)：部署静态炮塔弧线射击 + 近防炮拦截制导武器',
                    '',
                    '— 重组(重要弱点)—',
                    '形态切换约 0.6秒，期间无法攻击且 +25% 受伤',
                    '强制让他换形态可以撕开伤害窗口',
                    '每 20秒会主动循环切换一次',
                    '',
                    '— 阈值护盾(炮台形态)—',
                    '盾值上限 32% 总血量，伤害 -80%',
                    '回复极慢(满盾约 333秒)，破盾后冷却 8秒重生',
                    '破盾时有 35% 概率仅 1.2秒后重新激活',
                    '若在护盾激活时被强制切换形态 → 原地释放大范围 AOE 冲击波',
                    '',
                    '— 建议 —',
                    '不停拉近 / 推远迫使他切换，重组瞬间集火',
                    '炮台形态破盾用大单发武器，低伤连射会被护盾吃光',
                    '别在护盾激活时贴脸逼他切换，会被反震',
                ]},
                { name: '元素三主神 + 虚空', demoId: 'boss:TRIUMVIRATE', color: '#c87cff', lines: [
                    '三本体各 HP 240 | 杀两个后第三个变身为虚空 HP 200',
                    '',
                    '— 火神 Pyron（中近距压制）—',
                    '热熔柱(Heat Lance)：原地长出柱形烈焰，多层粒子',
                    '火焰喷射(Flamethrower Sweep)：长程跟踪锥火（射程 630px）',
                    '',
                    '— 雷神 Volthar（远程吊放）—',
                    '磁吸闪电(Magnet Strike)：从本体身上发出，蜿蜒延伸寻找玩家',
                    '铁桩仪式(Iron Spike)：全图一次部署多根机甲铁桩，引来 AOE 落雷+长僵直',
                    '',
                    '— 冰神 Glacius（远程减速控制）—',
                    '寒冰导弹(Frost Bolt)：三连发追踪弹，0伤害但叠加重度减速',
                    '寒冰冲击(Frost Nova)：以自身为中心 AOE，命中即 1秒僵直，原地留减速冰场',
                    '',
                    '— 三本体共通 —',
                    '同时出场，独立血条，互相会自动错开避免扎堆',
                    '受击时会侧身闪避(reactive sidestep)',
                    '',
                    '— 虚空 Voidborn（杀两个后登场）—',
                    'HP 200 | 缓慢飘移不主动追玩家',
                    '虚空吞噬：吸收所有非近战攻击（半径 240px 内的远程弹药直接消失）',
                    '虚空传送：玩家在 160px 内停留 0.35秒立刻被传送到远角',
                    '黑洞炮：一次发射 3 颗黑洞弹，引爆后形成强力吸力场，可无限叠加',
                    '近战减伤 50%（剑/光刃/月光对它效果减半）',
                    '',
                    '— 建议 —',
                    '优先击杀冰神切断减速，再处理雷神规避地刺AOE',
                    '虚空阶段近战才是有效输出，但要小心被传送',
                    '黑洞炮多发叠加时几乎跑不掉，提前预走位',
                ]},
            ]
        },
        {
            id: 'status', name: '状态效果', color: '#AAAAAA',
            content: [
                '【僵直】 短暂无法移动和行动',
                '【燃烧】 持续5秒，每0.1秒受2伤害，移速-20%',
                '【减速】 冰之姬回旋斩附加，短时间大幅降低移速',
                '【信号干扰】 噬星者专属，屏幕雪花噪点覆盖，无法切换锁定',
                '',
                '— 玩家属性 —',
                '生命值：150',
                '移动速度：20',
                '维修包：3个，每个恢复60HP',
                '闪避：0.15秒，冷却0.35秒',
            ]
        },
    ],

    en: [
        {
            id: 'controls', name: 'Controls', color: '#4488FF',
            content: [
                '[Move] WASD / Arrow Keys',
                '[Left Hand] Left Mouse Button',
                '[Right Hand] Right Mouse Button',
                '[Left Shoulder] Q Key',
                '[Right Shoulder] E Key',
                '[Hidden Ability] Shift Key',
                '[Dodge] Space + Direction (0.15s, 0.35s CD)',
                '[Toggle Lock] F Key (Soft → Hard → Manual)',
                '[Switch Target] C Key (Hard Lock mode)',
                '[Repair Kit] Ctrl Key (+60HP, 3 total)',
                '[Pause] P Key',
                '[Return to Menu] ESC Key',
                '',
                '— Lock System —',
                'Soft Lock: Auto-aim nearest enemy',
                'Hard Lock: Stay locked on target, C to switch',
                'Manual Lock: Mouse controls aim direction',
            ]
        },
        {
            id: 'hand_weapons', name: 'Hand Weapons', color: '#4169E1',
            items: [
                { name: 'Auto Rifle', demoId: 'weapons:gun', color: '#4169E1', lines: [
                    'Damage 8/shot | Fire Rate 5/sec',
                    'Magazine 30 | Reload 2s',
                    'Predictive Aim: leads target based on velocity',
                ]},
                { name: 'Beam Saber', demoId: 'weapons:sword', color: '#ff6b6b', lines: [
                    'Damage 50 | 120° arc range',
                    'Cooldown 4.8s',
                    'Dash Push: auto-dash to distant targets',
                ]},
                { name: 'Laser Spear', demoId: 'weapons:laser_spear', color: '#00FFFF', lines: [
                    'Damage 25 | Charge distance 400px',
                    'Charge speed 40 | Cooldown 5s',
                    'Can impale enemies and carry them along',
                ]},
                { name: 'Laser Rifle', demoId: 'weapons:laser_rifle', color: '#FF4444', lines: [
                    'Damage 18 | 1s charge before firing',
                    'Fire interval 0.7s | Infinite range',
                    'Overheat system: +50 heat/shot, ≥200 overheat',
                    'Forced 7s cooldown when overheated',
                ]},
                { name: 'Laser SMG', demoId: 'weapons:laser_smg', color: '#FF8866', lines: [
                    'Damage 6/shot | Snap charge (0.12s) | Fire interval 0.18s',
                    'Low heat per shot (+14): ~14 taps before overheat',
                    'Forced 7s cooldown when overheated',
                    'Rapid laser variant — chases mobile targets',
                ]},
                { name: 'Cluster Missile', demoId: 'weapons:cluster_missile', color: '#FFD700', lines: [
                    'Fires 1 mother missile, continuous tracking (8s self-destruct)',
                    'Splits into 8 sub-missiles when near the LOCKED target',
                    'Sub-missile DMG 4 | High tracking | 4s CD',
                    'Fan spread after split, then guided',
                ]},
                { name: 'Shotgun', demoId: 'weapons:shotgun', color: '#ff9040', lines: [
                    'DMG 8 × 12 pellets | 22° cone spread',
                    'Damage falls off with distance | 20% at max range',
                    'Range 700px | Fire interval 0.7s',
                    'Magazine 6 | Reload 1.6s',
                    'Devastating at point blank',
                ]},
                { name: 'Rocket Launcher', demoId: 'weapons:rocket', color: '#ff7030', lines: [
                    'DMG 30 | Blast radius 180px | Strong center, 5% edge',
                    'Quadratic falloff | Range 900px',
                    'Fire interval 1.1s | Single-shot tube | Reload 2.6s',
                    'Heavy AoE, devastating on direct hits',
                ]},
                { name: 'Minigun', demoId: 'weapons:minigun', color: '#d4a040', lines: [
                    '200-round belt | ~2× rifle DMG up close',
                    'Falloff to 30% at max range | Reload 45s',
                    'Brief spin-up before fire | Massive sustained DPS',
                ]},
                { name: 'Flamethrower', demoId: 'weapons:flamethrower', color: '#FF6020', lines: [
                    'Hold to spew a 30° flame cone | Range 240',
                    'Tick DMG 4 every 110ms (~36 DPS)',
                    'Damage falloff: muzzle 100% → tip 50%',
                    'Heat-limited: ~1.4s sustained fire then must cool',
                ]},
            ]
        },
        {
            id: 'shoulder_weapons', name: 'Shoulder Weapons', color: '#FF8800',
            items: [
                { name: 'Missile Launcher ×15', demoId: 'shoulder:missile', color: '#FFD700', lines: [
                    '15 missiles per salvo | 5 DMG each',
                    '1.1s strong homing | 80px blast radius',
                    'Cooldown 4s',
                ]},
                { name: 'High-Track Missile', demoId: 'shoulder:high_track', color: '#FF8030', lines: [
                    'Single-shot salvo | 80px blast radius',
                    'Damage 25 (~5× standard missile)',
                    '800px guidance radius, strong-tracking 2.8s',
                    'Missile speed 30% faster than standard',
                    'Cooldown 4s',
                ]},
                { name: 'Cluster Bomblet Missile', demoId: 'shoulder:cluster_bomb', color: '#FFA040', lines: [
                    'Body damage 1, begins dispersing 1s after launch',
                    'Drops 10 bomblets over 4s, alternating L30°/R45°',
                    'Bomblet damage 8 (high homing)',
                    'Body is invulnerable while dispersing',
                    'Cooldown 4s',
                ]},
                { name: 'Mine-Layer Missile', demoId: 'shoulder:mine_layer', color: '#FF6040', lines: [
                    'Body damage 1, drops a HE mine every 0.7s in flight',
                    'Mine damage 30 (enemies only — never harms player)',
                    'Distinct hex appearance, always visible to player',
                    'Body is invulnerable until at least one mine deploys',
                    'Cooldown 4s',
                ]},
                { name: 'Det-Cord Missile', demoId: 'shoulder:det_cord', color: '#FFB060', lines: [
                    'Warhead damage 12; ignites a det-cord on detonation',
                    'Cord chain-explodes (AoE) along the entire flight path',
                    'Per-node damage 17 (2/3 of original warhead)',
                    'Chain detonation 4× faster than baseline',
                    'Cooldown 12s (slow reload)',
                ]},
                { name: 'Laser Turret', demoId: 'shoulder:laser_turret', color: '#88E0FF', lines: [
                    'Plants a stationary laser turret at the player\'s position',
                    'Lifetime 12s, auto-targets nearest enemy in 600 range',
                    'Fires a 0.4s laser pulse every 1s, 8 damage per pulse',
                    '2-shot magazine, full reload 8s',
                    'Turret cannot be targeted/devoured; blinks before expiring',
                ]},
                { name: 'CIWS', demoId: 'shoulder:ciws', color: '#00FF88', lines: [
                    'Full-auto 30 rounds/sec | 30 round mag',
                    'Priority: Missiles > Crescents > Reversed > Mines > Enemies',
                    'One-shot kill on guided weapons',
                    '40% chance to hit enemy body',
                ]},
                { name: 'Plasma Missile ×6', demoId: 'shoulder:plasma', color: '#00FFCC', lines: [
                    '6 rapid-fire | Proximity fuse (55px trigger)',
                    'Creates plasma field: 1s duration, 3 DMG per 0.25s',
                    'Multiple fields stack | Cooldown 5s',
                ]},
                { name: 'Super Missile', demoId: 'shoulder:super', color: '#FF0000', lines: [
                    'Damage 100 | Occupies both shoulder slots',
                    '400px blast radius | 4.1s super homing',
                    'Single use per battle',
                ]},
                { name: 'Moonlight Greatsword', demoId: 'shoulder:moonlight', color: '#88CCFF', lines: [
                    'Damage 200 | Occupies R-Hand + Both Shoulders + Ability (4 slots)',
                    'Blade length 7× Beam Saber (1050px)',
                    '±90° sweep (180° total) | 1s sweep time',
                    'Cannot one-shot bosses (min 1 HP)',
                    'Single use per battle',
                ]},
            ]
        },
        {
            id: 'hidden', name: 'Hidden Abilities', color: '#00FFFF',
            items: [
                { name: 'Pulse Parry', demoId: 'hidden:pulse_shield', color: '#00FFFF', lines: [
                    '0.2s parry window | Reflects every damage type',
                    'Cooldown 1s',
                ]},
                { name: 'EMP', demoId: 'hidden:emp', color: '#66CCFF', lines: [
                    'Range 490px | Max damage 100',
                    'Damage falls off with distance | 2s stagger',
                    'Cooldown 18s',
                ]},
                { name: 'Counter Strike', demoId: 'hidden:counter', color: '#FF8C00', lines: [
                    '3s duration | 40% damage reduction',
                    'Reflects 250% of damage taken to nearest enemy',
                    'Cooldown 15s',
                ]},
                { name: 'Decoy Clone', demoId: 'hidden:decoy', color: '#4488FF', lines: [
                    'Deploys 3 holographic decoys (triangle formation)',
                    'Decoy 40HP | Max 7s lifetime',
                    'Player becomes untargetable for 4s',
                    'Enemy AI/missiles/bullets redirect to decoys',
                    'Cooldown 35s',
                ]},
                { name: 'Overdrive Burst', demoId: 'hidden:overdrive', color: '#FF2030', lines: [
                    'On activation: lose 30% of current HP',
                    'For 6s: outgoing damage x3 | move speed x3',
                    'Mech turns crimson | leaves afterimage trail',
                    'Drawback: incoming damage amplified to x2',
                    'Cooldown 30s',
                ]},
                { name: 'Repair Protocol', demoId: 'hidden:repair', color: '#60FF90', lines: [
                    'Resets banked overflow shield on activation',
                    'For 5s: move speed x1.5 | regen 5 HP/s',
                    'Cannot fire weapons or dodge while active',
                    'Surplus regen converts to overflow shield, up to +50',
                    'Cooldown 35s',
                ]},
                { name: 'God Mode (Debug)', demoId: 'hidden:godmode', color: '#FFD700', lines: [
                    '[Debug ability — no VFX]',
                    'Insta-kills every unit on the field',
                    'No cooldown, can be spammed at will',
                ]},
            ]
        },
        {
            id: 'bosses', name: 'Boss Guide', color: '#FF4444',
            items: [
                { name: 'Crimson King', demoId: 'boss:CRIMSON_KING', color: '#8B0000', lines: [
                    'HP 300 | Missile Barrage Type',
                    '',
                    '— Attacks —',
                    'Salvo: 60 standard missiles, 4-direction rotation, 6 DMG each',
                    'Homing: 6 amber-colored seekers, 12 DMG each (1600px guidance)',
                    'Plasma Square: 3 large plasma orbs from each of 4 sides — leave hostile plasma fields on hit',
                    'Grid Barrage: 4 vertical + 3 horizontal beams, weave through gaps',
                    '',
                    '— Special Mechanics —',
                    'Cumulative DR: more hits in 1s = higher reduction',
                    'Missile dodge: 80% evasion when tracked',
                    'Regen: 45% chance to heal 6-20 HP every 3s',
                    '',
                    '— Tips —',
                    'CIWS to intercept missiles, combine with melee',
                    'Avoid burst damage to prevent high DR',
                ]},
                { name: 'Sublime Moon', demoId: 'boss:SUBLIME_MOON', color: '#4682B4', lines: [
                    'HP 200 | High-Mobility Assassin Type',
                    '',
                    '— Attacks —',
                    'Crescent tracking shots: multiple firing patterns (volley/fan/spiral)',
                    'Spin slash: triggered when player gets close, applies a slow debuff',
                    'Missile guard: detonates incoming missiles with spin slash',
                    'Frost clones: summons clones that periodically fire homing ice shots',
                    '',
                    '— Special Mechanics —',
                    'Frequent teleport: prefers blinks over walking, often appears behind you',
                    'Laser Rifle resistance: takes 80% reduced damage from Laser Rifle',
                    'Extreme missile evasion: 90% dodge chance vs guided weapons',
                    '',
                    '— Tips —',
                    'CIWS to intercept crescents and ice shots',
                    'Avoid relying on Laser Rifle / homing missiles',
                    'Stay mid-close range, burst with Shotgun / Rocket Launcher',
                ]},
                { name: 'Star Devourer', demoId: 'boss:STAR_DEVOURER', color: '#333333', lines: [
                    'HP 300 | Tactical Suppression Type',
                    '',
                    '— Attacks —',
                    'Beam rifle: 25 DMG + 0.7s stagger',
                    'Auto rifle: close range 6 DMG/shot, 30 rps',
                    'Floating guns ×3: 70 HP each, 15 DMG laser + stagger',
                    '',
                    '— Special Mechanics —',
                    'Signal jamming: heavy static noise overlays the screen, cannot switch lock',
                    'Phase 2 (≤80 HP): cloaked (visible within 200px)',
                    'Missile reversal: 75% of player missiles turned against you',
                    '',
                    '— Tips —',
                    'Destroy floating guns first; CIWS intercepts reversed missiles',
                    'Keep moving while jammed; Phase 2 requires close combat',
                ]},
                { name: 'Ugly Emperor', demoId: 'boss:UGLY_EMPEROR', color: '#8B4513', lines: [
                    'HP 250 | Area Control Type',
                    '',
                    '— Attacks —',
                    'Chaos barrage: 8/wave, 4 DMG each',
                    'Distortion aura: 80px radius persistent damage field',
                    'Mines (Phase 1): 15 DMG on detonation',
                    'Molotov (Phase 2): creates burning area',
                    '',
                    '— Special Mechanics —',
                    'Phase 1: Immune to missile damage',
                    'Phase 2 (≤100 HP): Only takes missile DMG, ×2 multiplier',
                    'Chaos teleport: teleports near player every 8s',
                    '',
                    '— Tips —',
                    'Phase 1: use rifle/laser/melee; CIWS clears mines',
                    'Phase 2: full missile assault (double damage)',
                    'Two phases require completely different weapon strategies',
                ]},
                { name: 'Magnus, Mech Executive', demoId: 'boss:MAGNUS_EXEC', color: '#C68C2A', lines: [
                    'HP 600 | Heavy Suppression Type',
                    '',
                    '— Attacks —',
                    'Main cannon barrage: high-velocity solid shells',
                    'Orbital bombardment: telegraphed AoE strikes that lock down zones',
                    'Shoulder turrets ×2: 80 HP each, independent targeting',
                    'Detached pods fire homing rockets — only the pods, not the body',
                    '',
                    '— Threshold Shield —',
                    'Shield pool: 50% of total HP',
                    '≤40 single hit: fully absorbed, 0 hull damage',
                    '40~200 single hit: nonlinear partial reduction (more = less reduction)',
                    '>200 single hit: 100% hull damage, shield loses 2× the hit',
                    'After break: 70s respawn cooldown (25% chance to early-rebuild in 1.2s)',
                    '',
                    '— Tips —',
                    'High-burst weapons (Moonlight Greatsword / Super Missile) crack the shield',
                    'Small chip damage is eaten by the shield — break it before pouring DPS',
                    'Take down shoulder turrets first, then push the body',
                    'Use CIWS to pop the rockets fired by detached pods',
                ]},
                { name: 'Hive Mind', demoId: 'boss:HIVE_MIND', color: '#9C27B0', lines: [
                    'HP 320 (Queen) | Multi-body Coordination Type',
                    '',
                    '— Attacks —',
                    'Purple plasma barrage: high-frequency volleys',
                    'Drone swarm: up to 50 units, +4 every 0.5s',
                    '  · Defenders: intercept player attacks and guided weapons',
                    '  · Attackers: orbit & strafe the player with plasma fire',
                    'Drones have 10 HP and are replaced almost immediately',
                    'Splinters (Phase 2): 4× 80 HP shards, plasma sniper shots',
                    'Each splinter spawns its own mini-swarm (cap 12, 1/4 rate)',
                    '',
                    '— Special Mechanics —',
                    'Drones cannot be hard-locked but actively block all incoming attacks',
                    'Queen is mostly untouchable; only briefly exposed when swarm is suppressed',
                    'Splinter phase: queen enters ghost mode (invisible & untargetable)',
                    'Splinters repel each other and flee from the player — hard to clean up at once',
                    '',
                    '— Tips —',
                    'AoE weapons (Shotgun / Rocket / EMP) thin the swarm fast',
                    'Burst the queen during her exposed window',
                    'In splinter phase, focus the splinter that pressures you the most',
                ]},
                { name: 'Yukikon, the Silent Edge', demoId: 'boss:YUKIKON', color: '#7fc8ff', lines: [
                    'HP 150 | High-Mobility Melee Duelist',
                    '',
                    '— Attacks —',
                    'Flash Strike: blink-in slash with minimal wind-up',
                    'SMG Burst: mid-range autofire',
                    'Sword Rain: plants several swords that detonate as projectiles',
                    'Shadow Step: leaves shadow clones, swaps places with them',
                    'Iai Charge: curving long-range dash slash (200~520px)',
                    'Always taps SMG rounds while orbiting — never silent',
                    '',
                    '— Special Mechanics —',
                    'Melee Shield: ranged damage reduced to 15% while she\'s mid-swing',
                    '  (Sword / Moonlight / Crescent / Spear bypass it)',
                    'Built-in CIWS: shreds incoming missiles at any range',
                    'Prefers blinks to walking; constantly resets engagement distance',
                    '',
                    '— Tips —',
                    'Trade up close — ranged weapons get gutted by the melee shield',
                    'Watch for her swing windows; that\'s when ranged fizzles',
                    'During shadow phase, wait for the real one to reveal before locking',
                ]},
                { name: 'Proteus, the Shapeshifter', demoId: 'boss:PROTEUS', color: '#a0ffc0', lines: [
                    'HP 360 | Adaptive Shapeshifter',
                    '',
                    '— Three Forms (distance-based) —',
                    'Halberd (close < 350px): thrusts / sweeps / long wave (damage halved)',
                    'Skirmish (mid 350~600px): shotgun blasts, blink, self-heal, EMP, occasional cannon',
                    'Turret (far > 600px): static cannons, arc-fire, CIWS-style point defense',
                    '',
                    '— Reconfigure Window (KEY WEAKNESS) —',
                    'Form swap takes ~0.6s — cannot attack and takes +25% damage',
                    'Force form swaps with positioning to open damage windows',
                    'Auto-cycles forms every 20s anyway',
                    '',
                    '— Threshold Shield (Turret form) —',
                    'Shield pool: 32% of total HP, -80% damage absorbed',
                    'Regen extremely slow (~333s for full), 8s respawn cooldown after break',
                    '35% chance the shield rebuilds 1.2s after being broken',
                    'Forcing a form swap WHILE shield is up triggers a huge AoE shockwave',
                    '',
                    '— Tips —',
                    'Push or kite to force form swaps — burst him during reconfigure',
                    'Crack the turret-form shield with high single-hit weapons',
                    'Don\'t poke into melee while his shield is up — you\'ll eat the shockwave',
                ]},
                { name: 'Elemental Triumvirate + Voidborn', demoId: 'boss:TRIUMVIRATE', color: '#c87cff', lines: [
                    'Three bodies × HP 240 | Kill any 2 → the last becomes Voidborn (HP 200)',
                    '',
                    '— Pyron, the Fire God (close-mid pressure) —',
                    'Heat Lance: stationary multi-layer pillar of flame',
                    'Flamethrower Sweep: long-range tracking cone (range 630px)',
                    '',
                    '— Volthar, the Lightning God (long-range zoner) —',
                    'Magnet Strike: lightning crawls out of his body, snakes toward player',
                    'Iron Spike Ritual: drops multiple mecha-tech pylons across the arena',
                    '  → AoE chained lightning strikes + long stun',
                    '',
                    '— Glacius, the Ice God (long-range slow control) —',
                    'Frost Bolt: triple-shot homing missile, 0 damage but heavy slow',
                    'Frost Nova: self-centered AoE, 1s stagger on hit, leaves slow ice field',
                    '',
                    '— All three —',
                    'Spawn together with independent HP bars',
                    'Auto-spread so they don\'t pile up; reactive sidestep on hit',
                    '',
                    '— Voidborn (after any 2 die) —',
                    'HP 200 | Drifts slowly, doesn\'t actively chase',
                    'Void Devour: ALL ranged projectiles within 240px just disappear',
                    'Void Teleport: stay within 160px for 0.35s and you get yeeted to a far corner',
                    'Blackhole Cannon: salvo of 3 blackhole shots, pulls stack — escape gets harder fast',
                    'Melee resistance: takes 50% reduced damage from Sword / Moonlight',
                    '',
                    '— Tips —',
                    'Kill Glacius first to drop the slows, then Volthar for the spike AoE',
                    'In Voidborn phase melee is the only effective DPS — but don\'t linger',
                    'When multiple blackholes overlap, escape is nearly impossible — pre-empt them',
                ]},
            ]
        },
        {
            id: 'status', name: 'Status Effects', color: '#AAAAAA',
            content: [
                '[Stagger] Briefly unable to move or act',
                '[Burning] 5s duration, 2 DMG per 0.1s, -20% move speed',
                '[Slow] Applied by Sublime Moon spin slash, briefly halves move speed',
                '[Signal Jammed] Star Devourer exclusive: heavy static overlay, cannot switch lock',
                '',
                '— Player Stats —',
                'Health: 150',
                'Move Speed: 20',
                'Repair Kits: 3, each restores 60 HP',
                'Dodge: 0.15s, cooldown 0.35s',
            ]
        },
    ],

    ja: [
        {
            id: 'controls', name: '操作説明', color: '#4488FF',
            content: [
                '【移動】 WASD / 矢印キー',
                '【左手武器】 マウス左ボタン',
                '【右手武器】 マウス右ボタン',
                '【左肩武器】 Q キー',
                '【右肩武器】 E キー',
                '【隠しアビリティ】 Shift キー',
                '【回避】 スペース + 方向キー（0.15秒、CD 0.35秒）',
                '【ロック切替】 F キー（ソフト→ハード→マニュアル）',
                '【ターゲット切替】 C キー（ハードロック時）',
                '【修理キット】 Ctrl キー（+60HP、計3個）',
                '【一時停止】 P キー',
                '【メニューに戻る】 ESC キー',
                '',
                '— ロックシステム —',
                'ソフト：自動で最寄りの敵を狙う',
                'ハード：現在の対象を固定、C で切替',
                'マニュアル：マウスで照準を直接操作',
            ]
        },
        { id: 'hand_weapons', name: '手部武器', color: '#4169E1', items: [
            { name: 'オートライフル', demoId: 'weapons:gun', color: '#4169E1', lines: [
                'ダメージ 8/発 | 連射 5発/秒',
                '弾倉 30発 | リロード 2秒',
                '予測射撃：標的速度から着弾点を予測',
            ]},
            { name: 'ビームサーベル', demoId: 'weapons:sword', color: '#ff6b6b', lines: [
                'ダメージ 50 | 120°扇形範囲',
                'CD 4.8秒',
                'ダッシュ突進：距離が遠い時は自動で接近',
            ]},
            { name: 'レーザーランス', demoId: 'weapons:laser_spear', color: '#00FFFF', lines: [
                'ダメージ 25 | 突進距離 400px',
                '突進速度 40 | CD 5秒',
                '敵を貫きそのまま運ぶことが可能',
            ]},
            { name: 'レーザーライフル', demoId: 'weapons:laser_rifle', color: '#FF4444', lines: [
                'ダメージ 18 | 1秒チャージ後発射',
                '射撃間隔 0.7秒 | 射程無限',
                'オーバーヒート：1発+50熱量、≥200で過熱',
                '過熱後は7秒の強制冷却',
            ]},
            { name: 'レーザーSMG', demoId: 'weapons:laser_smg', color: '#FF8866', lines: [
                'ダメージ 6/発 | チャージ極短(0.12秒) | 射撃間隔 0.18秒',
                '単発熱量低(+14)、約14発で過熱',
                '過熱後は7秒の強制冷却',
                '速射型レーザー、機動目標の追撃に最適',
            ]},
            { name: '分裂ミサイル', demoId: 'weapons:cluster_missile', color: '#FFD700', lines: [
                '母弾1発を発射、持続追尾（8秒で自爆）',
                'ロック対象に近づいた時8発に分裂',
                'サブ弾 ダメージ 4 | 高追尾性 | CD 4秒',
                '分裂後は扇形展開→誘導',
            ]},
            { name: 'ショットガン', demoId: 'weapons:shotgun', color: '#ff9040', lines: [
                'ダメージ 8/弾 × 12発 | 22°円錐拡散',
                '距離で線形減衰 | 最大射程で20%',
                '射程 700px | 射撃間隔 0.7秒',
                '弾倉 6発 | リロード 1.6秒',
                '密着射撃で大爆発',
            ]},
            { name: 'ロケットランチャー', demoId: 'weapons:rocket', color: '#ff7030', lines: [
                'ダメージ 30 | 爆発半径 180px | 中心強・周縁5%',
                '距離の二乗で減衰 | 射程 900px',
                '射撃間隔 1.1秒 | 単発装填 | リロード 2.6秒',
                '直撃で甚大な威力',
            ]},
            { name: 'ミニガン', demoId: 'weapons:minigun', color: '#d4a040', lines: [
                '200発リンク | 単発威力は近距離でライフルの約2倍',
                '最大射程で30%まで減衰 | 装填 45秒',
                'スピンアップ後に発射 | 持続火力は破格',
            ]},
            { name: '火炎放射器', demoId: 'weapons:flamethrower', color: '#FF6020', lines: [
                '長押しで30°炎の円錐を持続噴射 | 射程 240',
                'Tickダメージ 4、110ms毎ヒット（約36 DPS）',
                '距離減衰：銃口100% → 円錐先端50%',
                '過熱制限：連続噴射約1.4秒で上限、冷却必要',
            ]},
        ] },
        { id: 'shoulder_weapons', name: '肩部武器', color: '#FF8800', items: [
            { name: '15連ミサイル発射機', demoId: 'shoulder:missile', color: '#FFD700', lines: [
                '1斉射 15発 | 1発5ダメージ',
                '前1.1秒の強誘導 | 爆発半径 80px',
                'CD 4秒',
            ]},
            { name: '高誘導ミサイル', demoId: 'shoulder:high_track', color: '#FF8030', lines: [
                '単発斉射 | 爆発半径 80px',
                'ダメージ 25（通常ミサイル約5倍）',
                '誘導半径 800px、強誘導持続 2.8秒',
                '弾速は通常より30%高い',
                'CD 4秒',
            ]},
            { name: 'クラスターミサイル', demoId: 'shoulder:cluster_bomb', color: '#FFA040', lines: [
                '本体ダメージ 1、発射1秒後にサブ弾散布開始',
                '4秒間でL30°/R45°交互に計10発投下',
                'サブ弾ダメージ 8（高誘導）',
                '散布中は本体無敵、迎撃・吸収不可',
                'CD 4秒',
            ]},
            { name: '機雷敷設ミサイル', demoId: 'shoulder:mine_layer', color: '#FF6040', lines: [
                '本体ダメージ 1、飛行中0.7秒毎に高威力機雷を敷設',
                '機雷ダメージ 30（敵専用、自機にダメージなし）',
                '醜皇の機雷とは異なる外観、自機からは常時可視',
                '最初の機雷を敷設するまで本体は破壊不可',
                'CD 4秒',
            ]},
            { name: '導爆索ミサイル', demoId: 'shoulder:det_cord', color: '#FFB060', lines: [
                '本体ダメージ 12、命中・自爆で導爆索を起爆',
                '発射点から飛行軌跡に沿って連鎖AOE爆発',
                '各節爆発ダメージ 17（母弾の2/3）',
                '連鎖速度は初期版の4倍',
                'CD 12秒（リロード長め）',
            ]},
            { name: 'レーザータレット', demoId: 'shoulder:laser_turret', color: '#88E0FF', lines: [
                '機体位置にレーザータレットを設置',
                '寿命 12秒、射程 600 内の最寄り敵を自動追尾',
                '1秒毎に0.4秒の短パルス、1発8ダメージ',
                '弾倉 2発、空になると一括リロード 8秒',
                'タレットはロック・吸収不可、消滅前に点滅警告',
            ]},
            { name: 'CIWS', demoId: 'shoulder:ciws', color: '#00FF88', lines: [
                'フルオート 30発/秒 | 弾倉 30発',
                '優先度：ミサイル > 月牙弾 > 反転弾 > 機雷 > 敵',
                '誘導兵器は1発で破壊',
                '敵本体には40%確率でダメージ',
            ]},
            { name: '6連プラズマミサイル', demoId: 'shoulder:plasma', color: '#00FFCC', lines: [
                '6連射 | 近接信管（55pxで起爆）',
                'プラズマ場生成：1秒持続、0.25秒毎3ダメージ',
                '複数のプラズマ場は重複可 | CD 5秒',
            ]},
            { name: 'スーパーミサイル', demoId: 'shoulder:super', color: '#FF0000', lines: [
                'ダメージ 100 | 両肩スロット占有',
                '爆発半径 400px | 超強誘導 4.1秒',
                '1戦に1回のみ',
            ]},
            { name: '月光の大剣', demoId: 'shoulder:moonlight', color: '#88CCFF', lines: [
                'ダメージ 200 | 右手+両肩+隠しの計4スロット占有',
                '光刃長はビームサーベルの7倍（1050px）',
                '機体方向±90°計180°範囲 | 1秒で薙ぎ払い',
                'ボスを即死不可（最低1HP残し）',
                '1戦に1回のみ',
            ]},
        ] },
        { id: 'hidden', name: '隠しアビリティ', color: '#00FFFF', items: [
            { name: 'パルス弾き', demoId: 'hidden:pulse_shield', color: '#00FFFF', lines: [
                '弾き窓 0.2秒 | 全ダメージ反射',
                'CD 1秒',
            ]},
            { name: 'EMP', demoId: 'hidden:emp', color: '#66CCFF', lines: [
                '範囲 490px | 最大ダメージ 100',
                '距離で減衰 | 2秒スタン付与',
                'CD 18秒',
            ]},
            { name: 'カウンター', demoId: 'hidden:counter', color: '#FF8C00', lines: [
                '3秒持続 | 被ダメ 40%軽減',
                '受けたダメージの250%を最寄り敵に反射',
                'CD 15秒',
            ]},
            { name: 'デコイクローン', demoId: 'hidden:decoy', color: '#4488FF', lines: [
                'ホログラフのデコイ3体を放出（正三角配置）',
                'デコイ40HP | 最大7秒生存',
                'プレイヤーは4秒間ロック不可状態',
                '敵AI/ミサイル/弾はデコイを攻撃',
                'CD 35秒',
            ]},
            { name: 'オーバードライブ', demoId: 'hidden:overdrive', color: '#FF2030', lines: [
                '発動時に現在HPの30%を即時喪失',
                '6秒間：ダメージ×3 | 移動速度×3',
                '機体が赤く染まり、ダッシュで残像',
                '代償：被ダメージは×2に増幅',
                'CD 30秒',
            ]},
            { name: 'リペアプロトコル', demoId: 'hidden:repair', color: '#60FF90', lines: [
                '発動時に既存の余剰シールドをリセット',
                '5秒間：移動速度×1.5 | 5HP/秒回復',
                '武器使用と回避は不可',
                'HP満タン後の余剰は最大+50シールドに変換',
                'CD 35秒',
            ]},
            { name: 'ゴッドモード（デバッグ）', demoId: 'hidden:godmode', color: '#FFD700', lines: [
                '【デバッグ用、エフェクトなし】',
                '発動で場の全ユニットを即死',
                'CDなし、自由に使用可',
            ]},
        ] },
        { id: 'bosses', name: 'ボス図鑑', color: '#FF4444', items: [
            { name: '深紅の王', demoId: 'boss:CRIMSON_KING', color: '#8B0000', lines: [
                'HP 300 | ミサイル弾幕型',
                '',
                '— 攻撃手段 —',
                '一斉射撃(salvo)：60発の通常ミサイルを4方向で交互、1発6ダメージ',
                '追尾(homing)：6発の琥珀色強誘導ミサイル、1発12ダメージ（1600px誘導）',
                'プラズマ方陣(square)：4辺各3発の大型プラズマ球、命中後にプラズマ場残置',
                'グリッドビーム：縦4+横3のレーザー網、隙間を縫って回避',
                '',
                '— 特殊機構 —',
                '累積軽減：1秒内の被弾が多いほど軽減UP（リセットなし）',
                'ミサイル回避：追尾された時80%回避',
                'リジェネ：3秒毎45%確率で6-20HP回復',
                '',
                '— 戦術 —',
                'CIWSでミサイル迎撃、近接で削る',
                '短時間集中火力は累積軽減を発動させる',
            ]},
            { name: '氷姫', demoId: 'boss:SUBLIME_MOON', color: '#4682B4', lines: [
                'HP 200 | 高機動アサシン型',
                '',
                '— 攻撃手段 —',
                '月牙追尾弾：複数射撃パターン（一斉/扇形/螺旋）',
                '回旋斬：接近時に発動、減速debuff付加',
                'ミサイル迎撃：迫るミサイルを回旋斬で破壊',
                '氷分身：分身を召喚、間欠的に追尾氷弾を発射',
                '',
                '— 特殊機構 —',
                '高頻度瞬移：歩くより瞬移を選び、玩家の背後に出現',
                'レーザーライフル耐性：レーザーライフル被ダメ80%軽減',
                '極高ミサイル回避：誘導兵器に対し90%回避',
                '',
                '— 戦術 —',
                'CIWSで月牙弾と氷弾を迎撃',
                'レーザーライフル/誘導武器に頼り過ぎない',
                '中近距離維持、ショットガン/ロケットで爆発火力',
            ]},
            { name: '星喰らい', demoId: 'boss:STAR_DEVOURER', color: '#333333', lines: [
                'HP 300 | 戦術制圧型',
                '',
                '— 攻撃手段 —',
                'ビームライフル：25ダメージ+0.7秒スタン',
                'オートライフル：近距離6ダメージ/発、30発/秒',
                'フローティングガン×3：各70HP、レーザー15ダメージ+スタン',
                '',
                '— 特殊機構 —',
                'シグナル妨害：画面が強烈なノイズで覆われ、ロック切替不可',
                '第2段階(≤80HP)：ステルス（200px以内のみ可視）',
                'ミサイル反転：玩家のミサイル75%が反転して襲ってくる',
                '',
                '— 戦術 —',
                'フローティングガン優先撃破、CIWSで反転弾迎撃',
                'シグナル妨害中は感覚で動き続け、第2段階は近距離戦',
            ]},
            { name: '醜皇', demoId: 'boss:UGLY_EMPEROR', color: '#8B4513', lines: [
                'HP 250 | エリアコントロール型',
                '',
                '— 攻撃手段 —',
                'カオス弾幕：8発/波、4ダメージ/発',
                '歪曲オーラ：半径80pxの持続ダメージ場',
                '機雷(第1段階)：起爆15ダメージ',
                '火炎瓶(第2段階)：燃焼区域生成',
                '',
                '— 特殊機構 —',
                '第1段階：ミサイルダメージ無効',
                '第2段階(≤100HP)：ミサイルダメージのみ受ける、×2倍率',
                'カオス瞬移：8秒毎に玩家近くへ瞬移',
                '',
                '— 戦術 —',
                '第1段階はライフル/レーザー/近接、CIWSで機雷掃除',
                '第2段階は全力ミサイル攻撃（ダメージ2倍）',
                '段階毎に全く異なる武装戦略が必要',
            ]},
            { name: 'メカ執政官 マグナス', demoId: 'boss:MAGNUS_EXEC', color: '#C68C2A', lines: [
                'HP 600 | 重装制圧型',
                '',
                '— 攻撃手段 —',
                '主砲一斉射撃：高速実弾弾幕',
                '軌道砲撃：予告された範囲を制圧するAOE打撃',
                '肩載砲塔×2：各80HP、独立追尾',
                '蜉蝣砲台：分離した肩砲塔だけが追尾ロケットを発射（本体は撃たない）',
                '',
                '— 閾値シールド —',
                'シールド上限：総HPの50%',
                '≤40の単発：完全吸収（HPダメージ0）',
                '40~200の単発：非線形軽減（高いほど軽減低下）',
                '>200の単発：100%本体に貫通、シールド消費×2',
                '破壊後70秒で再生（25%確率で1.2秒の早期再生）',
                '',
                '— 戦術 —',
                '高単発武器（月光大剣/スーパーミサイル）でシールド一撃破壊',
                '小ダメージ連射はシールドに吸われる、まず破壊してから本体へ',
                '肩砲塔を先に破壊し、本体を制圧',
                'CIWSで分離砲台のロケットを迎撃',
            ]},
            { name: 'ハイブマインド', demoId: 'boss:HIVE_MIND', color: '#9C27B0', lines: [
                'HP 320 (本体) | 多体協調型',
                '',
                '— 攻撃手段 —',
                '紫プラズマ弾幕：高頻度斉射',
                'ドローン群：上限50体、0.5秒毎に最大4体補充',
                '  · 防御型：玩家の攻撃と誘導兵器を迎撃',
                '  · 攻撃型：女王を周回し玩家を急襲',
                'ドローン10HP、撃墜直後に補充',
                '残識(第2段階)：4体80HPの残識、紫プラズマ狙撃',
                '残識それぞれ上限12の小型群を召喚（1/4速度）',
                '',
                '— 特殊機構 —',
                'ドローンはロック不可だが攻撃を能動的に妨害',
                '本体はほぼ届かず、群が制圧された短時間のみ露出',
                '残識形態：女王はゴーストモード（不可視・ロック不可）',
                '残識同士は反発、玩家から逃避、一斉掃討困難',
                '',
                '— 戦術 —',
                'ショットガン/ロケット/EMPなどAOEで群を一掃',
                '女王の露出窓を狙い集中爆発',
                '残識フェーズは脅威の高い1体に集中',
            ]},
            { name: '剣舞 雪魂 (Yukikon)', demoId: 'boss:YUKIKON', color: '#7fc8ff', lines: [
                'HP 150 | 高速近接決闘者',
                '',
                '— 攻撃手段 —',
                '閃斬(flashStrike)：抬手極短の瞬移突進斬',
                'SMGバースト(smgBurst)：中距離マシンガン掃射',
                '剣の雨(swordRain)：複数の剣を地面に挿し、起動して飛弾化',
                '影分身(shadowStep)：分身と入れ替わりロックを撹乱',
                '居合突進(iaiCharge)：200~520pxの距離を取り弧を描く居合',
                '常にSMG点射しながら遊撃、決して"静か"にならない',
                '',
                '— 特殊機構 —',
                '近接シールド：振りの間は遠距離ダメージを15%に軽減（剣/光刃/月牙は無効化されない）',
                '内蔵CIWS：誘導兵器を高速迎撃、距離無視',
                '歩くより瞬移を好み、頻繁に距離をリセット',
                '',
                '— 戦術 —',
                '近接で殴り合い、遠距離は大幅に削がれる',
                '振りの瞬間に注意、その数フレームは遠距離ほぼ無効',
                '影分身フェーズは焦らず本物が出るまで待機',
            ]},
            { name: '可変メカ プロテウス (Proteus)', demoId: 'boss:PROTEUS', color: '#a0ffc0', lines: [
                'HP 360 | 形態切替型',
                '',
                '— 三形態（距離で切替）—',
                '長戟形態(近接 < 350px)：突き / 横薙ぎ / 長距離波動 (ダメージ50%減)',
                '遊撃形態(中距離 350~600px)：散弾爆破、ブリンク、自己回復、EMP、稀にレーザー砲',
                '砲台形態(遠距離 > 600px)：据置砲塔の弧射撃 + 誘導兵器迎撃CIWS',
                '',
                '— 再構成（重要弱点）—',
                '形態切替は約0.6秒、その間攻撃不可+25%被ダメ',
                '形態切替を強制すればダメージ窓を開ける',
                '20秒毎に自動で循環切替',
                '',
                '— 閾値シールド (砲台形態) —',
                'シールド上限：総HPの32%、ダメージ-80%',
                '回復極遅(満盾約333秒)、破壊後8秒CDで再生',
                '破壊時35%確率で1.2秒後に再生',
                'シールド有効時に強制切替されると大範囲AOE衝撃波を放つ',
                '',
                '— 戦術 —',
                '近接/遠距離を頻繁に切替し再構成を強制、再構成中に集中砲火',
                '砲台形態のシールド破壊は大単発武器、低ダメ連射は吸収される',
                'シールド有効時に密着で形態切替を強制しない（衝撃波で反撃される）',
            ]},
            { name: '元素三主神 + ヴォイド', demoId: 'boss:TRIUMVIRATE', color: '#c87cff', lines: [
                '本体3体 各HP 240 | 2体撃破で残り1体がヴォイド化(HP 200)',
                '',
                '— 火神 Pyron（中近距離制圧）—',
                'ヒートランス：原地に多層粒子の火柱を生成',
                '火炎放射スイープ：長距離追尾の炎の円錐（射程 630px）',
                '',
                '— 雷神 Volthar（遠距離吊り）—',
                '磁吸閃電：本体から発し、屈曲しながら玩家を追う',
                '鉄杭儀式：戦場に複数のメカ式鉄杭を設置',
                '  → AOE雷撃と長スタンを誘導',
                '',
                '— 冰神 Glacius（遠距離減速制御）—',
                'フロストボルト：3連追尾弾、0ダメージだが重度減速',
                'フロストノヴァ：自身中心AOE、命中で1秒スタン、減速氷場残置',
                '',
                '— 三本体共通 —',
                '同時出場、独立HPバー、自動的に距離をとり"団子"を回避',
                '被弾時に横歩きで反応回避(reactive sidestep)',
                '',
                '— ヴォイド (2体撃破後出現) —',
                'HP 200 | ゆっくり浮遊、玩家を能動追尾しない',
                'ヴォイド吸収：240px以内の遠距離弾薬は全て消失',
                'ヴォイド瞬移：160px以内に0.35秒留まると遠隅へ瞬移される',
                'ブラックホール砲：3発の黒洞弾を一斉射、引力場は無限累積',
                '近接耐性 50%（剣/光刃/月光のダメージ半減）',
                '',
                '— 戦術 —',
                '冰神を最初に撃破し減速を排除、次に雷神で杭AOEを回避',
                'ヴォイドフェーズは近接が唯一の有効DPS、ただし瞬移に注意',
                'ブラックホール累積時はほぼ脱出不可、事前位置取りで予防',
            ]},
        ] },
        {
            id: 'status', name: '状態異常', color: '#AAAAAA',
            content: [
                '【スタン】 短時間移動・行動不能',
                '【燃焼】 5秒間、0.1秒毎に2ダメージ、移動-20%',
                '【スロウ】 氷姫の回旋斬付与、短時間で大幅減速',
                '【シグナル妨害】 星喰らい専用、画面ノイズ覆われロック切替不可',
                '',
                '— プレイヤーステータス —',
                'HP：150',
                '移動速度：20',
                '修理キット：3個、各60HP回復',
                '回避：0.15秒、CD 0.35秒',
            ]
        },
    ]
};
