function t(key, ...args) {
    const lang = (typeof gameState !== 'undefined' && gameState.language) || 'zh';
    const str = translations[lang] && translations[lang][key];
    if (str === undefined) return key;
    if (args.length === 0) return str;
    return str.replace(/\{(\d+)\}/g, (match, index) => {
        const i = parseInt(index);
        return i < args.length ? args[i] : match;
    });
}

function getLocalizedGuideData() {
    const lang = (typeof gameState !== 'undefined' && gameState.language) || 'zh';
    return guideData[lang] || guideData.zh;
}

const translations = {
    zh: {
        'menu.startBoss': '开始 Boss 战',
        'menu.startBossDesc': '挑战强大的Boss敌人',
        'menu.customizeMech': '定制机甲',
        'menu.customizeDesc': '配置武器装备，自定义作战风格',
        'menu.guide': '游戏简介',
        'menu.selectLevel': '选择关卡',
        'menu.bossModeSub': 'Boss战模式 - 挑战强大的敌人',
        'menu.difficulty': '难度: ',
        'menu.locked': '🔒 未解锁',
        'menu.back': '返回',
        'menu.backArrow': '← 返回',
        'menu.mainMenu': '主菜单',
        'menu.backToMenu': '返回主菜单',
        'menu.backToCatalog': '返回目录',
        'menu.backTo': '返回{0}',

        'cfg.selected': '已选择：{0}',
        'cfg.leftHand': '左手武器',
        'cfg.rightHand': '右手武器',
        'cfg.leftShoulder': '左肩武器',
        'cfg.rightShoulder': '右肩武器',
        'cfg.hiddenAbility': '隐藏机能',
        'cfg.leftKey': '(左键)',
        'cfg.rightKey': '(右键)',
        'cfg.qKey': '(Q键)',
        'cfg.eKey': '(E键)',
        'cfg.shiftKey': '(Shift键)',
        'cfg.none': '无',
        'cfg.currentConfig': '当前配置：',
        'cfg.invincibleOn': '无敌模式：开启',
        'cfg.invincibleOff': '无敌模式：关闭',
        'cfg.startGame': '开始游戏',
        'cfg.configHint': '点击武器槽位选择武器，然后点击开始游戏',
        'cfg.customHint': '点击武器槽位选择武器，然后返回主菜单',

        'hud.mech': '机甲: {0}',
        'hud.health': '❤️ 生命值: ',
        'hud.invincible': '⭐ 无敌模式 ⭐',
        'hud.leftKey': '🖊️ 左键 - ',
        'hud.rightKey': '🖐️ 右键 - ',
        'hud.dodgeKey': '⚡ 空格 - ',
        'hud.dodge': '闪避: {0}',
        'hud.lockKey': '🎯 F键 - ',
        'hud.lockMode': '锁定模式: {0}',
        'hud.shiftKey': '🛡️ Shift键 - ',
        'hud.noWeapon': '无武器',
        'hud.noHidden': '无隐藏机能',
        'hud.dodgeLimit': '闪避限制',
        'hud.cKey': '🔄 C键 - ',
        'hud.switchTarget': '切换目标',
        'hud.qKey': '🚀 Q键 - ',
        'hud.eKey': '🚀 E键 - ',
        'hud.noLeftShoulder': '无左肩武器',
        'hud.noRightShoulder': '无右肩武器',
        'hud.ctrlKey': '🛠️ Ctrl键 - ',
        'hud.repairKit': '维修包: {0}/{1}',
        'hud.repairEmpty': '维修包: 已用完',
        'hud.mode': '模式: {0}',
        'hud.bossKills': 'Boss击杀数: {0}',

        'enemy.elite': '精英',

        'ui.paused': '游戏暂停',
        'ui.pauseHint': '按 P 继续游戏',
        'ui.pauseBtn': '暂停',
        'ui.gameOver': '游戏结束',
        'ui.totalDamage': '造成总伤害: {0}',
        'ui.spaceReturn': '按空格键返回主菜单',
        'ui.victory': '🎉 胜利！🎉',
        'ui.defeated': '击败了 {0}！',
        'ui.finalScore': '最终分数: {0}',
        'ui.blindStatus': '失明状态',
        'ui.blindRemaining': '剩余时间: {0}秒',
        'ui.langToggle': 'EN',
        'ui.gameTitle': '机甲战斗游戏',

        'boss.CRIMSON_KING': '血红之王',
        'boss.SUBLIME_MOON': '冰之姬',
        'boss.STAR_DEVOURER': '噬星者',
        'boss.UGLY_EMPEROR': '丑皇',
        'boss.unknown': '未知Boss',
        'bossDesc.CRIMSON_KING': '深红色的恐怖统治者，掌控着黑暗的力量',
        'bossDesc.SUBLIME_MOON': '青蓝色的神秘支配者，散发着冰冷的月光之力',
        'bossDesc.STAR_DEVOURER': '黑白相间的虚无毁灭者，吞噬一切光明与黑暗',
        'bossDesc.UGLY_EMPEROR': '丑陋扭曲的混沌统治者，掌控着扭曲与混乱的力量',

        'boss.pierce': '扎穿!',
        'boss.blind': '失明',
        'boss.immune': '免疫',
        'boss.clone': '分身',
        'boss.burn': '燃烧',

        'boss.blindActive': '失明激活中 {0}s',
        'boss.blindUnlockNeed': '失明技能解锁: 还需 {0} 伤害',
        'boss.blindUnlocked': '失明技能已解锁',
        'boss.blindCooldown': '失明冷却中 {0}s {1}',
        'boss.blindReady': '失明技能准备就绪 {0}',
        'boss.phase1': '(一阶段)',
        'boss.phase2label': '(二阶段)',
        'boss.phase2Visible': '二阶段 - 距离 {0}/{1} - 可见可锁定',
        'boss.phase2Cloaked': '二阶段 - 距离 {0}/{1} - 隐身状态',
        'boss.phase2Trigger': '二阶段触发: 还需 {0} 伤害',

        'mode.BOSS_BATTLE': 'Boss战模式',
        'modeDesc.BOSS_BATTLE': '挑战强大的Boss敌人',
        'mech.HYBRID': '混合机甲',

        'weapon.gun': '自动步枪',
        'weapon.sword': '脉冲光束军刀',
        'weapon.laser_spear': '镭射长枪',
        'weapon.cluster_missile': '分裂飞弹',
        'weapon.laser_rifle': '镭射步枪',
        'weapon.missile_launcher': '15连导弹发射器',
        'weapon.ciws': '近防炮',
        'weapon.plasma_missile': '6连电浆飞弹',
        'weapon.super_weapon': '超级导弹',
        'weapon.moonlight_greatsword': '月光大剑',
        'weapon.pulse_shield': '脉冲护盾',
        'weapon.emp': 'EMP电磁脉冲',
        'weapon.counter_mech': '反制重击',
        'weapon.decoy_clone': '诱饵分身',

        'weaponDesc.gun': '远程射击 | 高射速 | 预瞄功能',
        'weaponDesc.sword': '近战攻击 | 高伤害 | 刀推功能',
        'weaponDesc.laser_spear': '中距离突刺 | 蓄力攻击 | 推进功能',
        'weaponDesc.cluster_missile': '大弹近炸分裂8子弹 | 持续索敌 | 高追踪',
        'weaponDesc.laser_rifle': '长按蓄力 | 预瞄射线 | 过热系统',
        'weaponDesc.missile_launcher': '强追踪1.1秒 | 范围爆炸 | 高伤害',
        'weaponDesc.ciws': '自动拦截制导武器 | 30发弹仓 | 优先打导弹',
        'weaponDesc.plasma_missile': '近炸引信 | 电浆场持续伤害 | 可叠加',
        'weaponDesc.super_weapon': '100伤害 | 一次战斗只能用一次 | 占用双槽位',
        'weaponDesc.moonlight_greatsword': '200伤害 | 超大范围光刃 | 占用4槽位 | 一次性',
        'weaponDesc.pulse_shield': '70%伤害减免 | 15秒持续 | 40秒冷却',
        'weaponDesc.emp': '范围伤害+僵直 | 距离越远伤害越低 | 30秒冷却',
        'weaponDesc.counter_mech': '3秒减伤40% | 反射50%伤害 | 15秒冷却',
        'weaponDesc.decoy_clone': '释放3诱饵 | 4秒隐身 | 35秒冷却',

        'ws.attacking': '攻击中...',
        'ws.stagger': '僵直: {0}秒',
        'ws.dashPush': '刀推中...',
        'ws.cooldown': '冷却: {0}秒',
        'ws.cooldownS': '冷却: {0}s',
        'ws.ready': '准备就绪',
        'ws.readyShort': '就绪',
        'ws.reloading': '重装中...',
        'ws.ammoEmpty': '弹药耗尽！自动重装',
        'ws.ammo': '弹药: {0}/{1}',
        'ws.pressR': ' | 按R重装',
        'ws.overheat': '过热! {0}s',
        'ws.charging': '蓄力中 {0}%',
        'ws.coolingDown': '冷却中...',
        'ws.heat': '热量: {0}/{1}',
        'ws.rushing': '冲锋中！',
        'ws.recovering': '恢复中',
        'ws.launching': '发射中... ({0}枚)',
        'ws.launchingSimple': '发射中...',
        'ws.shielding': '护盾中: {0}秒',
        'ws.countering': '反制中: {0}s',
        'ws.stealth': '隐身中: {0}s',
        'ws.slashing': '斩击中...',
        'ws.used': '已使用',
        'ws.cooldownRemaining': '冷却中 {0}s',

        'player.dodging': '闪避中...',
        'player.dodgeCooldown': '闪避冷却: {0}秒',
        'player.dodgeReady': '闪避就绪',
        'player.softLock': '软锁',
        'player.hardLock': '硬锁',
        'player.manualLock': '手动锁',
    },

    en: {
        'menu.startBoss': 'Start Boss Battle',
        'menu.startBossDesc': 'Challenge powerful bosses',
        'menu.customizeMech': 'Customize Mech',
        'menu.customizeDesc': 'Configure weapons & combat style',
        'menu.guide': 'Game Guide',
        'menu.selectLevel': 'Select Level',
        'menu.bossModeSub': 'Boss Battle - Challenge powerful bosses',
        'menu.difficulty': 'Difficulty: ',
        'menu.locked': '🔒 Locked',
        'menu.back': 'Back',
        'menu.backArrow': '← Back',
        'menu.mainMenu': 'Main Menu',
        'menu.backToMenu': 'Return to Menu',
        'menu.backToCatalog': 'Back to Catalog',
        'menu.backTo': 'Back to {0}',

        'cfg.selected': 'Selected: {0}',
        'cfg.leftHand': 'Left Hand',
        'cfg.rightHand': 'Right Hand',
        'cfg.leftShoulder': 'Left Shoulder',
        'cfg.rightShoulder': 'Right Shoulder',
        'cfg.hiddenAbility': 'Hidden Ability',
        'cfg.leftKey': '(LMB)',
        'cfg.rightKey': '(RMB)',
        'cfg.qKey': '(Q)',
        'cfg.eKey': '(E)',
        'cfg.shiftKey': '(Shift)',
        'cfg.none': 'None',
        'cfg.currentConfig': 'Current Config:',
        'cfg.invincibleOn': 'Invincible: ON',
        'cfg.invincibleOff': 'Invincible: OFF',
        'cfg.startGame': 'Start Game',
        'cfg.configHint': 'Click weapon slots to configure, then Start Game',
        'cfg.customHint': 'Click weapon slots to configure, then return to menu',

        'hud.mech': 'Mech: {0}',
        'hud.health': '❤️ HP: ',
        'hud.invincible': '⭐ Invincible ⭐',
        'hud.leftKey': '🖊️ LMB - ',
        'hud.rightKey': '🖐️ RMB - ',
        'hud.dodgeKey': '⚡ Space - ',
        'hud.dodge': 'Dodge: {0}',
        'hud.lockKey': '🎯 F - ',
        'hud.lockMode': 'Lock: {0}',
        'hud.shiftKey': '🛡️ Shift - ',
        'hud.noWeapon': 'No Weapon',
        'hud.noHidden': 'No Ability',
        'hud.dodgeLimit': 'Dodge Lock',
        'hud.cKey': '🔄 C - ',
        'hud.switchTarget': 'Switch Target',
        'hud.qKey': '🚀 Q - ',
        'hud.eKey': '🚀 E - ',
        'hud.noLeftShoulder': 'No L-Shoulder',
        'hud.noRightShoulder': 'No R-Shoulder',
        'hud.ctrlKey': '🛠️ Ctrl - ',
        'hud.repairKit': 'Repair: {0}/{1}',
        'hud.repairEmpty': 'Repair: Empty',
        'hud.mode': 'Mode: {0}',
        'hud.bossKills': 'Boss Kills: {0}',

        'enemy.elite': 'Elite',

        'ui.paused': 'Game Paused',
        'ui.pauseHint': 'Press P to resume',
        'ui.pauseBtn': 'Pause',
        'ui.gameOver': 'Game Over',
        'ui.totalDamage': 'Total Damage: {0}',
        'ui.spaceReturn': 'Press SPACE to return to menu',
        'ui.victory': '🎉 Victory! 🎉',
        'ui.defeated': 'Defeated {0}!',
        'ui.finalScore': 'Final Score: {0}',
        'ui.blindStatus': 'Blinded',
        'ui.blindRemaining': 'Time left: {0}s',
        'ui.langToggle': '中文',
        'ui.gameTitle': 'Mech Combat',

        'boss.CRIMSON_KING': 'Crimson King',
        'boss.SUBLIME_MOON': 'Sublime Moon',
        'boss.STAR_DEVOURER': 'Star Devourer',
        'boss.UGLY_EMPEROR': 'Ugly Emperor',
        'boss.unknown': 'Unknown Boss',
        'bossDesc.CRIMSON_KING': 'Crimson lord of terror, wielding the power of darkness',
        'bossDesc.SUBLIME_MOON': 'Cerulean mystic ruler, radiating icy moonlight power',
        'bossDesc.STAR_DEVOURER': 'Monochrome void destroyer, devouring all light and dark',
        'bossDesc.UGLY_EMPEROR': 'Twisted chaotic emperor, master of distortion and chaos',

        'boss.pierce': 'Pierce!',
        'boss.blind': 'Blind',
        'boss.immune': 'Immune',
        'boss.clone': 'Clone',
        'boss.burn': 'Burning',

        'boss.blindActive': 'Blindness Active {0}s',
        'boss.blindUnlockNeed': 'Blind unlock: {0} DMG needed',
        'boss.blindUnlocked': 'Blind skill unlocked',
        'boss.blindCooldown': 'Blind CD {0}s {1}',
        'boss.blindReady': 'Blind skill ready {0}',
        'boss.phase1': '(Phase 1)',
        'boss.phase2label': '(Phase 2)',
        'boss.phase2Visible': 'Phase 2 - Range {0}/{1} - Visible',
        'boss.phase2Cloaked': 'Phase 2 - Range {0}/{1} - Cloaked',
        'boss.phase2Trigger': 'Phase 2 trigger: {0} DMG needed',

        'mode.BOSS_BATTLE': 'Boss Battle',
        'modeDesc.BOSS_BATTLE': 'Challenge powerful bosses',
        'mech.HYBRID': 'Hybrid Mech',

        'weapon.gun': 'Auto Rifle',
        'weapon.sword': 'Beam Saber',
        'weapon.laser_spear': 'Laser Spear',
        'weapon.cluster_missile': 'Cluster Missile',
        'weapon.laser_rifle': 'Laser Rifle',
        'weapon.missile_launcher': 'Missile Launcher ×15',
        'weapon.ciws': 'CIWS',
        'weapon.plasma_missile': 'Plasma Missile ×6',
        'weapon.super_weapon': 'Super Missile',
        'weapon.moonlight_greatsword': 'Moonlight Greatsword',
        'weapon.pulse_shield': 'Pulse Shield',
        'weapon.emp': 'EMP',
        'weapon.counter_mech': 'Counter Strike',
        'weapon.decoy_clone': 'Decoy Clone',

        'weaponDesc.gun': 'Ranged | High ROF | Predictive Aim',
        'weaponDesc.sword': 'Melee | High DMG | Dash Attack',
        'weaponDesc.laser_spear': 'Mid-range Thrust | Charge | Rush',
        'weaponDesc.cluster_missile': 'Proximity Split ×8 | Tracking | Homing',
        'weaponDesc.laser_rifle': 'Hold to Charge | Aim Beam | Overheat',
        'weaponDesc.missile_launcher': '1.1s Homing | AoE Blast | High DMG',
        'weaponDesc.ciws': 'Auto-intercept | 30 Rounds | Missile Priority',
        'weaponDesc.plasma_missile': 'Proximity Fuse | Plasma DoT | Stackable',
        'weaponDesc.super_weapon': '100 DMG | Single Use | Dual Slot',
        'weaponDesc.moonlight_greatsword': '200 DMG | Massive Beam | 4 Slots | Single Use',
        'weaponDesc.pulse_shield': '70% Reduction | 15s Duration | 40s CD',
        'weaponDesc.emp': 'AoE + Stun | Damage Falloff | 30s CD',
        'weaponDesc.counter_mech': '3s -40% DMG | 50% Reflect | 15s CD',
        'weaponDesc.decoy_clone': '3 Decoys | 4s Stealth | 35s CD',

        'ws.attacking': 'Attacking...',
        'ws.stagger': 'Stagger: {0}s',
        'ws.dashPush': 'Dash Push...',
        'ws.cooldown': 'Cooldown: {0}s',
        'ws.cooldownS': 'CD: {0}s',
        'ws.ready': 'Ready',
        'ws.readyShort': 'Ready',
        'ws.reloading': 'Reloading...',
        'ws.ammoEmpty': 'Empty! Auto-reload',
        'ws.ammo': 'Ammo: {0}/{1}',
        'ws.pressR': ' | Press R',
        'ws.overheat': 'Overheat! {0}s',
        'ws.charging': 'Charging {0}%',
        'ws.coolingDown': 'Cooling...',
        'ws.heat': 'Heat: {0}/{1}',
        'ws.rushing': 'Rushing!',
        'ws.recovering': 'Recovering',
        'ws.launching': 'Launching... ({0} left)',
        'ws.launchingSimple': 'Launching...',
        'ws.shielding': 'Shield: {0}s',
        'ws.countering': 'Counter: {0}s',
        'ws.stealth': 'Stealth: {0}s',
        'ws.slashing': 'Slashing...',
        'ws.used': 'Used',
        'ws.cooldownRemaining': 'Cooldown {0}s',

        'player.dodging': 'Dodging...',
        'player.dodgeCooldown': 'Dodge CD: {0}s',
        'player.dodgeReady': 'Dodge Ready',
        'player.softLock': 'Soft Lock',
        'player.hardLock': 'Hard Lock',
        'player.manualLock': 'Manual',
    }
};

const guideData = {
    zh: [
        {
            id: 'controls', name: '操作说明', color: '#4488FF',
            content: [
                '【移动】 WASD / 方向键',
                '【左手武器】 鼠标左键',
                '【右手武器】 鼠标右键',
                '【左肩武器】 Q键',
                '【右肩武器】 E键',
                '【隐藏机能】 Shift键',
                '【闪避】 空格 + 方向键（0.15秒，冷却0.35秒）',
                '【切换锁定】 F键（软锁→硬锁→手动锁）',
                '【切换目标】 C键（硬锁模式下）',
                '【重装弹药】 R键',
                '【维修包】 Ctrl键（+60HP，共3个）',
                '【暂停】 P键',
                '【返回主菜单】 ESC键',
                '',
                '— 锁定系统 —',
                '软锁：自动瞄准最近敌人',
                '硬锁：锁定当前目标不放，C键切换',
                '手动锁：鼠标控制瞄准方向',
            ]
        },
        {
            id: 'hand_weapons', name: '手部武器', color: '#4169E1',
            items: [
                { name: '自动步枪', color: '#4169E1', lines: [
                    '伤害 6/发 | 射速 5发/秒',
                    '弹匣 30发 | 重装 2秒',
                    '自动预瞄：根据目标速度预判落点',
                ]},
                { name: '脉冲光束军刀', color: '#ff6b6b', lines: [
                    '伤害 50 | 120°扇形范围',
                    '冷却 4.8秒',
                    '刀推：距目标过远时自动冲刺接近',
                ]},
                { name: '镭射长枪', color: '#00FFFF', lines: [
                    '伤害 25 | 冲锋距离 400像素',
                    '冲锋速度 40 | 冷却 5秒',
                    '可扎穿敌人并带其一起移动',
                ]},
                { name: '镭射步枪', color: '#FF4444', lines: [
                    '伤害 18 | 蓄力 1秒后发射',
                    '射击间隔 0.7秒 | 射程无限',
                    '过热系统：每发+50热量，≥200过热',
                    '过热后强制散热7秒',
                ]},
                { name: '分裂飞弹', color: '#FFD700', lines: [
                    '发射1枚母弹，持续索敌（8秒无目标自爆）',
                    '接近敌人120px分裂为8枚子弹',
                    '子弹伤害 3 | 高追踪性 | 冷却 4秒',
                    '分裂后先扇形散开再制导',
                ]},
            ]
        },
        {
            id: 'shoulder_weapons', name: '肩部武器', color: '#FF8800',
            items: [
                { name: '15连导弹发射器', color: '#FFD700', lines: [
                    '每次齐射 15枚 | 每枚 3伤害',
                    '前1.1秒强追踪 | 爆炸半径 80px',
                    '冷却 4秒',
                ]},
                { name: '近防炮 (CIWS)', color: '#00FF88', lines: [
                    '全自动射击 30发/秒 | 弹仓 30发',
                    '优先级：导弹 > 月牙弹 > 策反弹 > 机雷 > 敌人',
                    '对制导武器一发摧毁',
                    '对敌人本体 40%概率造成伤害',
                ]},
                { name: '6连电浆飞弹', color: '#00FFCC', lines: [
                    '6枚连射 | 近炸引信（55px引爆）',
                    '生成电浆场：持续1秒，每0.25秒造成3伤害',
                    '多个电浆场可叠加 | 冷却 5秒',
                ]},
                { name: '超级导弹', color: '#FF0000', lines: [
                    '伤害 100 | 占用左右肩双槽位',
                    '爆炸半径 400px | 超强追踪 4.1秒',
                    '每场战斗限用1次',
                ]},
                { name: '月光大剑', color: '#88CCFF', lines: [
                    '伤害 200 | 占用右手+双肩+隐藏机能共4槽位',
                    '光刃长度为光束军刀的7倍（1050px）',
                    '机体朝向±90°共180°范围 | 1秒完成扫击',
                    '无法秒杀Boss（最低保留1HP）',
                    '每场战斗限用1次',
                ]},
            ]
        },
        {
            id: 'hidden', name: '隐藏机能', color: '#00FFFF',
            items: [
                { name: '脉冲护盾', color: '#00FFFF', lines: [
                    '70%伤害减免 | 持续 15秒',
                    '冷却 40秒',
                ]},
                { name: 'EMP电磁脉冲', color: '#66CCFF', lines: [
                    '范围 490px | 最大伤害 100',
                    '距离越远伤害越低 | 附加0.5秒僵直',
                    '冷却 30秒',
                ]},
                { name: '反制重击', color: '#FF8C00', lines: [
                    '持续 3秒 | 受伤减少 40%',
                    '将受到伤害的50%反射给最近敌人',
                    '冷却 15秒',
                ]},
                { name: '诱饵分身', color: '#4488FF', lines: [
                    '释放 3 个全息诱饵（等边三角形散开）',
                    '诱饵 40HP | 最多存活 7秒',
                    '玩家进入 4秒不可锁定状态',
                    '敌方AI/导弹/子弹转向攻击诱饵',
                    '冷却 35秒',
                ]},
            ]
        },
        {
            id: 'bosses', name: 'Boss图鉴', color: '#FF4444',
            items: [
                { name: '★ 血红之王', color: '#8B0000', lines: [
                    'HP 300 | 导弹洗地型',
                    '',
                    '— 攻击方式 —',
                    '60枚导弹齐射，四方向轮流，每枚6伤害',
                    '导弹带延迟制导，0.3秒后开始追踪',
                    '',
                    '— 特殊机制 —',
                    '累积减伤：1秒内受伤越多减伤越高（不归零）',
                    '导弹闪避：被追踪时80%闪避',
                    '回血：每3秒 45%概率恢复6-20HP',
                    '',
                    '— 建议 —',
                    '近防炮拦截导弹，配合近战输出',
                    '避免短时间集中火力触发高减伤',
                ]},
                { name: '★★ 冰之姬', color: '#4682B4', lines: [
                    'HP 200 | 高机动刺客型',
                    '',
                    '— 攻击方式 —',
                    '月牙追踪弹：5发齐射，10伤害+僵直',
                    '回旋斩：两段(12+18)伤害，可摧毁附近导弹',
                    '回旋镖形态：5个回旋镖，每个30伤害',
                    '分身：4个分身，每1.5秒发射15伤害月牙弹',
                    '',
                    '— 特殊机制 —',
                    '瞬移：距远或导弹靠近时瞬移到玩家背后',
                    '极高导弹闪避：90%概率闪避',
                    '',
                    '— 建议 —',
                    '近防炮拦截月牙弹，导弹对她效果有限',
                    '注意瞬移后的背刺，保持移动',
                ]},
                { name: '★★★ 噬星者', color: '#333333', lines: [
                    'HP 300 | 战术压制型',
                    '',
                    '— 攻击方式 —',
                    '光束步枪：25伤害+0.7秒僵直',
                    '自动步枪：近距离6伤害/发，30发/秒',
                    '浮游炮×3：各70HP，镭射15伤害+僵直',
                    '',
                    '— 特殊机制 —',
                    '失明：屏幕全黑，无法切换锁定',
                    '二阶段(≤80HP)：隐身(200px内可见)',
                    '导弹反转：75%玩家导弹被策反攻击玩家',
                    '',
                    '— 建议 —',
                    '优先摧毁浮游炮，近防炮拦截策反导弹',
                    '失明时保持移动，二阶段需近距离作战',
                ]},
                { name: '★★★★ 丑皇', color: '#8B4513', lines: [
                    'HP 250 | 区域控制型',
                    '',
                    '— 攻击方式 —',
                    '混沌弹幕：8发/波，4伤害/发',
                    '扭曲光环：半径80px持续伤害场',
                    '机雷(一阶段)：引爆15伤害',
                    '燃烧瓶(二阶段)：产生燃烧区域',
                    '',
                    '— 特殊机制 —',
                    '一阶段：免疫导弹伤害',
                    '二阶段(≤100HP)：仅受导弹伤害，伤害×2',
                    '混沌传送：每8秒传送到玩家附近',
                    '',
                    '— 建议 —',
                    '一阶段用步枪/激光/近战，近防炮清机雷',
                    '二阶段全力导弹输出（伤害翻倍）',
                    '两阶段需完全不同的武器策略',
                ]},
            ]
        },
        {
            id: 'status', name: '状态效果', color: '#AAAAAA',
            content: [
                '【僵直】 短暂无法移动和行动',
                '【燃烧】 持续5秒，每0.1秒受2伤害，移速-20%',
                '【失明】 噬星者专属，屏幕全黑，无法切换锁定',
                '',
                '— 玩家属性 —',
                '生命值：150',
                '移动速度：20',
                '维修包：3个，每个恢复60HP',
                '闪避：0.15秒，冷却0.35秒',
            ]
        },
    ],

    en: [
        {
            id: 'controls', name: 'Controls', color: '#4488FF',
            content: [
                '[Move] WASD / Arrow Keys',
                '[Left Hand] Left Mouse Button',
                '[Right Hand] Right Mouse Button',
                '[Left Shoulder] Q Key',
                '[Right Shoulder] E Key',
                '[Hidden Ability] Shift Key',
                '[Dodge] Space + Direction (0.15s, 0.35s CD)',
                '[Toggle Lock] F Key (Soft → Hard → Manual)',
                '[Switch Target] C Key (Hard Lock mode)',
                '[Reload] R Key',
                '[Repair Kit] Ctrl Key (+60HP, 3 total)',
                '[Pause] P Key',
                '[Return to Menu] ESC Key',
                '',
                '— Lock System —',
                'Soft Lock: Auto-aim nearest enemy',
                'Hard Lock: Stay locked on target, C to switch',
                'Manual Lock: Mouse controls aim direction',
            ]
        },
        {
            id: 'hand_weapons', name: 'Hand Weapons', color: '#4169E1',
            items: [
                { name: 'Auto Rifle', color: '#4169E1', lines: [
                    'Damage 6/shot | Fire Rate 5/sec',
                    'Magazine 30 | Reload 2s',
                    'Predictive Aim: leads target based on velocity',
                ]},
                { name: 'Beam Saber', color: '#ff6b6b', lines: [
                    'Damage 50 | 120° arc range',
                    'Cooldown 4.8s',
                    'Dash Push: auto-dash to distant targets',
                ]},
                { name: 'Laser Spear', color: '#00FFFF', lines: [
                    'Damage 25 | Charge distance 400px',
                    'Charge speed 40 | Cooldown 5s',
                    'Can impale enemies and carry them along',
                ]},
                { name: 'Laser Rifle', color: '#FF4444', lines: [
                    'Damage 18 | 1s charge before firing',
                    'Fire interval 0.7s | Infinite range',
                    'Overheat system: +50 heat/shot, ≥200 overheat',
                    'Forced 7s cooldown when overheated',
                ]},
                { name: 'Cluster Missile', color: '#FFD700', lines: [
                    'Fires 1 mother missile, continuous tracking (8s self-destruct)',
                    'Splits into 8 sub-missiles at 120px proximity',
                    'Sub-missile DMG 3 | High tracking | 4s CD',
                    'Fan spread after split, then guided',
                ]},
            ]
        },
        {
            id: 'shoulder_weapons', name: 'Shoulder Weapons', color: '#FF8800',
            items: [
                { name: 'Missile Launcher ×15', color: '#FFD700', lines: [
                    '15 missiles per salvo | 3 DMG each',
                    '1.1s strong homing | 80px blast radius',
                    'Cooldown 4s',
                ]},
                { name: 'CIWS', color: '#00FF88', lines: [
                    'Full-auto 30 rounds/sec | 30 round mag',
                    'Priority: Missiles > Crescents > Reversed > Mines > Enemies',
                    'One-shot kill on guided weapons',
                    '40% chance to hit enemy body',
                ]},
                { name: 'Plasma Missile ×6', color: '#00FFCC', lines: [
                    '6 rapid-fire | Proximity fuse (55px trigger)',
                    'Creates plasma field: 1s duration, 3 DMG per 0.25s',
                    'Multiple fields stack | Cooldown 5s',
                ]},
                { name: 'Super Missile', color: '#FF0000', lines: [
                    'Damage 100 | Occupies both shoulder slots',
                    '400px blast radius | 4.1s super homing',
                    'Single use per battle',
                ]},
                { name: 'Moonlight Greatsword', color: '#88CCFF', lines: [
                    'Damage 200 | Occupies R-Hand + Both Shoulders + Ability (4 slots)',
                    'Blade length 7× Beam Saber (1050px)',
                    '±90° sweep (180° total) | 1s sweep time',
                    'Cannot one-shot bosses (min 1 HP)',
                    'Single use per battle',
                ]},
            ]
        },
        {
            id: 'hidden', name: 'Hidden Abilities', color: '#00FFFF',
            items: [
                { name: 'Pulse Shield', color: '#00FFFF', lines: [
                    '70% damage reduction | 15s duration',
                    'Cooldown 40s',
                ]},
                { name: 'EMP', color: '#66CCFF', lines: [
                    'Range 490px | Max damage 100',
                    'Damage falls off with distance | 0.5s stagger',
                    'Cooldown 30s',
                ]},
                { name: 'Counter Strike', color: '#FF8C00', lines: [
                    '3s duration | 40% damage reduction',
                    'Reflects 50% of damage taken to nearest enemy',
                    'Cooldown 15s',
                ]},
                { name: 'Decoy Clone', color: '#4488FF', lines: [
                    'Deploys 3 holographic decoys (triangle formation)',
                    'Decoy 40HP | Max 7s lifetime',
                    'Player becomes untargetable for 4s',
                    'Enemy AI/missiles/bullets redirect to decoys',
                    'Cooldown 35s',
                ]},
            ]
        },
        {
            id: 'bosses', name: 'Boss Guide', color: '#FF4444',
            items: [
                { name: '★ Crimson King', color: '#8B0000', lines: [
                    'HP 300 | Missile Barrage Type',
                    '',
                    '— Attacks —',
                    '60-missile salvo, 4 directions rotating, 6 DMG each',
                    'Missiles have delayed guidance, tracking after 0.3s',
                    '',
                    '— Special Mechanics —',
                    'Cumulative DR: more hits in 1s = higher reduction',
                    'Missile dodge: 80% evasion when tracked',
                    'Regen: 45% chance to heal 6-20 HP every 3s',
                    '',
                    '— Tips —',
                    'CIWS to intercept missiles, combine with melee',
                    'Avoid burst damage to prevent high DR',
                ]},
                { name: '★★ Sublime Moon', color: '#4682B4', lines: [
                    'HP 200 | High-Mobility Assassin Type',
                    '',
                    '— Attacks —',
                    'Crescent tracking shots: 5 per volley, 10 DMG + stagger',
                    'Spin slash: two stages (12+18) DMG, destroys nearby missiles',
                    'Boomerang form: 5 boomerangs, 30 DMG each',
                    'Clones: 4 clones, fire 15 DMG crescents every 1.5s',
                    '',
                    '— Special Mechanics —',
                    'Teleport: blinks behind player when distant or missiles approach',
                    'Extreme missile evasion: 90% dodge chance',
                    '',
                    '— Tips —',
                    'CIWS to intercept crescents; missiles are ineffective',
                    'Watch for backstab after teleport, keep moving',
                ]},
                { name: '★★★ Star Devourer', color: '#333333', lines: [
                    'HP 300 | Tactical Suppression Type',
                    '',
                    '— Attacks —',
                    'Beam rifle: 25 DMG + 0.7s stagger',
                    'Auto rifle: close range 6 DMG/shot, 30 rps',
                    'Floating guns ×3: 70 HP each, 15 DMG laser + stagger',
                    '',
                    '— Special Mechanics —',
                    'Blindness: screen goes black, cannot switch lock',
                    'Phase 2 (≤80 HP): cloaked (visible within 200px)',
                    'Missile reversal: 75% of player missiles turned against you',
                    '',
                    '— Tips —',
                    'Destroy floating guns first; CIWS intercepts reversed missiles',
                    'Keep moving when blinded; Phase 2 requires close combat',
                ]},
                { name: '★★★★ Ugly Emperor', color: '#8B4513', lines: [
                    'HP 250 | Area Control Type',
                    '',
                    '— Attacks —',
                    'Chaos barrage: 8/wave, 4 DMG each',
                    'Distortion aura: 80px radius persistent damage field',
                    'Mines (Phase 1): 15 DMG on detonation',
                    'Molotov (Phase 2): creates burning area',
                    '',
                    '— Special Mechanics —',
                    'Phase 1: Immune to missile damage',
                    'Phase 2 (≤100 HP): Only takes missile DMG, ×2 multiplier',
                    'Chaos teleport: teleports near player every 8s',
                    '',
                    '— Tips —',
                    'Phase 1: use rifle/laser/melee; CIWS clears mines',
                    'Phase 2: full missile assault (double damage)',
                    'Two phases require completely different weapon strategies',
                ]},
            ]
        },
        {
            id: 'status', name: 'Status Effects', color: '#AAAAAA',
            content: [
                '[Stagger] Briefly unable to move or act',
                '[Burning] 5s duration, 2 DMG per 0.1s, -20% move speed',
                '[Blindness] Star Devourer exclusive: screen goes black, cannot switch lock',
                '',
                '— Player Stats —',
                'Health: 150',
                'Move Speed: 20',
                'Repair Kits: 3, each restores 60 HP',
                'Dodge: 0.15s, cooldown 0.35s',
            ]
        },
    ]
};
